### ISSUE TITLE
Нету подсветки синтаксиса в MineCode

### ISSUE THREAD

**Issue by grozahn** [IgorTimofeev/MineOS#114]

**Comment by IgorTimofeev** [comment]
Мяу? Так кнопочка же существует для ее переключения:
![2018-05-20 22 40 16](https://user-images.githubusercontent.com/11760002/40282927-c8aeff14-5c7e-11e8-96dc-b688c589843d.png)

Или после нажатия тоже не активируется?

**Comment by grozahn** [comment]
А ведь действительно кнопочка есть. Если не впадлу, добавь кнопку в панели меню.

**Comment by IgorTimofeev** [comment]
Угу, ща
