### ISSUE TITLE
Ревквестую эмулятор терминала с автокомплитом как в CompucterCraft

### ISSUE THREAD

**Issue by grozahn** [IgorTimofeev/MineOS#116]

**Comment by IgorTimofeev** [comment]
Не-а, этого точно не будет. Во-первых, я терпеть не могу консольный интерфейс, предпочитая графический. Во-вторых, этот велосипед мне будет на фиг не нужен, т.к. всегда есть возможность вернуться в OpenOS Shell. В-третьих, все доки по написанию ПО с тонной примеров и иллюстраций лежат в открытом доступе, а магаз софтин так и ждет, чтоб в него что-то запостили. Так что, как гриццо, "хочешь - сделай сам"
