### ISSUE TITLE
Падает при выборе опций диска в приложении Control

### ISSUE THREAD

**Issue by grozahn** [IgorTimofeev/MineOS#117]
![scr](https://i.imgur.com/NTzBd0z.jpg)

**Comment by IgorTimofeev** [comment]
У тебя старая версия программы. Обновился бы хоть ради приличия, метода "addUniversalContainer" уже сто лет как не существует. Странно вообще, что у тебя этот модуль не апгрейднулся автоматически

**Comment by grozahn** [comment]
Нету обновлений, а сам баг заметил после обновления

**Comment by IgorTimofeev** [comment]
НУ ЛЯ, ЭТО Ж С ДИВАНА ВСТАВАТЬ НАДО, ПРОВЕРЯТЬ ВСЕ ВРУЧНУЮ... А ТУТ КОШЕЧКА СПИТ :(

**Comment by IgorTimofeev** [comment]
Дыа, обнаружил косячок. Фиксанул, пасебо
