### ISSUE TITLE
Specified grid position (2x1) is out of layout grid range

### ISSUE THREAD

**Issue by yyk419476391** [IgorTimofeev/MineOS#118]
![tim 20180529202629](https://user-images.githubusercontent.com/18556014/40658720-b60b9276-637e-11e8-8c7c-9bb3155b599a.png)
it happens after i updated system

**Comment by IgorTimofeev** [comment]
wtf, seems like main OS file hasn't been updated. I'll fix it, but use this to re-download file manually:
> wget https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/OS.lua /bin/OS.lua -f
