### ISSUE TITLE
Пакетный  менеджер

### ISSUE THREAD

**Issue by grozahn** [IgorTimofeev/MineOS#119]
Идея может и бредовая, но было бы пиздато сделать формат файлов типа .pkg, из которых будут устанавливаться проги. Может быть удобным для передачи прог при помощи дискет.

**Comment by IgorTimofeev** [comment]
Чому бредовая, вполне норм. На данный момент уже есть поддержка архивов без какой-либо степени сжатия данных (т.е. пакетов) - правда,  распаковывать их приходится все же средствами самой оськи. Еще вопрос в том, насколько сия система практически полезна: ведь передавать файлы можно и при помощи модемчиков буквально парой кликов. А вот самораспаковывающиеся пакеты были бы рили интересны

**Comment by vasilyokunevs** [comment]
А идея хорошая, прямо как .deb пакеты. Только бы до собственноручной компиляции не дойти...

**Comment by sziberov** [comment]
@antalink Как раз до нее и дойдем, если такую хрень предлагать. .pkg надо.

**Comment by IgorTimofeev** [comment]
Кпец: до сих пор не ебу, о чем вы - а они там уже сидят, потирают лапки и что-то ждут(

Есть же маркет с либами, скриптами и приложухами, нах вам пакетная линуксо-параша?

**Comment by sziberov** [comment]
@IgorTimofeev Так я не жду, просто к слову. Если и вводить установщики, которые могут систему кардинально менять то только ОС Иксовые.

**Comment by IgorTimofeev** [comment]
@sziberov Фига потно! Нет шоб грамотно кодить standalone-приложухи без засирания системы :(
