### ISSUE TITLE
GUI interface of MineOS cannot be displayed in multiplayer game?

### ISSUE THREAD

**Issue by 054545641** [IgorTimofeev/MineOS#120]
Configuration:
It's a MC 1.10.2 Server, and with OpenComputers version 1.7.2.170, and Forge version 1.10.2-12.18.3.2185 on it.
In a **multiplayer game** I tried to install Mine OS on to a **Tier 3 Server** on rack with hardware below:
- Tier 3 CPU
- Internet Card
- Tier 3 GPU x2
- Tier 3.5 RAM x4
- Tier 3 HDD

Reproduction:
At first I installed Open OS, and then I executed command "pastebin run 0nm5b1ju"
Instillation is in GUI, and everything seems to be good.
And BIOS was rewritten to a Mine OS EFI successfully.
**But after BIOS interface, the CLI of Open OS showed again, no GUI interface showed.**
I tried to execute command "OS", but I got an error below:
> /lib/image.lua:232: attempt to index a boolean value (local 'picture'):
>stack traceback:
>&ensp;&ensp;&ensp;&ensp;/lib/image.lua:232: in field 'getWidth'
>&ensp;&ensp;&ensp;&ensp;/bin/OS,lua:227: in upvalue 'changeWallpaper'
>&ensp;&ensp;&ensp;&ensp;/bin/OS.lua:1150: in local 'createOSWindow'
>&ensp;&ensp;&ensp;&ensp;/bin/OS.lua:1160: in main chunk
>&ensp;&ensp;&ensp;&ensp;(...tail calls...)
>&ensp;&ensp;&ensp;&ensp;[C]: in function 'xpcall'
>&ensp;&ensp;&ensp;&ensp;machine:751: in global 'xpcall'
>&ensp;&ensp;&ensp;&ensp;/lib/process.lua:63: in function </lib/process.lua:59>

I even tried to change CPU architechture from lua 5.3 to lua 5.2 and erase all data, then performed steps above, but no use.

However **the Mine OS works in the single-player world**, with the same hardware and operations on it.
Is it a bug?
THX
----------------------------------------------------update-------------------------------------------------------
I canceled wallpaper and pre-installed apps while installation, and it works.
But I don't understand still why these can cause such an error.
Does network condition matter?

**Comment by IgorTimofeev** [comment]
It seems like your wallpaper image has been corrupted while downloading to HDD - that's why image.load() function has returned **false**, **reason** values. For example, it may happen when server host bans some IP-addresses where pictures is stored.

By the way, I'll add some conditions to prevent this in future with corresponding alert window, thanks
