### ISSUE TITLE
App Market: Web request failed: Connection timed out: connect

### ISSUE THREAD

**Issue by PomHolms** [IgorTimofeev/MineOS#121]
Я тупой, поэтому опишу так: Играем с другом на локальном серваке, комп вроде правильный, 
2 памяти tier 3.5, видюха tier 3, ЦП tier 3, жёсткий диск tier 3. OpenOS установил на диск, MineOS тоже вроде нормально.
Когда пытаюсь зайти в App Market идёт загрузка где то сек 10-15, затем выбивает ошибку сверху.
На сайт http://eliteclubsessions.ru зайти не могу, только с помощью VPN.
Менять провайдера шоли?
![screenshot_1](https://user-images.githubusercontent.com/23733394/41820005-27ef3a2e-77d3-11e8-9ab2-db883cd73e06.png)

**Comment by Eugene8388608** [comment]
или впн серваку делать

**Comment by IgorTimofeev** [comment]
Ркн лочит IP клаудфлейра, впн в помощь, да

**Comment by PomHolms** [comment]
прошу прощения, но как впн на сервак сделать? просто для компа скачать, или как?

**Comment by IgorTimofeev** [comment]
Я не знать, не пользовался никогда. Вот @Eugene8388608 точно знать

**Comment by Eugene8388608** [comment]
впн на сервер майна, хз как, но это единственное решение.
