### ISSUE TITLE
Время.

### ISSUE THREAD

**Issue by BrightYC** [IgorTimofeev/MineOS#123]
Не возможно установить своё время,покопался в конфиг-файлах-в итоге ничего не нашёл кроме формата даты и часового пояса.Время не валидное,хотя os.date показывает точную дату.Может стоит сделать изменение времени на своё усмотрение?
![default](https://user-images.githubusercontent.com/28766913/42232400-b4d85638-7f07-11e8-9530-f5a00e922590.PNG)

**Comment by kcinnaJlol** [comment]
Translation according to Google Translate:

>Time
>
>It's not possible to set your time, dig into config-files-in the end, nothing found except the date format and the time zone. Time is not valid, although os.date shows the exact date. Can it make a time change at its discretion?

**Comment by IgorTimofeev** [comment]
Хм, интересно. По задумке комп создает файл, чекает таймштамп его изменения, удаляет файл - и от созданной временной метки отсчитывает времечко. Судя по всему, время на сервере принудительно сбрасывается на 0 после рестарта - отсюда и такая вот залупа. Как вариант - могу добавить селектор "использовать время os.sleep вместо реального"

**Comment by IgorTimofeev** [comment]
Раз уж нахуярили софтину для настроек, то заодно добавили фичу выбора игрового времени вместо реального. Надеюсь, этого достаточно:

![2018-09-12 14 39 14](https://user-images.githubusercontent.com/11760002/45422696-a805bd00-b699-11e8-9fa1-490a7af3c127.png)
