### ISSUE TITLE
APp market

### ISSUE THREAD

**Issue by crossingpants5** [IgorTimofeev/MineOS#125]

**Comment by crossingpants5** [comment]
why isnt the app market working?

**Comment by kgaudium** [comment]
The site that supports the market is closed, but on the territory of the Russian Federation is blocked. =(

**Comment by crossingpants5** [comment]
then where can i get the apps i need

**Comment by kgaudium** [comment]
you can download apps on this page: https://github.com/IgorTimofeev/MineOS/tree/master/Applications . (But it can don't work). Just put these files in a folder with the world.
![image](https://user-images.githubusercontent.com/41070203/42675409-9bd0e106-867c-11e8-8f99-6f71479ca182.png) 
![image](https://user-images.githubusercontent.com/41070203/42675417-a379ba72-867c-11e8-9607-cd6cc794de9f.png) 
![image](https://user-images.githubusercontent.com/41070203/42675421-a9af817e-867c-11e8-9440-4561ce5511ab.png) 
![image](https://user-images.githubusercontent.com/41070203/42675428-b167c322-867c-11e8-881a-8dd32fb2b8f6.png) 
![image](https://user-images.githubusercontent.com/41070203/42675434-b776c89e-867c-11e8-8d49-48276f648917.png)

And add .app to end of name of the folder

**Comment by kgaudium** [comment]
I tried to set VK in this way, but there was an error

**Comment by crossingpants5** [comment]
what if im on a server

**Comment by kcinnaJlol** [comment]
What is your computer setup?
If it doesnt have an Internet card, then that is the problem.
If it has a internet card, then

1. You are on a server and the server does not allow http requests
2. The app market is down

**Comment by kcinnaJlol** [comment]
Please comment your computer setup.

**Comment by kcinnaJlol** [comment]
On servers where http requests and tcp sockets are allowed, you are fine. Else, if you host the server, somehow allow http and tcp. Or, if someone else hosts that server, ask the owner to allow http and tcp

**Comment by crossingpants5** [comment]
![image](https://user-images.githubusercontent.com/41082936/43105123-c5c61d78-8ea1-11e8-8aa0-91fe28444fe9.png)

Can some one translate this

**Comment by Eugene8388608** [comment]
this aplication needs radio from OpenFM mod

**Comment by Eugene8388608** [comment]
and not all versions of that mod work correct with this app

**Comment by Eugene8388608** [comment]
and with not all versions of that mod this app works correctly

**Comment by fgRuslan** [comment]
because mod's author is a faggot. I was testing it on november version. It was ok

**Comment by crossingpants5** [comment]
ok thanks

**Comment by IgorTimofeev** [comment]
meow-meow
