### ISSUE TITLE
show Image in ecs.UniversalWindow

### ISSUE THREAD

**Issue by veso266** [IgorTimofeev/MineOS#127]
Hi I was playing around a bit with ecs.UniversalWindow
```lua
ecs.universalWindow("auto", "auto", 36, 0x262626, true, 
					{"EmptyLine"},
					{"CenterText", ecs.colors.orange, "Radio v1.0"}, 
					{"EmptyLine"},
					{"CenterText", 0xFFFFFF, "Author:"},
					{"CenterText", 0xBBBBBB, "Igor Timofeev"},
					{"CenterText", 0xBBBBBB, "vk.com/id7799889"},
					{"EmptyLine"},
					{"CenterText", 0xFFFFFF, "Tester:"},
					{"CenterText", 0xBBBBBB, "Oleg Hrechyhyn"}, 
					{"CenterText", 0xBBBBBB, "http://vk.com/id250552893"},
					{"EmptyLine"},
					{"CenterText", 0xFFFFFF, "Author of Ideas:"},
					{"CenterText", 0xBBBBBB, "MrHerobrine с Dreamfinity"}, 
					{"EmptyLine"},
					{"Button", {ecs.colors.orange, 0xffffff, "OK"}}
				)
```
and yes it is from Radio.app would like to change about windows a bit :)

and I was wondering on how can I show an image after {"EmptyLine"},

lets suppose I would like to show that image: https://3wa6swswssi2rh7s6nj1ju16-wpengine.netdna-ssl.com/wp-content/uploads/2017/07/The-Wolf-Moon-Of-12-January-2017.jpg

below all the text
so How can I convert it to the right format and then display it?

Thanks for Anwsering and Best Regards

**Comment by veso266** [comment]
do you have any idea what this other methods to show the image could be

also converter looks realy nice (but its background looks even nicer :))

**Comment by fgRuslan** [comment]
```lua
--Example
local buffer = require("doubleBuffering")
local image = require("image")

buffer.image(1, 1, image.load("/MineOS/Pictures/Raspberry.pic"))
buffer.draw()
```

**Comment by fgRuslan** [comment]
Also, ECSAPI library is deprecated, I recommend you to use doubleBuffering and GUI libraries.

**Comment by veso266** [comment]
Thanks
it kinda works :) (it errors out after 2 seconds)
```lua
--Example
local buffer = require("doubleBuffering")
local image = require("image")

buffer.drawImage(1, 1, image.load("/MineOS/Pictures/Wolf.pic"))
while true do
buffer.drawChanges()
buffer.flush()
end
```

**Comment by fgRuslan** [comment]
What if you change
```lua
while true do
buffer.drawChanges()
buffer.flush()
end
```

to

```lua
buffer.draw()
```

**Comment by fgRuslan** [comment]
I haven't checked it for a long time so I can not help you with that

**Comment by IgorTimofeev** [comment]
BigLetters library draws text directly to screen buffer and not interacts with GUI library anyway. You should create an empty GUI.object with .draw() method that draws your text:

```lua
local GUI = require("GUI")
local bigLetters = require("bigLetters")

--------------------------------------------------------------------------------

local mainContainer = GUI.fullScreenContainer()
mainContainer:addChild(GUI.panel(1, 1, mainContainer.width, mainContainer.height, 0x262626))

-- Specify any text you want to
local text = "hello world"
-- Obtain big letters size in pixels
local textWidth, textHeight = bigLetters.getTextSize(text)
-- Create an empty object with text size
local object = mainContainer:addChild(GUI.object(3, 2, textWidth, textHeight))
-- Attach a .draw() method that will draw it's content to screen buffer
object.draw = function()
	bigLetters.drawText(object.x, object.y, 0xFFFFFF, text)
end

--------------------------------------------------------------------------------

mainContainer:drawOnScreen(true)
mainContainer:startEventHandling()
```

Here's the result:

![2018-09-06 14 56 26](https://user-images.githubusercontent.com/11760002/45155902-27504800-b1e5-11e8-871e-c9bcaadfbe15.png)

And... wtf is this mix of APIs? :D

ECASPI is a deprecated piece of shit based on raw GPU calls. The GUI is an double buffered shit based on double buffering library. Don't even try to use them together, meow
