### ISSUE TITLE
Вход в систему не работает

### ISSUE THREAD

**Issue by fgRuslan** [IgorTimofeev/MineOS#128]
Это происходит из-за того, что SHA-256 выдаёт разные хэши на разных архитектурах. Наверное это всё происходит потому, что в opencomputers на архитектуре 5.3 нет родной библиотеки bit32, когда на 5.2 есть. Скорее всего, эти библиотеки на разных архитектурах разные и хэши они вычисляют по разному.
Вот хэши строки "suka" на разных архитектурах:
Lua 5.2

![default](https://user-images.githubusercontent.com/11362683/44626227-7f539880-a921-11e8-9ff9-41d50183bb59.png)

Lua 5.3

![default](https://user-images.githubusercontent.com/11362683/44626234-a14d1b00-a921-11e8-9f40-4bf49d31c254.png)

**Comment by IgorTimofeev** [comment]
Угу, известный баг. Как фиксить - понятия не имею, т.к. либу спиздил, и как она устроена - в душе не ебу, самому дико лень было писать. Могу в принципе склепать простенький хеш-метод со слабой криптостойкостью, если прям АЩЕ ОЧ НАДО, но ваще ща занят переписыванием оськи с нуля, чтоб это была ваще чисто оська, а не опеносовско-зависимая параша

**Comment by fgRuslan** [comment]
Или можно убрать выбор архитеуктуры процессора в самой оси) Но это уже будет мегакостыль
