### ISSUE TITLE
FTP....

### ISSUE THREAD

**Issue by Fronun** [IgorTimofeev/MineOS#129]
дело том, что я не пользуюсь гитхабом для загрузки моих приложений, вообщем не важно, мне бывает надо использовать FTP, и твоя "ось", выдает ошибку и не могу подключаться скриншоты есть
![screenshot_2](https://user-images.githubusercontent.com/32768348/44948784-742acc00-ae3d-11e8-894e-0c912f4e13ee.png)
![screenshot_1](https://user-images.githubusercontent.com/32768348/44948785-742acc00-ae3d-11e8-8e6b-f1a88c43f636.png)

**Comment by IgorTimofeev** [comment]
И че? Каким образом я могу хелпануть с проблемой, если никакой инфы, кроме "авторизация не удалась", нет? Я че, ебу, почему она не удалась? Траблов может быть масса: либо удаленный сервак фильтрует сокет-соединения и не пропускает опенкомповские, либо сервер (игровой) не позволяет открывать внешние сокеты, либо позволяет, но не отсылает сообщения с таймаутом, либо не успевает прочесть, либо еще какое-нибудь говнище. Мяу?

**Comment by Fronun** [comment]
это оказывается сервак удалённый (игровой), попробовал на другом клиенте опен компьютерс. спасибо ввсе равно.

**Comment by IgorTimofeev** [comment]
:c
