### ISSUE TITLE
importing images

### ISSUE THREAD

**Issue by chevysixgaming** [IgorTimofeev/MineOS#130]
i like the wallpapers and what not, but i want to know how to import pictures into it, and which format do I use so that they are recognized

**Comment by IgorTimofeev** [comment]
The format is OCIF, you can convert any real image using this: https://github.com/IgorTimofeev/OCIFImageConverter

As an alternative you can use built-in "Picture Edit" application to create/edit images directly is OS

**Comment by chevysixgaming** [comment]
thanks a lot man this is definitely a huge upgrade, i'm using mineOS on opencomputers, i ended up making a tier 3 server unit so i could put 4 RAM sticks in and more hard drives its really awesome now i know how to add in my own wallpapers and what not thanks a lol

**Comment by IgorTimofeev** [comment]
Glad you're satisfied. If you enjoy pictures then you can try this:
https://github.com/IgorTimofeev/MineOS/blob/master/Applications/MultiScreen/MultiScreen.lua

It allows to do draw really big images:

![ws2idjelcnq](https://user-images.githubusercontent.com/11760002/45168803-d9e3d300-b204-11e8-98eb-2f2da9e80e23.jpg)

**Comment by koriuju** [comment]
When i try to download a .pic file to mineos that i have converted using that converter it says "Failed to load OCIF image: binary signature is not valid. How do i solve this?

**Comment by IgorTimofeev** [comment]
Seems like bad file hosting. You need "direct url" to .pic file without anything else to download it properly

**Comment by koriuju** [comment]
Is hosting through github ok? I made a repository specifically for the .pic file and it still gave the same error.

**Comment by IgorTimofeev** [comment]
Yeah, ok, I personally use only GitHub. Are you sure you do everything right? How picture is being created? Via native "Picture edit" program or what? Maybe you are trying to use Multiscreen Converter with "OCIF5 (Multiscreen)" conversion option?

![image](https://user-images.githubusercontent.com/11760002/73139177-630adc80-407c-11ea-8f1c-08657726c0a1.png)

 MineOS doesn't work with this encoding method - it's only for "Multiscreen" application from App Market. Only OCIF 6 (Optimized) can be opened

**Comment by EpikDisko** [comment]
Just in case anyone else who also have the same problem as me, but now solved(I think), as said above, posting on github, you are required to get its "direct url", but it requires you to use inspect element on the download button of the file, so say, i want the pic file from "https://github.com/EpikDisko/drip/_blob_/main/yharimdrip.pic", I gotta replace the "blob" with "raw" , now its "https://github.com/EpikDisko/drip/_raw_/main/yharimdrip.pic". Let me know if that solves the problem. Do note I don't know how to code.

**Comment by merkush012** [comment]
> Just in case anyone else who also have the same problem as me, but now solved(I think), as said above, posting on github, you are required to get its "direct url", but it requires you to use inspect element on the download button of the file, so say, i want the pic file from "https://github.com/EpikDisko/drip/_blob_/main/yharimdrip.pic", I gotta replace the "blob" with "raw" , now its "https://github.com/EpikDisko/drip/_raw_/main/yharimdrip.pic". Let me know if that solves the problem. Do note I don't know how to code.

How do you download a picture from windows desktop into mineos?

**Comment by merkush012** [comment]
How do i download a picture into mineos? I have a pic hosted on github but when i try to upload it into mineos i get an error on line 96 main.lua in downloader app.

**Comment by IgorTimofeev** [comment]
@merkush012  What is downloader app? Third-party software from AppMarket? The easiest way is to go to desktop -> right click -> create -> file by URL, it's a built-in feature

**Comment by polrbare** [comment]
can someone help, i hosted the .pic on github and tried to import from url however i got an error message in mineos. said error message only said the .pic link from github. any help or alternatives would be greatly appreciated!

**Comment by CoolCat467** [comment]
Don't use normal github link, it'll try to be a webpage. What you want is the "raw file" version. For example, "EpicDisko" 's file would be accessible here from MineOS: https://raw.githubusercontent.com/EpikDisko/drip/main/yharimdrip.pic

**Comment by CoolCat467** [comment]
@polrbare For you in particular and your repository "imagestorage", you would use these links:
https://raw.githubusercontent.com/polrbare/imagestorage/main/carrack.pic
https://raw.githubusercontent.com/polrbare/imagestorage/main/jurassic.pic
https://raw.githubusercontent.com/polrbare/imagestorage/main/mudman.pic
https://raw.githubusercontent.com/polrbare/imagestorage/main/wallpaper.pic

**Comment by CoolCat467** [comment]
```py
def get_address(user:str, repo:str, branch:str, path:str) -> str:
    "Get raw github user content url of a specific file."
    return f'https://raw.githubusercontent.com/{user}/{repo}/{branch}/{path}'
```
