### ISSUE TITLE
Новые идеи для оперционнки.

### ISSUE THREAD

**Issue by Fronun** [IgorTimofeev/MineOS#131]
1. почему бы не сделать файл подкачи, как в нормальных осях? если конечно ты пробовал (но конечно может скорость упасть, будет полезно для компьютеров 3 уровня где оперативная память ограничена.)
2. будет конечно по поводу интерфейса, почему бы не сделать тёмную тему? когда у тебя тёмные обои и хочется немного сделать атмосферно.
3. по поводу документаций библеотеки GUI: конечно, я все понимаю что есть и дргуие нации есть другие языки, и поэтому ты сделал документацию на глобалном языке, почему бы не сделать ещё документацию на своем родном языке? (но если конечно захочешь, я тут ничего не требую, тут конечно потребуется время на перевод)
4. если дело пошло почему бы не сделать Dock более похожим на реальный MacOS 10.13? Темболле не думаю что эппл не будет лазить по GitHub и темболле на Lua, если тебе нравиться более ранная версия, то я конечно не против это твой вкус, но почему бы не сделать хотя бы варианты, чтобы пользователь мог выбирать dock как ему захочется.

**Comment by IgorTimofeev** [comment]
1. Во-первых, я в душе не ебу, как подобное реализовать средствами мода, т.к. прямого доступа к стеку памяти он не предоставляет. Во-вторых, скорость работы ЖД настолько низка, что приходится писать библиотеки с обратным принципом: для ускорения ЖД путем буферизации через оперативку, мяу
2. Этот функционал же давно имеется: бери и меняй цвета по своему усмотрению. Ну, и большинство приложений никак не связаны с самой осью и обладают индивидуальными цветовыми шаблонами.
3. Потому что я еще не настолько обдолбался, чтобы параллельно документировать подобное кол-во инфы. Также потому что основная аудитория оськи, судя по логам маркета, нерусь - это Штаты, Китай и, как ни парадоксально, Австралия. Да и на людей, не способных прочесть инфу на столь примитивном уровне инглиша, мне рили насрать, т.к. примеров кода там вагон с тележкой. Ну, и также потому что проект некоммерческий, профита я с него почти не имею, поэтому и выкладываюсь по тем пунктам, которые считаю приоритетными. Старая версия доки на руссише, если надо, вот: https://github.com/IgorTimofeev/MineOS/blob/00f19b2c460bc82a4ae5fc593c367f0fbfd5ccdd/Documentation/GUI.md
4. Потому что мне не нравится этот ссаный недо-док в новых версиях макоси. Как вы меня заебали уже с этим доком и стилизацией интерфейса, сил уже нет! Ну рили че вы там собрались кастомизировать на нескольких пикселях? Цвет менюхи сверху? Цвет дока? Форму дока? Цвет... фона в проводнике? Пиздец обширно хд

**Comment by Fronun** [comment]
Игорь, где то я согласен по поводу интерфейса, я согласен раньше макось мне нравилась а сейчас при виде его блеваюсь.
