### ISSUE TITLE
App market не работает.

### ISSUE THREAD

**Issue by Fronun** [IgorTimofeev/MineOS#132]
Кажись ты накосячил.... (Я обновил GUI, у меня апп маркет перестал работать, даже переустановил опенось)
![default](https://user-images.githubusercontent.com/32768348/45220680-5a1f3c80-b2c8-11e8-9e8e-88aab963a0a6.png)

**Comment by IgorTimofeev** [comment]
Угу, ща фиксанется само. Не подтянулись зависимости
