### ISSUE TITLE
Поздравление

### ISSUE THREAD

**Issue by Fronun** [IgorTimofeev/MineOS#133]
Сегодня, день программиста! Я тебя поздравляю, я считаю что программист, это состояние души, не знаю считаешь себя программистом или нет, я себя не считаю а просто, считаю себя любителем.

**Comment by IgorTimofeev** [comment]
хуя какие нежности! нет, не считаю, однако внимание всегда приятно, так что держи тяночек:

![xuw7qter-wa](https://user-images.githubusercontent.com/11760002/45488508-46f9ea00-b76a-11e8-89df-bd25f21d91ce.jpg)


![iazd4hq9be8](https://user-images.githubusercontent.com/11760002/45488492-3d708200-b76a-11e8-8fdc-7fa90092eca9.jpg)

**Comment by fgRuslan** [comment]
У второй тянки вансы палёные)

**Comment by IgorTimofeev** [comment]
:((
