### ISSUE TITLE
Титл

### ISSUE THREAD

**Issue by BrightYC** [IgorTimofeev/MineOS#139]
Есть такая проблема, что при выходе в шелл - жёсткий диск начинает жужжать, и это подтверждают индикатор жёсткого диска. Без понятия что это такое, решается ребутом. Ставил на абсолютно чистом компьютере, так что какие-то конфликты исключены.
Вторая проблема - иногда при установке библиотека scale.lua не докачивается, без понятия почему, из-за этого приходится ставить её вручную. 
З.Ы Видео с жужжащим диском https://youtu.be/ZppVwpF99Nk

**Comment by IgorTimofeev** [comment]
Вот это рили странная штука, да, тоже заметил недавно. Причем если удалить /autorun.lua, запустить майнось и вернуться в опенось - то все в порядке. Видимо, где-то я накосячил с /init.lua, не позволяя опеноси прогрузиться как следует. Будем фиксить, че. А скейл ща докину в сырцы, видимо, забыл

(пасебо)

**Comment by BrightYC** [comment]
А где котики?:с

**Comment by IgorTimofeev** [comment]
Мяу, ну вот, держи одного:

![](https://pp.userapi.com/c852020/v852020711/33ea/U5Azh4umAto.jpg)

Или даже не одного:

![](https://sun1-16.userapi.com/c543108/v543108362/3dae2/GhA5uDRZc28.jpg)

А проблему обнаружил: оказывается, при установке так называемого package unloading в настройках некоторые опеносовские модули выгружаются, а затем пытаются подгрузиться каждый терминальный ивент. Выставлю по дефолту эту фичу на "выкл", мяу.

Это самое, а в каких случаях со скейлом были траблы? После установки оси чет не открывалось?

**Comment by BrightYC** [comment]
ОО, котики. А траблы были при открытии приложений с настройками - была ошибка мол "scale" это нил, вот и крашило. Вручную докачал - всё заработало

**Comment by BrightYC** [comment]
Вот пикча, хоть это ничего и не даст, но возможно ты меня поймешь, а то у меня с высказыванием мыслей проблемы большие. [https://i.imgur.com/mLEKABh.png](url)

**Comment by IgorTimofeev** [comment]
Угу, угу, ты все корректно понял. На всякий случай переставил ось - либа имелась. Вполне возможно, кстати, ты "удачно" попал в момент, когда приложуха настроек была опубликована, однако еще не имела в зависимостях скейл либу... оч сложна!

Но хоть с ЖД трабл решили, пасебо
