### ISSUE TITLE
Титл намба фри

### ISSUE THREAD

**Issue by BrightYC** [IgorTimofeev/MineOS#141]
Ток не бей, я не специально. Вылетает при "Создать приложение MineOS".

И еще, зачем нужна кнопка "Отправить отчёт" если она ничего не делает?)) (Проверил, светодиод интернет-платы не работает)
![default](https://user-images.githubusercontent.com/28766913/45776521-c94b4800-bc5b-11e8-8adc-7c20dbbb5187.PNG)

**Comment by IgorTimofeev** [comment]
Та йопта! Видимо, подтерись некоторые поля при обновлении локализаций - отсутствует "Путь к иконке". Пофиксил

А отчеты оно отправляет суды, о существовании светодиода вообще не слыхивал: https://api.mcmodder.ru/ECS/reports.txt

**Comment by BrightYC** [comment]
Блин, я думал светодиод у сервера показывает и интернет-запросы, но только от модема к сожалению(
