### ISSUE TITLE
Памахите 

### ISSUE THREAD

**Issue by BrightYC** [IgorTimofeev/MineOS#142]
Привет, тут проблемка нарисовалась. При попытке require'нуть библиотеку зыреад вот что происходит. Это абсолютно чистый компьютер, на который была установлена майнось. Тем не менее, на другому компьютере без майноси всё отлично работает, они идентичны друг другу. Честно, - для меня загадка что это, и прошу у тебя помощи, потому что это происходит только после установки твой оськи
![default](https://user-images.githubusercontent.com/28766913/45921443-55f54080-bebe-11e8-81d7-fe6892badb4d.PNG)

**Comment by IgorTimofeev** [comment]
Решение загадки в либе event, которая у майноси своя. Тут с этим уже сталкивались: https://github.com/IgorTimofeev/MineOS/issues/85
