### ISSUE TITLE
удаленные приложение с гитхаба или пастебина.

### ISSUE THREAD

**Issue by Fronun** [IgorTimofeev/MineOS#143]
удоли, ошибку выдает, лишний мусор.
![screenshot_1](https://user-images.githubusercontent.com/32768348/46012782-bc0edd00-c0e3-11e8-83ec-07fbb8c156ab.png)

**Comment by IgorTimofeev** [comment]
Мяу, это, видимо, уже мой косяк: символьные баги описаний, ща чекну. НО АВТОР ВСЕ РАВНО СВОЛОТА, ЧО ОН ГОВНИЩЕ КИАДЕТ КАКОЕ-ТО
