### ISSUE TITLE
MineIDE...

### ISSUE THREAD

**Issue by Fronun** [IgorTimofeev/MineOS#144]
однажды я переместил окно MineIDE, и я заметил что код вылазивает из окна, из правой стороны в левой (концы кода)
![screenshot_1](https://user-images.githubusercontent.com/32768348/47169358-b3917700-d31c-11e8-8f43-f60bbcb3c82c.png)

**Comment by IgorTimofeev** [comment]
УУУУ, ОЛДСКУЛЬНЫЙ БАГ, ПОФИКСИМ КАК-НИТЬ, ПАСЕБО

**Comment by hobbytes** [comment]
> УУУУ, ОЛДСКУЛЬНЫЙ БАГ, ПОФИКСИМ КАК-НИТЬ, ПАСЕБО

Это фича! Можно кодить с двух сторон

**Comment by kcinnaJlol** [comment]
well windows can still leave the screen so you need to simulate a bigger screen to fix that issue.

**Comment by Fronun** [comment]
ну так когда пофиксишь?

**Comment by IgorTimofeev** [comment]
@Fronun Мб вообще никогда, мне лень. Че за стремная назойливость?(

**Comment by IgorTimofeev** [comment]
Fixed
