### ISSUE TITLE
Снова сервер упал?

### ISSUE THREAD

**Issue by Fronun** [IgorTimofeev/MineOS#146]
Твой апп маркет не работает.
![screenshot_4](https://user-images.githubusercontent.com/32768348/48623134-aa063800-e9ca-11e8-847d-97280d8ccfb2.png)

**Comment by IgorTimofeev** [comment]
Угу, инета пока нет на хосте, профилактика. Поднимется как-нибудь

**Comment by Fronun** [comment]
Если не секрет, то что у тебя делается в профилактике?)

**Comment by IgorTimofeev** [comment]
@Fronun Это ты у провайдера лучше спроси, я не знать. Вон, вчера решили впервые за десяток с лишним лет сменить мне внешний IP'шник, а заодно и с тарифами пошаманить. Ничего интересного

**Comment by Fronun** [comment]
ааа... Я не понял, я начало подумал что ты делаешь профилатику на свой хост (малинку), и да какой у тебя провайдер? У меня Ростелеком и он сука мне обрезает скорость до 60 мб/с в итоге мой роутер обрезывает мне скорость а вот другим устройствам норм.

**Comment by IgorTimofeev** [comment]
@Fronun Да хз, какой-то, доставшийся по наследству от прадеда. Не интересовался, мяу
