### ISSUE TITLE
Игорь, когда новые видео?

### ISSUE THREAD

**Issue by BrightYC** [IgorTimofeev/MineOS#147]
Это конечно не баг, но тем не менее, сделай какой-то таймер, который возвращает разрешение на старое, если не принять его. Потому что вот. Случайно поставил длину в 1 символ, вот что случилось.(Да, добраться до папки с конфигом труда не доставляет, но если у кого-то минеось в автозагрузке и никак не добраться до папки из-за разрешения?)
Надеюсь ты понял, а то у меня проблемы с донесением мыслей.
![1746de425dcc231ea18be936180b5c03](https://user-images.githubusercontent.com/28766913/48656986-f4280180-ea3c-11e8-8b6d-feee957a67fc.png)
И когда новые видео, а то уже 8 месяцев новые видео не выпускал!!1!1

**Comment by IgorTimofeev** [comment]
@BrightYC Ебать, всегда было интересно, нахуя эти таймеры в игрушках вообще сдались. Видимо, для чего-то схожего. Лан, ченить придумаем, пасебо

**Comment by IgorTimofeev** [comment]
@BrightYC :((9

**Comment by Fronun** [comment]
Игорь, с идеей могу подкинуть а вот если тебе лень снимать, то тебе не лень озвучивать?)

**Comment by IgorTimofeev** [comment]
@BrightYC Я, мля, обладаю IQ чуть больше 20 и уж идею сгенерить как-нибудь смогу при наличии желания без посторонней помощи. Мне все лень, ацтаньти

**Comment by IgorTimofeev** [comment]
Добавил лимит под 30 пикселей в минималочке. Вроде бы хватает для ресета, если накосячил
