### ISSUE TITLE
ЕБАЛО БЛЯТЬ ИСПРАВЬ!!!

### ISSUE THREAD

**Issue by Fronun** [IgorTimofeev/MineOS#148]
Вообщем, решил зайти на свой (не фейковый акк), ввел все свои данные для логина, и мне кидает ошибку я так думаю что то с ебалом или префиксом. 
![screenshot_6](https://user-images.githubusercontent.com/32768348/48661354-5bbc6c00-ea92-11e8-91e7-cd3023a10623.png)

**Comment by IgorTimofeev** [comment]
@Fronun  Не знать, че это. Как-то связано с получением юзера из беседы на конкретном аккаунте, эт надо знать, че за беседа, че за акк и т.п.

**Comment by Fronun** [comment]
а можно мне как то отрубить ебло?

**Comment by IgorTimofeev** [comment]
@Fronun та йобаный рот, ты похромист или кто? Сделай в исходнике что-то типа **messagePreview = eblo and (eblo.firstName... и все далее) or "WTF EBLO MISSING"**, че за детсад? Обычное условие же

Такие вещи тока опытным путем фиксятся. Че за конфа-то?

**Comment by IgorTimofeev** [comment]
САМ ТЫ CLOSED, ГОУ ИНФУ О КОНФЕ

**Comment by IgorTimofeev** [comment]
Стопудова в конфе есть либо какой-то чат-бот, либо какой-нибудь паблик или аналог сбербанка. Или мяу.

**Comment by Fronun** [comment]
ебучие боты, спасибо)

**Comment by IgorTimofeev** [comment]
ТАК ЧЕ ЗА БОТ, СКАЖИ МНЕ, ЕБАНЫЙ РОТ, КАК Я ТЕ ФИКСИТЬ ЭТО БУДУ, А А А А А А АА А У ФАФ УА

**Comment by Fronun** [comment]
ща "Код Дурова", "типичный программист"

**Comment by BrightYC** [comment]
ecs кагда двухфактарная аутентификация!1!1(Нет, реально, когда?)

**Comment by IgorTimofeev** [comment]
@Fronun Пасебо, потестим
@BrightYC Никогда, как я те капчу вхуячу в опенкомпы? Не, ну могу url текстом на нее давать, но это ж бред, она огромная хд

**Comment by BrightYC** [comment]
@IgorTimofeev Обидно. И чо мне теперь делать, выключать её что-ли?

**Comment by IteratorW** [comment]
@BrightYC костыли еще никогда не подводили)

**Comment by IgorTimofeev** [comment]
@BrightYC Я чо, ебу штоле. Ну как я те высру возможность отображения капч в нихуевом разрешении (около 360х200)? Либа для парсинга jpeg имеется, но пикча качаться ж полгода будет, плюс сжимать ее надо для отображения на монике

**Comment by IgorTimofeev** [comment]
@Fronun Насчет кодов дурова и девнуллов - ты типа в личку паблику писал?

**Comment by Fronun** [comment]
Не писал.

**Comment by IgorTimofeev** [comment]
@Fronun Че? А откуда у тебя тогды беседа с девнуллом и кодом дурова? Они те штоль писали или че?

**Comment by Fronun** [comment]
Расылку включил

**Comment by Fronun** [comment]
![screenshot_20181118-140141](https://user-images.githubusercontent.com/32768348/48670506-b90bf800-eb3a-11e8-816d-08fbb1ff8c78.jpg)
Cyka, blyat

**Comment by IgorTimofeev** [comment]
ЕБАААААААТЬ, ТО ЕСТЬ ВК ИЗОБРЕТАЮТ НОВУЮ ФИЧУ, А Я, МЛЯ, ДОЛЖЕН СВОЙ КОД ПРАВИТЬ, ОХУЕННО))0))0

**Comment by IgorTimofeev** [comment]
Мяу, это у меня и так разрешено уже с год, а никакой рассылки нет, как нет надежды на сытный обед. Смирюсь :(

**Comment by IgorTimofeev** [comment]
@Fronun Рили хз, че там у тебя за лс с пабликами. Усе норм отображаеццо

![2018-11-18 18 23 24](https://user-images.githubusercontent.com/11760002/48675181-f1c1c680-eb66-11e8-95bf-2cf8cc84ad1f.png)

**Comment by Fronun** [comment]
Игорь, у меня появилась идея что добавить в МайнОСИ.
1. сделать чтобы юзер, мог открыть папку жёсткого диска, да бы не открывать файдер и искать жд который нужен 
![57028050](https://user-images.githubusercontent.com/32768348/48708093-61958700-ec23-11e8-833c-b2b13a7e6998.png)
2. так как не давно вышла новая версия опенкомпьютерса, сделай извлечение дискет через контекст меню. (Относится к идей номер 1)

**Comment by IgorTimofeev** [comment]
@Fronun Мяу? А чем это будет отличаться от обычного ярлыка? Ну, которого пкм - создать ярлык.

А второе надо бы, дыа, спсоеба

**Comment by Fronun** [comment]
ну так это и есть ярлык, допустим мне было бы удобно, потому что у меня все прогги которые пишу находятся в райде, а заходить файндер и искать райд.

**Comment by IgorTimofeev** [comment]
Так это, а че не создашь ярлык на диск? Ну, заходишь такой в mnt, создаешь ярлык. Или ты че, хочешь, чтоб система тебе автоматом надрачивала иконки эти в зависимости от имеющихся дисков? Оч сложна кодить(

**Comment by Fronun** [comment]
лол, а я не заметил, что можно делать ярлыки папок в майнос.

**Comment by Fronun** [comment]
кстати игорь, а живые иконки работают в майнос? или ты убрал эту фишку?

**Comment by IgorTimofeev** [comment]
@Fronun Работают, но я не скажу, как их делать))0

Вообще надо бы впилить подобную фичу в маркет, но чет пизда лень, никак не возьмусь

**Comment by IgorTimofeev** [comment]
Надеюсь, "попробую сделать" подразумевает создание живой иконки, а не правку оси

**Comment by Fronun** [comment]
канеш живой иконки, а не оси а то мне лень лазить в не знакомый код.

**Comment by Fronun** [comment]
![screenshot_1](https://user-images.githubusercontent.com/32768348/48760749-ac1d0f00-ecc8-11e8-8ed1-530a4d455965.png)
я сделаль)

**Comment by Fronun** [comment]
чёт issue пошёл не туда.
