### ISSUE TITLE
AppMarket не работает: ошибка 403

### ISSUE THREAD

**Issue by down555** [IgorTimofeev/MineOS#151]
Не робит магазин, все вкладки выдают ошибку типа такой:
![2018-12-01_20 10 17](https://user-images.githubusercontent.com/45518431/49330833-47559480-f5a5-11e8-86c1-e48cd5ba656b.png)

**Comment by IgorTimofeev** [comment]
Мяу, значит, твой провайдер внес в блеклист IP cloudflare. Прокси в помощь
