### ISSUE TITLE
Pastebin Error

### ISSUE THREAD

**Issue by IXIInternational** [IgorTimofeev/MineOS#153]
When I try “pastebin run 0nm5blju“ it gives me an error.

**Comment by IgorTimofeev** [comment]
Meow? Not **0nm5b "l" ju**, there's no extra **"l"**. Just **0nm5b1ju**. If error comes from another reason - attach screenshot or some info. How the fuck can I understand what's wrong? :p

**Comment by IXIInternational** [comment]
Was too dumb to read :D
