### ISSUE TITLE
Ошибка обновления приложения

### ISSUE THREAD

**Issue by BTVoidX** [IgorTimofeev/MineOS#154]
Пытаюсь обновить AppMarket (Через AppMarket, как раз), а происходит такое
![default](https://user-images.githubusercontent.com/37330718/50443170-87e1cd00-091b-11e9-9a5b-1525d630a269.png)

**Comment by IgorTimofeev** [comment]
Фига ты в минутный интервал ошибочки попал. Снупер, йопта. Ща усе работает, пасебо
