### ISSUE TITLE
Failed to start autorun.

### ISSUE THREAD

**Issue by 0xF6** [IgorTimofeev/MineOS#156]
![image](https://user-images.githubusercontent.com/13326808/50489680-0886f300-0a1a-11e9-93fa-27c85536a1a6.png)

Похоже в ласт обновлении /lib/MineOSInterface что-то поломалось)))0)

**Comment by 0xF6** [comment]
![image](https://user-images.githubusercontent.com/13326808/50490574-d75cf180-0a1e-11e9-8fd0-b1a5680cff82.png)

**Comment by IgorTimofeev** [comment]
Ну и хуй с ней))0
