### ISSUE TITLE
Cannot delete folder from floppy disk

### ISSUE THREAD

**Issue by WattanaGaming** [IgorTimofeev/MineOS#157]

**Comment by WattanaGaming** [comment]
I think I have an Idea.
You have two delete optons
1. Send to the rubbish bin
2. Permanent delete(similiar to rm -r)

**Comment by IgorTimofeev** [comment]
Meow? I have only one option, the first one. After moving somthing to Trash you can erase it with "permanent delete" using filesystem.remove()

And, as I said, filesystem.rename() is broken for now. Nothing I can help

**Comment by IgorTimofeev** [comment]
Seems to be fixed in MineOS Standalone
