### ISSUE TITLE
Failed start drawOnScreen at window container

### ISSUE THREAD

**Issue by 0xF6** [IgorTimofeev/MineOS#158]
Опять ты все сломал, куча софта не стартует теперь.
ReactorControll, InfoPanel, OpenSecurity и тд

![image](https://user-images.githubusercontent.com/13326808/50731660-83b77a00-117b-11e9-95cb-0b878180d353.png)

**Comment by 0xF6** [comment]
![image](https://user-images.githubusercontent.com/13326808/50731722-cded2b00-117c-11e9-892c-fe8a4a79d78a.png)

**Comment by 0xF6** [comment]
Кек
*если чо, mainContainer юзается еще и в твоем софте*

**Comment by 0xF6** [comment]
И вообще, ты умничка
С новыми апдейтами система стала почти летать.
Вот еще бы клиент телеграмма бы запилил, цены бы тебе не было :3

**Comment by IgorTimofeev** [comment]
@0xF6 Мяу, половину из них не я публикую: просто аккаунт общий для маркета для удобства, ИнфоПанель ту же один уебан дофига самостоятельный писал. А телеграммо-софтину было бы занятно, но, увы, я им не пользуюсь хд

**Comment by IgorTimofeev** [comment]
Сломанный софт успешно починен его выпиливанием с маркета. Все как мы любим))0

**Comment by 0xF6** [comment]
))00
