### ISSUE TITLE
Failed to install MineOS standalone.

### ISSUE THREAD

**Issue by fadda** [IgorTimofeev/MineOS#159]
![image](https://user-images.githubusercontent.com/16801119/51430217-fcf9a700-1c28-11e9-9bd3-830e3c7ea188.png)

P.S.: Clean install from OpenOS floppy on T3 server

**Comment by IgorTimofeev** [comment]
happens only after installing over OpenOS 1.6, trying to figure out how to fix, thx

**Comment by IgorTimofeev** [comment]
Seems to be fixed. Fuck openos!111

**Comment by fadda** [comment]
Not quite..

![image](https://user-images.githubusercontent.com/16801119/51440264-65eb2880-1cd6-11e9-96f9-d2e47486eb3f.png)

**Comment by IgorTimofeev** [comment]
How?((99 HOW, HOW, HOW

WHY I'M ON OC 1.6/1.7 AND DO NOT HAVE SUCH PROBLEMS

**Comment by IgorTimofeev** [comment]
![2019-01-20 17 42 07](https://user-images.githubusercontent.com/11760002/51440684-ba90a280-1cda-11e9-96c2-471c8d877ad8.png)

**Comment by fadda** [comment]
MC 1.7.10
OC 1.7.0.1085
OpenOS 1.6.8

Tried a clean install several times (removed everything from 'opencomputers' folder in world data on the server).

Every time the PC is powered on it is loading MineOS installer which ends up with this error (no matter what HDD or EEPROM is inserted.) Only deleting all files in that folder allows installing OpenOS again.

Booting up the PC without an internet card results in the following error: 

![image](https://user-images.githubusercontent.com/16801119/51441033-6f788e80-1cde-11e9-9ef3-5240ea6d98f5.png)

Hope it helps. Would be glad to provide more info.

**Comment by IgorTimofeev** [comment]
с:
