### ISSUE TITLE
Ошибка 404 на странице при подтверждении регистрации

### ISSUE THREAD

**Issue by vecktor911** [IgorTimofeev/MineOS#160]
Хотел зарегаться в маркете, пришло уведомление на почту со ссылкой на подтверждение и она не работает. Шо делать? Это важно или без разницы?

upd: Работает.
![screenshot_1](https://user-images.githubusercontent.com/15859698/51482697-33a9fb80-1da8-11e9-96bf-5aead1fb16aa.png)

**Comment by IgorTimofeev** [comment]
@vecktor911 Спасибо, пофикшено.
