### ISSUE TITLE
Can someone help me?

### ISSUE THREAD

**Issue by Mike123124** [IgorTimofeev/MineOS#162]
I recently downloaded the mineos to my computer but i wanted to download the shooting app but it doesn't show up on the app store?? does anyone know why?

**Comment by IgorTimofeev** [comment]
Meow, it was removed a half year ago cause of deprecated (and also removed) API usage. If you really need it, I can re-publish it in some days

**Comment by Mike123124** [comment]
If you could that would be amazing, Thank you so much!!!

**Comment by IgorTimofeev** [comment]
Added simplified version for now. Maybe someday will adjust it with score table
