### ISSUE TITLE
When did MineOS became standalone and the installer start to look like Ubuntu installer?

### ISSUE THREAD

**Issue by WattanaGaming** [IgorTimofeev/MineOS#163]
When did MineOS became standalone and how?

And to be honest, how does the installer's design get the design from Ubuntu installer?
There is even user account setup

**Comment by IgorTimofeev** [comment]
Meow, long time ago in a galaxy far, far away

And meow again, this is just a coincidence. I only saw Ubuntu by a screen sharing from friend via Skype - that was only once much longer time ago. Maybe in the same galaxy
