### ISSUE TITLE
Function to emulate a computer?

### ISSUE THREAD

**Issue by WattanaGaming** [IgorTimofeev/MineOS#164]
I've been developing my own kernel/OS for a while now, but it's just too annoying to leave the floppy directory and put it in another computer just to test it. Is it possible to emulate a computer so that OS development can get easier?

**Comment by IgorTimofeev** [comment]
Yep, you can do it via load() environment. But only if your OS doesn't substitute native OpenComputers functions/tables like OpenOS does (in /lib/event.lua, for example):

```lua
-- Create sandbox environment table that will be used as global variables source for your OS
local sandbox = {}
for key, value in pairs(_G) do
  sandbox[key] = value
end
sandbox._G = sandbox

-- Run your code in sandbox. It won't change your currently running OS global environment
load(<your lua code string goes here>, "=MyOS.lua", "t", sandbox)
```
