### ISSUE TITLE
r/TechNope maybe?

### ISSUE THREAD

**Issue by WattanaGaming** [IgorTimofeev/MineOS#165]
![screenshot from 2019-02-09 06-26-52](https://user-images.githubusercontent.com/25323231/52512162-037eab80-2c36-11e9-98da-5ca24bb73c53.png)

**Comment by IgorTimofeev** [comment]
Yes, yes, the same issue here: #144 

Not critical to fix right now. But still need to

**Comment by IgorTimofeev** [comment]
Cyka blyad fixed thx
