### ISSUE TITLE
App Store

### ISSUE THREAD

**Issue by SaltySquid23** [IgorTimofeev/MineOS#166]
It Isn't working because you need to renew the lease please do it this looks amazing!!

**Comment by IgorTimofeev** [comment]
Meow? What exactly isn't working?

![2019-02-13 12 14 55](https://user-images.githubusercontent.com/11760002/52700471-00aeee00-2f89-11e9-8092-053a1e7d009f.png)

Maybe you're still on an old OS version? App Market is now only for MineOS Standalone, you just need to reinstall OS via pastebin. Or what?

**Comment by veso266** [comment]
Where did Radio app go? I updated it once: https://github.com/veso266/MineOS/blob/master/Applications/Radio/Radio.lua

But now 1 year has past and b4 I install Minecraft again i ask myself: would it still work :)
BTW do you have Backend code for App store?

**Comment by IgorTimofeev** [comment]
Meow, some apps are being automatically removed when "too much negative reviews" ratio is achieved. I'll check your

Backend app store code is hidden - i'm too lazy to publish it.
