### ISSUE TITLE
Как выложить приложение?

### ISSUE THREAD

**Issue by getkirill** [IgorTimofeev/MineOS#167]
Плз помоги как выложить приложение в твой магаз.
Заранее спасибо.

**Comment by IgorTimofeev** [comment]
Мяу? И так же все для полнейших дебилов сделал, что ж за сложности?(99

Регаешься в маркете -> опубликовать ПО -> вставляешь ссылки на иконку и луа-файл -> profit

**Comment by getkirill** [comment]
Пасиб
