### ISSUE TITLE
Создайте приложение наподобие Visual Studio

### ISSUE THREAD

**Issue by getkirill** [IgorTimofeev/MineOS#168]
Здравствуйте еще раз. Предлогаю идею - сделать типа Visual Studio, чтобы создавать приложения быстрее. Еще раз спасибо (Еще?)

**Comment by IgorTimofeev** [comment]
Если речь о визуальном дизайнере интерфейса с редактированием всех свойств объектов, то мне лень. Слишком большие времязатраты без профита для некоммерческого проекта.

А если речь о редакторе кода - то есть майнкодыч

**Comment by getkirill** [comment]
я тогда сам попробую

**Comment by getkirill** [comment]
сделать

**Comment by getkirill** [comment]
Спасибо.
