### ISSUE TITLE
Can't launch any program

### ISSUE THREAD

**Issue by netblink-cobreen** [IgorTimofeev/MineOS#172]
runned this command and installed mineOS
pastebin run 0nm5b1ju
When tried to run AppStore got this error:
![2019-03-09_13 55 06](https://user-images.githubusercontent.com/45759596/54071880-33d85a80-4273-11e9-8e0f-99d51daae5de.png)

**Comment by IgorTimofeev** [comment]
@netblink-cobreen You're on **VERY**, very old version of OpenComputers mod: so critical function debug.getInfo doesn't even exists. Please update to 1.6 or higher

**Comment by netblink-cobreen** [comment]
@IgorTimofeev Can you provide latest OpenComputers for 1.7.10?

**Comment by IgorTimofeev** [comment]
Meow? Google is blocked or what?

https://minecraft.curseforge.com/projects/opencomputers/files

**Comment by ProjectHSI** [comment]
I think it's time to close this issue now. It's already fixed with the new update.

**Comment by IgorTimofeev** [comment]
I'm not really bothered by open Issues, but ok, if u insist
