### ISSUE TITLE
Error on Open "Reactor Ctrl"

### ISSUE THREAD

**Issue by LePandaFou77** [IgorTimofeev/MineOS#173]
I can't open "Reactor CTRL";

Error : https://i.imgur.com/BTFKZHF.png

**Comment by IgorTimofeev** [comment]
@LePandaFou77 Meow, it's a software from independent developer that was just posted to App Market by him. I've no possibilities to fix any errors on programs like that

**Comment by intervisionlord** [comment]
There are several problems with names of libraries
e.g:

- MineOSInterface now called as GUI
- MineOSPaths as Paths
- MineOSCore as System

You should fix it yourself on your ingame computer, cuz it seems, that developer of this app abandoned it
