### ISSUE TITLE
Установка сторонних скриптов

### ISSUE THREAD

**Issue by intervisionlord** [IgorTimofeev/MineOS#178]
Доброго времени суток.
Не уверен, поддерживается ли ОСь до сих пор, но все же спрошу...

Не совсем понятно, как правильно установить скрипты с pastebin из под самой ОС, чтобы запускать их оттуда же.

Некоего аналога консоли или терминала в ОСи не реализовано.

Собственно вопрос по сабжу - как правильно скачать скрипт так, чтобы он отображался внутри ОСи и запускался из под нее же?

**Comment by IgorTimofeev** [comment]
Мяу? Пкм - создать - файл по URL. Ну, а после загрузки Lua-файлы запускаются через местную IDE.

**Comment by intervisionlord** [comment]
Как-то упустил этот пункт из виду, большое спасибо.
