### ISSUE TITLE
Requiring a custom library gives recursive require error.

### ISSUE THREAD

**Issue by chrispytoes** [IgorTimofeev/MineOS#179]
I am trying to require a lua file in an application which I added to the `Libraries` folder, and I keep getting the error: `"Components/PowerStatus" is trying to require another library that requires it`.

Here is where I require it from the application at `Applications/ME Monitor.app/Main.lua`
```
local GUI = require("GUI")
local PowerStatus = require("Components/PowerStatus")
```

And the PowerStatus library's require statements at `Libraries/Components/PowerStatus.lua`
```
local GUI = require("GUI")
local me = component.me_controller
```

The error still occurs when I comment out everything except for the lines above.

**Comment by IgorTimofeev** [comment]
Are you sure that's a full code? It works fine:

![Снимок экрана 2019-05-28 в 10 25 47](https://user-images.githubusercontent.com/11760002/58459093-460bbb80-8133-11e9-9d25-52af1ba45ad3.png)

![Снимок экрана 2019-05-28 в 10 25 35](https://user-images.githubusercontent.com/11760002/58459037-2f656480-8133-11e9-80bb-58f06810ff92.png)

![Снимок экрана 2019-05-28 в 10 25 54](https://user-images.githubusercontent.com/11760002/58459050-37250900-8133-11e9-8ae9-012564870cd9.png)

This error could happen ONLY if libraries perform a recursive "require" calls through themselves: for example, if you're do require("meow.lua") from "purr.lua", and doing require("purr.lua") from "meow.lua".

**Comment by CoolCat467** [comment]
Powerstatus.lua might be incorrectly trying to get the ME Controller. Try the following: `local meController = component.proxy(component.list("me_controller")())`

**Comment by CoolCat467** [comment]
@chrispytoes Reffer to my previous comment. If that works, this issue can be closed.

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/124782992-60890380-df4d-11eb-87ea-6c135c8340ad.png)
