### ISSUE TITLE
Wiki Handle

### ISSUE THREAD

**Issue by Cinobi** [IgorTimofeev/MineOS#180]
Как блин пользоваться Handleами из filesystem,  в вики чушь какая-то написана: 

```filesystem.open(string path[, string mode]): table handle```

Сделайте пример кода пожалуйста =)

**Comment by IgorTimofeev** [comment]
На каждую строчку пояснение уже надо что ль? У меня даже сеструха по вики этой спокойно бинарники записывала/читала, когда пейнт самопальный делала. 

Table (курсивом даже выделено) - тип данных. Handle - краткая инфа о данных, дескать, эта таблица репрезентирует буферизированный файловый дескриптор, обернутый в таблицу с доп. методами

Примеры кода добавлю, конечно, но это уже пиздец деградация
