### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by myraidlabs** [IgorTimofeev/MineOS#185]
When I install it, I can't get it to sale properly to my screen.  It's tier III, so I don't know what I'm doing wrong

**Comment by IgorTimofeev** [comment]
Meow? Do you mean "black strips" effect or what? If so, it's not an issue, it's just how content is being rendered on OpenComputers screens

**Comment by CoolCat467** [comment]
This can probably be closed then.

**Comment by SashaTalk** [comment]
> @myraidlabs This can probably be closed then.

This Issue is the last contribution of this guy. Well yeah, it should be closed.

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/148643832-6c031d0f-8bbc-45b1-8110-f31206fe63d4.png)
