### ISSUE TITLE
A Question, meow and changes

### ISSUE THREAD

**Issue by veso266** [IgorTimofeev/MineOS#188]
Hi there since a lot of things had changed since I last visited MineOS (1 year ago)
I thought I should write them somewhere
DoubleBuffering became Screen and its DrawChanges method became Update
context became System or did it??
it had a method called context.menu it was used like this
```lua
local action = context.menu(e[3], e[4], {"Add Station", #radioStations >= countOfStationsLimit}, {"Delete station", #radioStations < 2}, "-", {"About this program"}, "-", {"Quit"})
			if action == "Add Station" then
                            print("Add station was called")
                        end
```

which I don't know equivalent of in GUI lib
GUI::startEventHandling() is now GUI::start()
ESCAPI is gone :sob:  (I realy miss error method and its universalWindow)
but some of its methods I don't know equvalents of like
ecs.stringLimit
ecs.clickedAtArea
ecs.universalWindow

what are they?

now a question:
I have this piece of code
```lua
local GUI = require("GUI")
local screen = require("Screen")
local bigLetters = require("bigLetters")
local RAPI = require("RadioAPI")

--------------------------------------------------------------------------------

local mainContainer = GUI.workspace()
mainContainer:addChild(GUI.panel(1, 1, mainContainer.width, mainContainer.height, 0x262626))

-- Specify any text you want to
local text = "hi there"
-- Obtain big letters size in pixels
local textWidth, textHeight = bigLetters.getTextSize(text)
-- Create an empty object with text size
local object = mainContainer:addChild(GUI.object(3, 2, textWidth, textHeight))
-- Attach a .draw() method that will draw it's content to screen buffer
object.draw = function()
	bigLetters.drawText(object.x, object.y, RAPI.colors.orange, text)
end

--------------------------------------------------------------------------------
local function HandleTouch(mainContainer, object, e1, e2, e3, e4, e5) 
		if e1 == "touch" then
			if e5 == 1 then ---when I right click I should get context menu like in HEX app
				local menu = GUI.addContextMenu(mainContainer, e3, e4)
				menu:addItem("Exit").onTouch = function()
					mainContainer.stop(); --Exit App
				end
			end
			--mainContainer:draw()
		end
end
--------------------------------------------------------------------------------
-- Draw mainContainer content once on screen when program starts
mainContainer:draw()
-- Start processing events for mainContainer
mainContainer:start()

mainContainer.eventHandler = HandleTouch
```
I am not sure why I cannot create right-click menu?

another question, meow
How would I load a library from the same dir as my app is
lets suppose I have RadioLib.lua in lib dir
something like 

```
myTerrible.app
   Main.lua
   Libs
      RadioLib.lua
```
in normal Lua I woud write this into Main.lua and load my lib
local RAPI = require("Libs.RadioLib")
I tried that but MineOS cannot find it only can load it if its located in Libraries folder in the root where all the other libraries are located, is there a way my app could install my Lib in Libraries dir if it cannot load it from its dir?

Please if its possible don't introduce anymore breaking changes if you have to change something keep the old method and write Legacy in the docs besides it so new devs now not to use it anymore :smile:

Thanks for Anwsering and Best Regards, hope your cats are fine, would really like to see one :smile:
PS: now lets discuss standalone version a bit :smile: 
I see that a lot of libs from OpenOS are missing like os, io, term, and so on
now for os.sleep I found event.sleep
for io.open I found filesystem.open

but what about print and io.stream? are there any equvalent functions?, was wondering how do you print something nowadays is there a debug.print or something like that since MineOS is standalone I cannot find any shell :smile:

**Comment by IgorTimofeev** [comment]
> Hi there since a lot of things had changed since I last visited MineOS (1 year ago)
I thought I should write them somewhere
DoubleBuffering became Screen and its DrawChanges method became Update
context became System or did it??

When OS has released as standalone version - many stuff changed. All info about system API exists in wiki.

> ESCAPI is gone 😭 (I realy miss error method and its universalWindow)
but some of its methods I don't know equvalents of like
ecs.stringLimit
ecs.clickedAtArea
ecs.universalWindow

Deprecated pieces of shit was removed in standalone version.
StringLimit -> (Text API).limit
clickedAtArea -> deprecated and removed cause it doesn't belongs to OOP UI concept of OS
universalWindow -> same

> I am not sure why I cannot create right-click menu?

You're calling **start()** function of a workspace - and it's being **infinitely** waiting for some events. ```mainContainer.eventHandler = HandleTouch``` will never be executed


> How would I load a library from the same dir as my app is

OpenComputers is not a "normal lua" and MineOS is not an shell script that parses any shit for you. You must specify absolute path to your relatively located lib: 

```lua
local system = require("System")
local filesystem = require("Filesystem")
local path = filesystem.path(system.getCurrentScript()) .. "Libs/RadioLib.lua"
```

> Please if its possible don't introduce anymore breaking changes if you have to change something keep the old method and write Legacy in the docs besides it so new devs now not to use it anymore 

Nope, I just don't care during OS developing. Developing is finished - so it's unlikely that there will be any changes

> but what about print and io.stream? are there any equvalent functions?, was wondering how do you print something nowadays is there a debug.print or something like that since MineOS is standalone I cannot find any shell 😄

Why the fck do i need this shit in fkin UI OS? There's no any shell. Who the fck need shell? OpenOS is your bro here <3

**Comment by veso266** [comment]
Thanks for anwsering you think you could curse a bit less often?

So how can I create right click menu now?

**Comment by IgorTimofeev** [comment]
> So how can I create right click menu now?

The same fucking way it's discribed in wiki. 

```lua
local GUI = require("GUI")

--------------------------------------------------------------------------------

local workspace = GUI.workspace()

local panel = workspace:addChild(GUI.panel(1, 1, workspace.width, workspace.height, 0x2D2D2D))

panel.eventHandler = function(workspace, object, e1, e2, e3, e4, e5)
  if e1 == "touch" and e5 == 1 then
    local contextMenu = GUI.addContextMenu(workspace, e3, e4)
    contextMenu:addItem("New")
    contextMenu:addItem("Open")

    local subMenu = contextMenu:addSubMenuItem("Open with")
    subMenu:addItem("Explorer.app")
    subMenu:addItem("Viewer.app")
    subMenu:addItem("Finder.app")
    subMenu:addSeparator()
    subMenu:addItem("Browse...")

    workspace:draw()
  end
end

--------------------------------------------------------------------------------

workspace:draw()
workspace:start()
```

> Is there any equvalent thing for clickedAtArea
No, I even can't understand why someone may need it. GUI library automatically performs all calculations - so **touch** event will raise event handlers **only** if given object was clicked by user. If you need to draw an arrow - just create an simple **GUI.object** with your custom **.draw** function. If you need to check clicks on it - attach an event handler.

**Comment by CoolCat467** [comment]
Probably good to close now, right?

**Comment by veso266** [comment]
Yea, probably

Not aure is MineOS still in development? Does the info up there still apply?

**Comment by CoolCat467** [comment]
@veso266 No, development got finished a long time ago, apparently IgorTimofeev is now only fixing bugs or something.

**Comment by SashaTalk** [comment]
> Yea, probably

Then close it

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/147929016-2fb1f23d-42be-4a23-b319-85a38f45c5f0.png)
