### ISSUE TITLE
Blue screen on install

### ISSUE THREAD

**Issue by IlyaVorozhbit** [IgorTimofeev/MineOS#189]
It happened after I wrote: "pastebin run 0nm5b1ju"

[Blue Screen](https://yadi.sk/i/iCKyOEZQtxnECg)

[Computer hardware](https://yadi.sk/i/tRRRoixKs2iMsA)

The computer began to work again only with the new EEPROM, but now I have 2 broken EEPROM. Thanks ;)

Yes, Minecraft Version - 1.12.2, OpenComputers - 1.7.4.153

**Comment by IlyaVorozhbit** [comment]
I get it, github.com not in whitelist

**Comment by IgorTimofeev** [comment]
:((
