### ISSUE TITLE
Images in MineOS application

### ISSUE THREAD

**Issue by Masterlupo** [IgorTimofeev/MineOS#190]
i've tried to insert images in mine MineOS application (following the wiki) but nothing, error.

![Cattura](https://user-images.githubusercontent.com/50267464/62623363-ef83e000-b920-11e9-8e3d-ef94486dfe5d.PNG)

**Comment by IgorTimofeev** [comment]
Meow, image loading may fail - and **false** plus **string reason** will be given. If you're adding **GUI.image** widget directly after loading image file you should be sure that image file exists and not broken. Otherwise you can use this:

```lua
local result, reason = image.load("/U.pic")
if result then
  workspace:addChild(GUI.image(1, 1, loadedImage)
else
  GUI.alert("Something wrong: " .. reason)
end
```
