### ISSUE TITLE
MineOS fails to install

### ISSUE THREAD

**Issue by QEStudios** [IgorTimofeev/MineOS#204]
Every time the loading bar gets filled, this error message comes up:

machine:1494 [string "..."]:183: load =GUI: java.lang.NullPointerException
stack traceback:
 [Java]: in ?

**Comment by IgorTimofeev** [comment]
some mod Java error, don't know what it is and how to fix it

**Comment by 3pixl** [comment]
> 
> 
> Every time the loading bar gets filled, this error message comes up:
> 
> machine:1494 [string "..."]:183: load =GUI: java.lang.NullPointerException
> stack traceback:
> [Java]: in ?

On what version of OpenComputers you're playing? If on dev version, then MineOS can't be installed cuz LuaJ is the only arch in dev verison. If on stable ver... I don't know

**Comment by ProjectHSI** [comment]
/\ Considering that I think it's time to update to a stable version..

**Comment by CoolCat467** [comment]
I think this can be closed now then

**Comment by CoolCat467** [comment]
@QEStudios If this issue no longer appears in the newest versions of both MineOS and OpenComputers 1, this should be closed.

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/124787136-f5413080-df50-11eb-8e8b-6a9589f6ae96.png)
