### ISSUE TITLE
Ошибка при попытке войти в ВКонтакте

### ISSUE THREAD

**Issue by DarkShyMW** [IgorTimofeev/MineOS#207]
Здравствуйте, при попытке войти в аккаунт выдает ошибку, что неправильный запрос.

**Comment by IgorTimofeev** [comment]
Здравствуйте. Я хуй знает, что там за хуйня. Без контекста ошибки решение проблемы не выссу, да и приложуху более не поддерживаю. Не работает - хуй с ней.

**Comment by CoolCat467** [comment]
Думаю вопрос можно закрыть сейчас
(en: I think issue can be closed now)

**Comment by SashaTalk** [comment]
Может закрыть иссую?

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/148524266-356225dc-3ab7-4d32-bf96-daf4e60c4115.png)

**Comment by MrFredber** [comment]
Обожаю эту фотку :D

**Comment by CoolCat467** [comment]
=^._.^=
