### ISSUE TITLE
где блять софтина?

### ISSUE THREAD

**Issue by 0x77dev** [IgorTimofeev/MineOS#208]
Где софтина для отрисовки местности с помощью ` Hologram Projector ` и ` Geolyzer `?

**Comment by IgorTimofeev** [comment]
Та хз, удалили, видимо, с маркета

**Comment by 0x77dev** [comment]
А как то ?

**Comment by IgorTimofeev** [comment]
Не проссал вопроса. Кто удалил? Тот, кто опубликовал. Почему? Хз, мб несовместима прога стала с новыми версиями, мб лень поддерживать было

**Comment by 0x77dev** [comment]
@IgorTimofeev 🤣
