### ISSUE TITLE
How to use native libraries?

### ISSUE THREAD

**Issue by Senliast** [IgorTimofeev/MineOS#213]
How can i use native libraries, for example redstone?

**Comment by IgorTimofeev** [comment]
Hm... "Redstone" is not a library, it's a component **proxy**. 

```lua
local redstone = component.redstone

redstone.setOutput(0, 15)
```

or

```lua
local redstone = component.get("redstone")

redstone.setOutput(0, 15)
```

**Comment by Senliast** [comment]
Ah i see, thanks) one question more - why cannot i use "print" command, like in GUI Api
described? it always gives "print is nil error"

**Comment by IgorTimofeev** [comment]
Because "print" is OpenOS function, not MineOS. OpenOS has an interactive shell which can display "printable" stuff. MineOS has a windowed GUI. If you need to show some script info - use this:

```lua
local GUI = require("GUI")
GUI.alert("it's like a print")
```

**Comment by LaysDragon** [comment]
https://github.com/IgorTimofeev/MineOS/wiki/GUI-API#guiworkspacex-y-width-height-extends-guicontainer
there is a code snippets use the print and related to a nonexistent terminal,lead me misunderstanding there is a print function and terminal and spent a lot of time to find why print function is not working.Docs might outdated
```lua
-- Import the library
local GUI = require("GUI")

--------------------------------------------------------------------------------

-- Create new workspace
local workspace = GUI.workspace()

-- Create simple event handler for it
workspace.eventHandler = function(workspace, object, ...)
    print("It works! The event data was: ", ...)
end

--------------------------------------------------------------------------------

-- Start processing events for workspace
workspace:start()
```

**Comment by IgorTimofeev** [comment]
Docs can have some library migration issues (from OpenOS to MineOS). Changed to GUI.alert, thanks
