### ISSUE TITLE
Can't install MineOS

### ISSUE THREAD

**Issue by Ormoyo** [IgorTimofeev/MineOS#221]
I have the mod OpenComputers, I have a computer case tier 3 with tier 3 CPU, tier 3 graphics card, tier 2 graphics card, Internet Card, 2X tier 3.5 Memory, OpenOS disk, tier 3 Hard Disk Drive, tier 2 Hard Disk Drive, Lua BIOS and I have a power source but when I use the command "pastebin run 0nm5b1ju" it says "Unrecoverable Error bad argument #3 (number expected, got nil)"

**Comment by IgorTimofeev** [comment]
Meow, i can't to reproduce error (and fix) without additinal info. And you can't get any info because of custom minified BIOS. Sorry for this

**Comment by ProjectHSI** [comment]
Yeah. I have encountered this before.
To solve this do this:

- Install OpenOS
- Get a new OpenOS BIOS.

**Comment by ProjectHSI** [comment]
https://github.com/IgorTimofeev/MineOS/issues/251#issuecomment-612828903

**Comment by CoolCat467** [comment]
If anything check the capitalization of pastebin code, or try to run the github install command instead.

**Comment by CoolCat467** [comment]
@Ormoyo Any luck?

**Comment by IgorTimofeev** [comment]
@CoolCat467 Ты так стараешься, поддерживаешь оську, мне даже стыдно :(

**Comment by SashaTalk** [comment]
> @Ormoyo Any luck?

Ormoyo made last contribution made in June. There is no additional information that can solve issue. Issue should be closed

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/148643858-cce12e34-c3b8-4f44-9fae-12ac85a609e5.png)
