### ISSUE TITLE
Translation on MineOS

### ISSUE THREAD

**Issue by PaffcioStudio** [IgorTimofeev/MineOS#224]
I don't have permission to the pull request. I am sending a translation in Polish.

https://pastebin.com/ryCriCnf

**Comment by IgorTimofeev** [comment]
Meow, I can't add only OS localization without installer localization (they work in pair during installation process). Please add installer file as well

**Comment by CoolCat467** [comment]
I could make a Polish installer localization since it looks like @PaffcioStudio is not.

**Comment by CoolCat467** [comment]
There we go. Now pull request number #305 should have @PaffcioStudio 's polish translation and my own installer translation files.

**Comment by CoolCat467** [comment]
@PaffcioStudio This can now be closed after pull request #305 has been merged.

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/124787273-09852d80-df51-11eb-827b-9e8e8b9b0548.png)
