### ISSUE TITLE
Allow disabling interrupts

### ISSUE THREAD

**Issue by NopeDK** [IgorTimofeev/MineOS#225]
Please allow us to disable hard interrupts (CTRL-ALT-C) in some way.

Doing the following does not work.
```
local event = require("event")

event.interruptingEnabled = false

while true do
  event.sleep(0.1)
end
```
Checking the data in `event` before and after shows that it correctly changes the flag.
After pressing CTRL-ALT-C when the above is running, it exits with
```
interrupted
stack traceback
[C]: in function 'error'
/Libraries/Event.lua:107: in field 'pull'
/Libraries/Event.lua:128: in field 'sleep'
/script.lua:6: in main chunk
```
As it normally does with the hard interrupt.

If you press any key after interrupting it, the computer turns off instantly without any error.

**Comment by NopeDK** [comment]
I found a temporary solution by copying and modifying the Event library, specifically the routine where CTRL-ALT-C is done and adding a username check on the event.
This also requires one to copy all libraries that utilize the Event library and modify them to point to the modified Event library.

**Comment by IgorTimofeev** [comment]
Meow, the solution was to use

```lua
if (signalData[1] == "key_down" or signalData[1] == "key_up") and event.interruptingEnabled then
```

instead of

```lua
if signalData[1] == "key_down" or signalData[1] == "key_up" and event.interruptingEnabled then
```

Fucking braces! Btw thanks for this issue, I would never have noticed it, because I never used interruption disabling feature
