### ISSUE TITLE
You can delete the only user if it has no password and this crashes the computer.

### ISSUE THREAD

**Issue by NopeDK** [IgorTimofeev/MineOS#227]
MineOS currently crashes if there are no users. ~~OpenComputers mentions that a computer with zero users become publically available.~~

If you remove your password in the User Management and reboot the computer, you lose the possibility to add a password.

In the User Management panel, you can delete yourself if you have no password, resulting in the error:
`Failed to update file list: nil`
On line 65 in Main.lua.

Trying to boot the computer without any users results in the following crash on boot:
```
MineOS EFI
/Libraries/Paths.lua:39: attempt to concatenate a nil value (local ´name´)
stack traceback:
machine:796: in metamethod ´__concat´
/Libraries/Paths.lua:39: in field ´getUser´
/Libraries/Paths.lua:54: in field ´updateUser´
/Libraries/System.lua:2753: in local ´loadUserSettingsAndCheckProtection´
/Libraries/System.lua:2771: in field ´authorize´
/OS.lua:215: in main chunk
[C]: in function ´xpcall´
bios:1: in upvalue ´Z´
bios:1: in local ´a1´
bios:1: in main chunk
```

**Comment by IgorTimofeev** [comment]
> MineOS currently crashes if there are no users. OpenComputers mentions that a computer with zero users become publically available.

> In the User Management panel, you can delete yourself if you have no password, resulting in the error:
Failed to update file list: nil
On line 65 in Main.lua.

Fixed, thanks. By default, OS can't work without any users, so "remove user" button in Settings app is disabled while selecting currently logged in user. There was a mistake in System library while obtaining users list - and this button just wasn't able to become "disabled"

> If you remove your password in the User Management and reboot the computer, you lose the possibility to add a password.

Can't reproduce this issue. I removed my password, rebooted - and everything works normally, I can add password if I need to. Perhaps this is a consequence of a previous error - but if not, let me know if it will happen again.
