### ISSUE TITLE
Add Multiboot

### ISSUE THREAD

**Issue by 3pixl** [IgorTimofeev/MineOS#231]
It's would be a good idea to add Multiboot in MineOS EFI. For example, if you want some assistance by console, you can boot to OpenOS. If you want to use GUI, boot to MineOS. I think it's a good feature to extend EFI.
Что скажешь, Игорь?

**Comment by IgorTimofeev** [comment]
Дык эта фича уже сто лет как имеется:

![image](https://user-images.githubusercontent.com/11760002/72191436-34053180-3413-11ea-8329-9ec663300989.png)

![image](https://user-images.githubusercontent.com/11760002/72191440-39627c00-3413-11ea-8223-d49487588576.png)

**Comment by 3pixl** [comment]
Ля как
