### ISSUE TITLE
Unable to install MineOS

### ISSUE THREAD

**Issue by ndiniz2013** [IgorTimofeev/MineOS#234]
I've attempted to run MineOS on a system with the following specs:

Tier 3 graphics card
Internet Card
CPU Tier 3
2x Memory Tier 3.5
Hard Disk Tier 3 (4 MB) and Tier 2 (2 MB)

However, when I do pastebin get -0mn5b1ju I get the following:
![2020-01-15_23 04 42](https://user-images.githubusercontent.com/7496027/72495180-91bac480-37eb-11ea-88c6-085b2b64ea90.png)

I have no idea of what's going on, or if I need to adjust some kind of file or something. I also tried to download another OS and got a similar error. Any help in solving this problem would be greatly appreciated.

**Comment by IgorTimofeev** [comment]
0**nm**5b1ju, not 0**nm**5b1ju
