### ISSUE TITLE
Double keystrokes

### ISSUE THREAD

**Issue by TurretKingVIII** [IgorTimofeev/MineOS#236]
I have installed MineOS on both a server and a normal computer, and whenever you type something, it enters two characters. If that makes any sense. I have reinstalled MineOS like three times now and it still comes up

![2020-01-30_18 39 03](https://user-images.githubusercontent.com/51881121/73500079-d1f37880-438f-11ea-9c73-836a335204a8.png)

**Comment by IgorTimofeev** [comment]
Let me guess: you have 2 keyboards attached to screen?

**Comment by TurretKingVIII** [comment]
Ah...

Well I'm just stupid aren't I 😂😂

Thank you so much, I'm sorry for the dumb question

**Comment by IgorTimofeev** [comment]
nah that's okay, take a doggy

![image](https://user-images.githubusercontent.com/11760002/73590690-56600b80-44f6-11ea-8584-c56d0e624b12.png)
