### ISSUE TITLE
Не могу установить

### ISSUE THREAD

**Issue by JolySwally1** [IgorTimofeev/MineOS#243]
Вот ошибка
![image](https://user-images.githubusercontent.com/32881362/78056207-662c8c80-738d-11ea-9b37-1d904aa3b9e1.png)

**Comment by CoolCat467** [comment]
@JolySwally1 Похоже, он запрашивает URL "https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/" дважды, в основном, рядом друг с другом. Это означает, что вы, вероятно, набрали скрипт установщика для github, но почему-то сделали это неправильно? Я не могу сказать без дополнительной информации. Попробуйте еще раз, я думаю, и покажите / скажите мне, какую именно команду вы ввели.

en:
@JolySwally1 It looks like it is requesting the URL "https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/" twice right next to each other basically. This means you probably typed in the installer script for github, but somehow did it incorrectly? I can't tell without more information. Try it again I guess, and show/tell me exactly what command you typed in.

**Comment by CoolCat467** [comment]
@JolySwally1 Повторите попытку с последней версией MineOS и OpenComputers 1. 

en:
@JolySwally1 Please try again with newest version of both MineOS and OpenComputers 1.

**Comment by SashaTalk** [comment]
JolySwally1's last contribution on GitHub made in August 2020
Issue should be closed?

**Comment by IgorTimofeev** [comment]
> Issue should be closed?

![image](https://user-images.githubusercontent.com/11760002/147929038-4a697b7a-087d-449d-b15b-85cd3b15313b.png)
