### ISSUE TITLE
Minecraft 1.6.4 - Install problem.

### ISSUE THREAD

**Issue by DominikJoppa** [IgorTimofeev/MineOS#246]
Hi, I have problem with install.

Minecraft 1.6.4
OpenComputers-MC1.6.4-1.3.6.561

![Snímka](https://user-images.githubusercontent.com/16322623/78817054-e036c400-79d2-11ea-814b-5e824d8c7b28.PNG)

**Comment by IgorTimofeev** [comment]
Too old opencomputers version, i have no idea of what's wrong here. No errors
