### ISSUE TITLE
Screen Resolution problem.

### ISSUE THREAD

**Issue by MenschenToaster** [IgorTimofeev/MineOS#252]
Before I start I want to say that this OS is amazing. WOW. There are some Computer Mods that have a System directly integrated and they are worse than an Os written for/in a mod! 
-------------------------
What are my OpenOS Computer Specs

I have 6 Tier 3 Screens
A normal Tier 3 Case
Tier 3 Graphics Card
Internet Card
2x 3.5 Ram
1x Tier 3 Hardrive

--------------------------
What is my Problem:
Sometimes my Computer is scaling wrong.
Here a Screenshot http://prntscr.com/s0ume2
Instead of the right resolution:
http://prntscr.com/s0uoe7

Is this Bug known? Is there a way to fix it?
I'm on 1.12.2 btw. With OpenComputers 1.7.5.192

-----------------------------------------
And I'm happy to announce that I will help with this Project.
I'm from Austria and I'm playing with my friends from Germany on my Server.
And we found out that we couldn't use our computer in German very well.
The German translation is really bad. I am not the best in German but I think I can help.
Here an example of the shitty translation: "Flashing EEPROM" -> "Blinkendes EEPROM".
When we translate that back to English it means "blinking EEPROM" which is very confusing.

I hope you can help me, and I can help this Project soon :)
Have a nice Day,
MenschenToaster | David

**Comment by IgorTimofeev** [comment]
> Is this Bug known? Is there a way to fix it?

No, and without any information except "sometimes scaling is wrong" I can't do anything to fix it beacuse I'm not interested in this project anymore to spend time to looking for bugs

> The German translation is really bad. I am not the best in German but I think I can help

You can do pull request with "correct" translation (not the Google translated version like now), I'll be happy to merge it

**Comment by IgorTimofeev** [comment]
UPD: in the first screenshot color palette of GPU/screen is primitive. Seems like your computer have multiple GPUs or something like that - so system just take control of the first of them. If so, use only one Tier 3 GPU, and the problem should be gone

**Comment by CoolCat467** [comment]
@MenschenToaster , did this fix your issue? If so, I think this issue can be closed.

**Comment by tbdrabbit** [comment]
The scaling issue happens with an apu and any tier screen  &  a 2 x 3 screen.
 --> Issue corrected, via switching to CPU with GPU remove of apu and volia. 
Issue is creatable with this setup      tier 3 case, tier 3 apu, 2 ram sticks, 2x3 tier 2 screen.  
if this will be primary user terminal in system, best to use dedicated cpu and gpu and connect to Rack and Server.
Hope this helps

**Comment by CoolCat467** [comment]
From email that somehow didn't appear here from Dahs Rabbit that solved the issue:
"The scaling issue happens with an apu and any tier screen  &  a 2 x 3 screen.
 --> Issue corrected, via switching to CPU with GPU remove of apu and volia.
Issue is creatable with this setup      tier 3 case, tier 3 apu, 2 ram sticks, 2x3 tier 2 screen.
if this will be primary user terminal in system, best to use dedicated cpu and gpu and connect to Rack and Server.
Hope this helps"
