### ISSUE TITLE
Installer does not download the latest libraries or appilcations.

### ISSUE THREAD

**Issue by ProjectHSI** [IgorTimofeev/MineOS#253]
I mean. It does download them. But
## Not.
# Update them!
You have to update manually.

**Comment by ProjectHSI** [comment]
And before I forget this. I did use the one mentioned in the readme.md file!

**Comment by IgorTimofeev** [comment]
Yeah, it's known issue. I just don't want to put additional load on AppMarket host by obtaining a list of current apps versions during every OS installation. This is still a home project, not a public commercial system

**Comment by ProjectHSI** [comment]
Ok.
