### ISSUE TITLE
Не могу открыть свою публикацию в App Market.

### ISSUE THREAD

**Issue by Navatusein** [IgorTimofeev/MineOS#254]
Я опубликовал приложение в App Market. После публикации вылезает ошибка при: попытке скачать приложение, попытке открыть описание, попытке редактировать.

Вот фото ошибки.
https://i.imgur.com/qjRq38J.png

**Comment by IgorTimofeev** [comment]
Исправил вручную в базе маркета. Видимо, по какой-то причине перевод на нужную локализацию через яндекс был безуспешен

**Comment by Navatusein** [comment]
Спасибо!)
