### ISSUE TITLE
I don't know what happened...

### ISSUE THREAD

**Issue by cgiigc** [IgorTimofeev/MineOS#255]
So, I put all the required things in the computer case, then started my computer.

Then, it goes to the MineOS loading screen when I put in the pastebin command or whatever.

After a bit of loading it crashes, and the message is: "bad argument #3 (number expected, got nil)"

I'm using Immersive Engineering to power the computer.
Oh, and I just installed OpenComputers today so tell me what to do if I need to provide further details.

I can't start up my computer again now....

**Comment by BlackShape** [comment]
Just give it a new LUA eeprom and it should work again, and you can start over again.

**Comment by cgiigc** [comment]
Okay I will try that and let you know if it works :)

**Comment by cgiigc** [comment]
Okay so it says "No appropriate filesystem found" how can I fix this? :) (it says that on the mineos loading screen)

**Comment by cgiigc** [comment]
Okay so once the loading bar gets to the end it says this - "GUI:853: attempt to index local 'image' (a boolean value)"

**Comment by BlackShape** [comment]
Make sure you are using a Computer Case Tier 3(CPU, RAM, HDD Tier3)and a Network Card, and install OpenOS before everything else.

**Comment by cgiigc** [comment]
Yes, I have tried that

**Comment by KyleBCox** [comment]
just to note I got this issue "bad argument #3 (number expected, got nil)" but didn't touch anything (didn't even replace the EEPROM )and just turned the machine back on (it had automatically shut down) and it loaded the installer perfectly fine.
--- a few moments later ---
so I have just let it finish installing and it works fine, boots up doesn't seem to be any noticeable issues, however, I will see how it pans out after using it a bit.

**Comment by cgiigc** [comment]
> just to note I got this issue `"bad argument #3 (number expected, got nil)"` but didn't touch anything (didn't even replace the EEPROM )and just turned the machine back on (it had automatically shut down) and it loaded the installer perfectly fine.
> --- a few moments later ---
> so I have just let it finish installing and it works fine, boots up doesn't seem to be any noticeable issues, however, I will see how it pans out after using it a bit.

Yeah, I had this issue as well, I tried turning it back on but it still says that.

Sorry for the late response.

I guess I'll just try whatever I can, thanks guys.
