### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by BichSuckCock** [IgorTimofeev/MineOS#257]
So i was playing with the os and managed to translate it, but i don´t had rights to contribute so here is both .lang files. I would appreciate if those would be added to the project.
[Finnish.zip](https://github.com/IgorTimofeev/MineOS/files/4674171/Finnish.zip)

**Comment by IgorTimofeev** [comment]
No problem, localization has been added. Thanks!

**Comment by BichSuckCock** [comment]
thx
