### ISSUE TITLE
 Error installing MineOS

### ISSUE THREAD

**Issue by Godzillka** [IgorTimofeev/MineOS#260]
All Level 3 Computer Components
When writing the command ''pastebin run 0nm5b1ju'' gives an error
![Screenshot_2](https://user-images.githubusercontent.com/65909687/82823756-f7ba0580-9ec9-11ea-82c4-1dc5a092ed25.png)

**Comment by Godzillka** [comment]
If possible, clear and detailed instructions from start to installation.  Maybe I did something wrong.  I have all the main components and a network card.  There is also an OpenOS and EEPROM diskette with the OpenOS that I previously installed.

**Comment by IgorTimofeev** [comment]
Something with your internet connection to pastebin.com. Nothing I can help you with

**Comment by Godzillka** [comment]
Кстати возможно. Потому что когда я в браузере набираю pastebin.com он
просто не открывается. Возможно vpn поможет мне.

вт, 26 мая 2020 г., 3:30 IgorTimofeev <notifications@github.com>:
