### ISSUE TITLE
как поженить свои Eventы с  Eventами GUI библиотеки

### ISSUE THREAD

**Issue by arduinka55055** [IgorTimofeev/MineOS#261]
https://github.com/IgorTimofeev/MineOS/wiki/Event-API#eventaddhandlerfunction-func-int-interval-int-times-table-handler
использовал вызов каждую секунду(для обновления значений):
`event.addHandler(function()
  -- Do someting every 5 seconds
end, 5)
--копипаста с вики`

но функция вызывается когда кликаю(жму на клаву) по экрану, если не кликать - данные не обновляются, чуда не происходит

от мой код, закомментировал фоновую картинку и лишнее, управляю реактором из мода big reactors(переименовал в формат .txt, ибо github не жуёт(или я лох))

[main.txt](https://github.com/IgorTimofeev/MineOS/files/4731054/main.txt)

но стоит заметить, если зажать Enter, то наблюдается нормальная работа. 

после`workspace:start()` дело не идёт, но если его нахрен закомментировать, то работает мой код. Но кнопочки не нажимаются, ясен пень.
-------------------------------------------------------
workspace:draw()
--workspace:start()
while true do
    event.pull(0)
    workspace:draw()
end
 |
\\/
но если нажать на ctrl alt c, то почему-то начинает работать и то, и другое. странно... start же не вызывался. 

может я ступил, но вроде внимательно вики читал, а ответа не нашел. может быть и такое.   

P.S.
заранее спасибо, хотя бы за то, что ОСь написал, если бы не mineos, то сдурел бы от самоизоляции

**Comment by IgorTimofeev** [comment]
Все оч просто. Если хочешь юзать event.timer - юзай workspace:start(0) по аналогии с "нативным", computer.pullSignal чтобы ивенты дрочились бесконечно и без ожидания действия юзера. На производительность не повлияет.

Вот эта штука вовсе не нужна, workspace:start() делает всё за тебя: отрисовывает графоуни и чекает нажатия на кнопочки. В :start() уже встроен бесконечный цикл.

```lua
workspace:draw()
--workspace:start()
while true do
event.pull(0)
workspace:draw()
end
```

Если же хочешь делать что-то каждые N сек без event.timer (например, так работают скринсейверы в оське) - то юзай чот типа такого:

```lua
local oldUptime
workspace.eventHandler = function()
  local uptime = computer.uptime()

  -- 5 сек, епта!
  if uptime - oldUptime > 5 then
    oldUptime = uptime
   
    -- Твой ход
  end
end

workspace:start(0)
```

**Comment by arduinka55055** [comment]
Спасибо, может захуярить в Вики. Хочется сделать нормальный контроллер реактора, ибо питон уже надоел. 
Удачи!
не ожидал, что живой.

**Comment by arduinka55055** [comment]
работает, сука!
ну ждите пополнений в магазе
