### ISSUE TITLE
Error when trying to install or use the OS in any way possible:

### ISSUE THREAD

**Issue by QuickMuffin8782** [IgorTimofeev/MineOS#263]
init.lua:2: attempt to index global 'computer' (a nil value)

I'd suggest to use the code from SquidDev from The new ComputerCraft forms. It should help the problem.

**Comment by IgorTimofeev** [comment]
Meow? MineOS doesn't have any "init.lua" or something same. Are you trying to install it manually from OpenOS? This won't work. You should install in only from EEPROM, i.e. from "clear OpenComputers without any OpenOS memory modifications"

> I'd suggest to use the code from SquidDev from The new ComputerCraft forms.

What code?

**Comment by QuickMuffin8782** [comment]
I actually use OpenOS emulator as I don't have a java minecraft. So it results as that error.

**Comment by IgorTimofeev** [comment]
If emulator is "ocemu" - then there's no way to install MineOS for you. Ocemu doesn't support https protocol that is required to download source code files from GitHub (where MineOS is located)

**Comment by CoolCat467** [comment]
I think this can be closed now then.
