### ISSUE TITLE
is there a possible way to connect the WebDisplays OpenComputers interface to open computers ?

### ISSUE THREAD

**Issue by shoter10** [IgorTimofeev/MineOS#264]
i tried to connect the webdisplays OC Module to my OC computer but when i add the MineOS and try to use the WebDisplay application its says that no webdisplays OC module connected can somone help me ?

**Comment by kingofsponges** [comment]
if you want to connect a webdisplays opencomputers interface, use the **adapter** block, as the webdisplays oc interface **is not a component from opencomputers**, its **an addon block from another mod**

**Comment by kingofsponges** [comment]
its the fix as you forgot to use the **adapter** block. its not related to **mineos**, either **the webdisplays application**, but to opencomputers. you could ask about this on [the opencomputers forum](https://oc.cil.li) or in [the opencomputers repository issues](https://github.com/MightyPirates/OpenComputers).

**Comment by CoolCat467** [comment]
This should no longer be an open issue then

**Comment by purpelpower** [comment]
its simple

**Comment by kingofsponges** [comment]
@IgorTimofeev please close issue
