### ISSUE TITLE
Cannot find the localization file icon

### ISSUE THREAD

**Issue by SashaSemenishchev** [IgorTimofeev/MineOS#265]
Cannot find the localization file icon. Please, who can leave the path to the icon.

**Comment by IgorTimofeev** [comment]
По дефолту .lang привязан к MineCode для открытия. Иконка вот тута:
https://github.com/IgorTimofeev/MineOS/tree/master/Applications/MineCode%20IDE.app/Extensions/.lang

Логика следующая: система получает расширение файла ".lang", пиздует в конфиг пользователя Users/Имя/Settings.cfg и ищет ассоциации расширения ".lang" с каким-либо приложением. В нашем случае приложением является MineCode, поэтому система чекает папку Applications/MineCode.app/Extensions/, ищет в ней папку .lang/ и, если находит, назначает указанную иконку и выполняет скрипт для расширения контекстного меню. Как-то так
