### ISSUE TITLE
error on pastebin?

### ISSUE THREAD

**Issue by Teru-dot-png** [IgorTimofeev/MineOS#266]
(recent try)
![image](https://i.imgur.com/NZup6Ui.png)
(i did try to do pastebin run "pbCode" )
![image](https://user-images.githubusercontent.com/68662335/88218000-ccd3ff80-cc35-11ea-8cde-0ccdaca8f1af.png)
i am on version 1.7.10(i did try on latest versions) i dont know if that affects anything
the computer: tier T3.5 , T3 ram. T3 cpu. graphics card also at max tier along with HDD
i did try to put the raw code and run it but nothing... tells me there's a syntax error on 'Local', line 528
unless this is a older lua version im running...

**Comment by Teru-dot-png** [comment]
tried again...
https://i.imgur.com/NZup6Ui.png

**Comment by IgorTimofeev** [comment]
Added alternative installing method on repo page. Maybe this will be helpful

![image](https://user-images.githubusercontent.com/11760002/88453787-f0d05480-ce72-11ea-9441-2e4a295b4e88.png)

**Comment by SaphireLattice** [comment]
There's a typo in the PasteBin ID on the forums, specifically the lowercase letter `m` should be uppercase `M`.

**Comment by IgorTimofeev** [comment]
@SaphireLattice 2 days ago all lowercased permalinks on pastebin ceased to be valid. Why? Who knows... I think by "forums" you mean oc.cil.li/computercraft.ru? Thx, I'll fix it. Unfortunately, links to this installer exists in lots of webpages - and now I can't remember exactly where

**Comment by Teru-dot-png** [comment]
Thank chu, also i big dissapointed at pastebin i dont get why they are region blocking here
