### ISSUE TITLE
Whats up with the images in the GUI Api Docs?

### ISSUE THREAD

**Issue by TheGreyDiamond** [IgorTimofeev/MineOS#267]
There are some pictures with open Skype windows in the GUI Api Docs.... You should change that

**Comment by IgorTimofeev** [comment]
So what? I don't care. I "should"... yeah, this made me laugh

**Comment by TheGreyDiamond** [comment]
You're right, just because there was a webcam feed visible, because of privacy and stuff.

**Comment by IgorTimofeev** [comment]
Nah, that just my friend. She also doesn't care, meow
