### ISSUE TITLE
attempt to concatenate a nil value (local 'name')

### ISSUE THREAD

**Issue by thm51b8f2d68cs** [IgorTimofeev/MineOS#268]
![image](https://user-images.githubusercontent.com/68766033/88448744-b1175780-cdf5-11ea-9cd9-56cdcaba7f8d.png)
I have used paste bin link from this github and tried wget link from this github and both result in this.  Both links get me to the installer where I choose my language and install etc.  Everything runs fine until I reboot the computer and then I get this screen.

**Comment by thm51b8f2d68cs** [comment]
Here is what I do to get this.

1.  Place blank tier 3 hard drive into computer
2.  Place lua eeprom that is crafted with OC manual into computer
3.  Place OpenOS floppy into tier 3 case
4.  Install OpenOS onto tier 3 hdd
5.  Reboot
6.  Remove OpenOS floppy
7.  Paste pastebin link from this github
8.  Follow on screen prompts
9.  Erase disk with OpenOS installation from installer menu
10.  Select that disk for installation of MineOS
11.  Continue to create user screen
12.  Enter username: <SCooBy Doo
13.  Enter password: *wRbNZs5LNu*
14.  Click next and keep all boxes checked
15.  Click next
16.  Wait for install to complete
17.  Reboot
18.  Error shows up

It looked like this had something to do with the account creation so I tested with a username of user1 and password of passwd1 and did not erase the OpenOS disk before installing on it and got no error.

**Comment by IgorTimofeev** [comment]
Nice bug, thanks. I think special characters in the username cannot be used as the name of the user's working directory, since the minecraft server OS imposes its own specific limitations.

Apparently, i will have to give some restrictions on names in the installer...

**Comment by IgorTimofeev** [comment]
Edit: this mess only happens if OpenComputers runs on a Windows based server. Just checked "<SCooBy Doo" user on debian server - everything is fine. Fucking cross-platform

**Comment by IgorTimofeev** [comment]
Fixed
