### ISSUE TITLE
"pastebin run 0nm5b1ju" doesnt work

### ISSUE THREAD

**Issue by kingofsponges** [IgorTimofeev/MineOS#273]
i was recently trying to install mineos using the install script on pastebin but it didnt work.
**(it mainly happens on monday very often)**

it just says it successfully connected to pastebin and it just popped up an error. **(after running pastebin run)**
the issue just disappears after monday, but i just want to use it before. is there a fix?

**Comment by PoltixeTheDerg** [comment]
It's 0nM5b1jU, not 0nm5b1ju: https://pastebin.com/0nM5b1jU

**Comment by kingofsponges** [comment]
ok thanks, must have again done a mistake with the codes

**Comment by Z3v3r** [comment]
pastebin run HvLEX6cx
Work on 2023
