### ISSUE TITLE
app market: connection timed out

### ISSUE THREAD

**Issue by kingofsponges** [IgorTimofeev/MineOS#274]
**(sorry for making 2 issues today, but this time its kind of serious)**
i tried to log into the app market today but it just gave me some error:
`Web request failed: Connection timed out: connect`

what happened to the app market that i cannot get in it?

**Comment by levshx** [comment]
http://mineos.modder.pw/MineOSAPI/2.04/ живи
Жыве беларусь!

**Comment by kingofsponges** [comment]
sorry, i am not from russia, i dont understand at all

**Comment by snaildos** [comment]
Same here!

**Comment by snaildos** [comment]
@kingofsponges "The API will be fixed at the end of this week."
Quoted off @Nik-mmzd

**Comment by kingofsponges** [comment]
@snaildos thanks, gotta check it out soon

**Comment by IgorTimofeev** [comment]
Should be fixed for now

**Comment by snaildos** [comment]
Thank you @IgorTimofeev ! I appreciate it.

**Comment by vladglass0** [comment]
doesn't work
