### ISSUE TITLE
App market does not work

### ISSUE THREAD

**Issue by KKosty4ka** [IgorTimofeev/MineOS#276]
http://mineos.modder.pw/MineOSAPI/2.04/ is dead

(sorry for bad english)

**Comment by PoltixeTheDerg** [comment]
duplicate of #274

**Comment by snaildos** [comment]
What are we going to do about it? I dont own the domain. Who does?

**Comment by SoloMaker** [comment]
I would try to contact the guy who runs https://modder.pw, but he seems to have been last active a month ago.

**Comment by snaildos** [comment]
I just got in contact wihh the developer. Will keep you guys advised on what's going to happen next.

**Comment by Nik-mmzd** [comment]
modder.pw domain owner here.

@SoloMaker mineos.modder.pw is hosted by @IgorTimofeev itself.
Subdomain is working but Igor's server is down.

**Comment by snaildos** [comment]
@Nik-mmzd Damn. I see. Do you have contact with Igor? If you do just tell him I'm happy to run it for him. :) thanks for your time and making your way here.

**Comment by Nik-mmzd** [comment]
@snaildos I contacted @IgorTimofeev already. Waiting for reply now.

**Comment by snaildos** [comment]
@Nik-mmzd Very much appreciated. Again, I'm happy to help with hosting. Thanks for your time.

**Comment by Nik-mmzd** [comment]
API will be fixed at the end of the week

**Comment by snaildos** [comment]
@Nik-mmzd Awesome, Thank you for your time.

**Comment by kingofsponges** [comment]
yes this is a duplicate of my issue, but let me get to the point.
now the message is:
`Web request failed: Connection timed out (Connection timed out)`

the api is dead rn, meanwhile me and my friend are literally panicking. thanks for contacting the devs
i am literally suffering in mineos because i cannot log into my account and upload a single app to the market

**Comment by IgorTimofeev** [comment]
Should be fixed #274
