### ISSUE TITLE
VK app block my account 

### ISSUE THREAD

**Issue by levshx** [IgorTimofeev/MineOS#278]
The app has blocked my account, not the first time, perhaps when to attach a file to a message

**Comment by IgorTimofeev** [comment]
Nothing to Yes, there have already been several similar cases in the last month. Apparently, this is due to a change in the VK policy in relation to third-party applications using the API - alas, I cannot find a solution to the problem yet

**Comment by CoolCat467** [comment]
I think the VK app is no longer supported if I remember correctly.

**Comment by CACKE** [comment]
WHY THIS issue didnt closed

**Comment by IgorTimofeev** [comment]
> WHY THIS issue didnt closed

komu ne pohuy....

**Comment by misha99fr** [comment]
idk lol, nu mne ne pohuy XD
