### ISSUE TITLE
Finder.app FTP Authentication Error

### ISSUE THREAD

**Issue by levshx** [IgorTimofeev/MineOS#279]
I may be using a bad FTP server 000webhost, but FileZilla authorizes everything.

![image](https://user-images.githubusercontent.com/17254908/93360347-3f371980-f84c-11ea-8e88-d4ea55698336.png)

If the problem in hosting can tell me free hosting?

**Comment by IgorTimofeev** [comment]
Yes, this is a known issue. Apparently, in MineOS has only the most primitive version of the FTP client implementation without support for modern options. In the future it would be nice to add support for other cases
