### ISSUE TITLE
Хуета с апп маркетом

### ISSUE THREAD

**Issue by Hatry1337** [IgorTimofeev/MineOS#285]
![image](https://user-images.githubusercontent.com/53402621/98631781-2d935f00-232f-11eb-9ffc-e5b6387f0e1e.png)

Шаги вопсроизведения:
- Зайти в апп маркет
- Перейти в настройки
- Залогиниться
- Перейти во вкладку "Приложения"
- Нажать "Опубликовать ПО"
- Заполнить форму публикации
- Попытаться опубликовать прогу
- Получить хуйню

Проверено на двух разных компах, майнкрафтах, версиях мода и самой майн оси, из чего делаю вывод, что скорее всего хуета с апи

**Comment by Hatry1337** [comment]
Проблема решилась ¯\_(ツ)_/¯

**Comment by IgorTimofeev** [comment]
Да пиздец, тут у Яндекса апи переводчика переобулось и ушло исключительно на коммерческую основу, и все старые ключи стали недействительными. Цыганская ИТ-контора, хули

А как, собственно, проблема-то решилась?

**Comment by Hatry1337** [comment]
> Да пиздец, тут у Яндекса апи переводчика переобулось и ушло исключительно на коммерческую основу, и все старые ключи стали недействительными. Цыганская ИТ-контора, хули
> 
> А как, собственно, проблема-то решилась?

Да не знаю, пошел, поспал, проснулся - нихуя не работает. После минут 5 агрессивного тыканья по разным кнопкам, а также перебора различных параметров формы, удалось кое как выложить приложуху, но после этого не завеоись описание на русском, поставил инглиш в настройках, и вроде как всё даже заработало.

**Comment by IgorTimofeev** [comment]
Пздц, сочувствую. Ща чекну, можно ли это по-фасту оффнуть, чтоб не ебало мозг

**Comment by CoolCat467** [comment]
Думаю, я знаю, в чем проблема. Ключ API Яндекса отслеживает, сколько раз было использовано, и «превышает лимит в месяц» или что-то в этом роде.

en:
I think I know what the issue is. Yandex API key keeps track of how many times used, and "exceeds monthly limit" or something.

**Comment by IgorTimofeev** [comment]
Да какой лимит, блин, если они вообще отключили возможность некоммерческого использования для всех старых ключей? Плати денежку - и пользуйся. Увы, я слишком жмот, чтоб капиталистам монетки отсыпать за игровой проект 3х-летней давности. Фиг с ним, проще отключить автоперевод
