### ISSUE TITLE
Issue with launching mineOS

### ISSUE THREAD

**Issue by chevysixgaming** [IgorTimofeev/MineOS#286]
I am having an issue where i convert the image in the program, when i copy the .pic file into the disk then after that when i power on the OP computer it won't go on I can't remember if i am missing a step,

**Comment by chevysixgaming** [comment]
it appears when i close the saved world and open it again mineOS bugs out the computer and i have to install mineOS everytime, im guessing on a server it wouldn't do this might be only single player, im a see if it works

**Comment by IgorTimofeev** [comment]
Meow, are you sure that your pic size is lesser than available space on OC HDD? Manual copying to saves/opencomputers/hdd folder comes without checking free space on mod side

**Comment by chevysixgaming** [comment]
i did a test and all i did was install mineOS and then exit game and re-entered it and the mineOS won't boot up unless i reinstall mineOS on a fresh drive, i was able to put the .pic files on a seperate disk drive in minecraft so after i install mineOS i just mount it and before i log off i pull the drive after its powered off, next time i log in i just remount it,

**Comment by chevysixgaming** [comment]
i did also make sure that the contents of the folder for the drive didn't go over 4MB

**Comment by IgorTimofeev** [comment]
So no errors? No info on screen? Just "no booting" without some "beep" or something? I rather can't help you without such stuff. I can only make senseless guesses

**Comment by chevysixgaming** [comment]
when i load mineOS in session it works fine, then when i quit the server/saved world and rejoin, when i power on the computer the mineOS white background appears for a second then shuts off right away.

also curious how big to make each screen, before you showed me an example but i can only 11 of the screens to show up the rest stay black

**Comment by chevysixgaming** [comment]
[https://imgur.com/undefined](url)

**Comment by chevysixgaming** [comment]
[https://imgur.com/iShJYR9](url)

**Comment by IgorTimofeev** [comment]
Maybe OS just switches to first available screen from list after logout for some reason? The "primary" screen has equal "rights" with others. Have you tried to unplug "other" screens except "primary" and rebooting instead of reinstalling OS?

I don't remember if MineOS has a feature of "remembering" the "primary" screen address in settings, it has been long time ago. And, probably, if you exit the game while drawing in MultiScreen app, then even with this feature, the address will be erased from memory.

You can draw your image using MultiScreen app on "primary" screen, disconnect screens array from rack (but keep them powered on), and everything should be fine

**Comment by chevysixgaming** [comment]
how do I add more power to the screens?

**Comment by chevysixgaming** [comment]
run more cables from a power source or a computer case or something that is powered? cause the rack has 5 faces that can be wired

**Comment by IgorTimofeev** [comment]
More power sources (i've used one MFU attached to each screen), more power converters (depends on mod/game versions). Just play around

**Comment by chevysixgaming** [comment]
i added a bunch of creative computer cases without any internal components attached them to the cables around until the screens all lit up then swapped it out for power distributors and convertors

**Comment by chevysixgaming** [comment]
[https://imgur.com/PW910Q8](url)

**Comment by chevysixgaming** [comment]
link to it now it shows up on the whole screen array thank you, i also noticed if i disconnect the array before turning on the PC then it doesn't make one of the random screens the primary

**Comment by IgorTimofeev** [comment]
Of course it doesn't. This is the only way how MultiScreen should be used. Nothing to fix here
