### ISSUE TITLE
скроллбар неверно показывает половинку

### ISSUE THREAD

**Issue by arduinka55055** [IgorTimofeev/MineOS#289]
Или я хуй, или вы облажались.
короче, вызываю эту штуку, и на полоске прокрутки нет ползунка, если он "пополам":
local verticalScrollBar = window:addChild(GUI.scrollBar(window.width, 1, 1, window.height, 0x333333, 0x999999, 0, 1 , 0, 1, 1, false))

указано 0 и 1, тоесть 2 значения. и оно выглядит так:
[![https://imgur.com/8p6i5lg.png](https://imgur.com/8p6i5lg.png)](https://imgur.com/8p6i5lg.png)
(нажал в самый край и это видно с алерта)

если сделать 3 и больше значений, то оно работает, и серая фигня есть

помогите, заранее спс

**Comment by arduinka55055** [comment]
при этом оно мотает нормально, в 2 положения, колесиком и нажатием тоже
но отображение неправильное

**Comment by IgorTimofeev** [comment]
Как нет ползунка-то, если он есть? На скрине ползунок растянут на всю полосу прокрутки, цвет 0x999999 тому в подтверждение. Ты ж, бля, сам скроллбару выставил значения maxValue = 1 и shownValueCount = 1. Значение shownValueCount должно быть всегда <= maxValue, иначе ты получишь полностью закрашенный скроллбар. Размер "передвигаемой шняги" рассчитывается в рантайме по формуле:

```lua
ceil(shownValueCount / (maxValue - minValue) * height)
```

 В твоём случае я юзнул 0.25 - и все заебок:

```lua
local GUI = require("GUI")
local system = require("System")

---------------------------------------------------------------------------------

local workspace, window, menu = system.addWindow(GUI.filledWindow(1, 1, 60, 20, 0xE1E1E1))

local text = window:addChild(GUI.text(2, 4, 0x2D2D2D, "Sosi pisos"))
local scrollBar = window:addChild(GUI.scrollBar(window.width, 1, 1, window.height, 0x333333, 0x999999, 0, 1 , 0, 0.25, 0.25, false))

scrollBar.onTouch = function()
	text.text = "Scrollbar value: " .. scrollBar.value
end

---------------------------------------------------------------------------------

workspace:draw()
```

Пруф:
![image](https://user-images.githubusercontent.com/11760002/100042706-14a1a800-2e1d-11eb-85d5-50947b886a2b.png)

**Comment by arduinka55055** [comment]
От оно что. Не до конца понял зачем shownValue нужен. Спасибо вам!
Ща пойду дальше допиливать прогу
