### ISSUE TITLE
Проблема с подключением экранов

### ISSUE THREAD

**Issue by lartyom** [IgorTimofeev/MineOS#290]
Как можно подключить дополнительные экраны в "Multiscreen", если он видит только один?

**Comment by IgorTimofeev** [comment]
Подрубаешь основной экран, запускаешь прогу. Подрубаешь остальные экраны. Калибруешь экраны в проге, рисуешь пикчу. Отключаешь контроль (но не питание) остальных экранов, кроме основного

**Comment by lartyom** [comment]
> Подрубаешь основной экран, запускаешь прогу. Подрубаешь остальные экраны. Калибруешь экраны в проге, рисуешь пикчу. Отключаешь контроль (но не питание) остальных экранов, кроме основного

Другим основным экраном управлять неудобно

**Comment by IgorTimofeev** [comment]
Ну щито поделать, пиши собственную прожку так, как  будет удобно
