### ISSUE TITLE
codedoor

### ISSUE THREAD

**Issue by EVRICA** [IgorTimofeev/MineOS#291]
Программа CodeDoor отсутствует как на рабочем столе операционки, так и в магазине приложений. Игорь, её пришлось выпилить из-за каких-то проблем?
Возможно ли эту програмку как-нибудь установить обычным смертным? Знаю, есть альтернатива
https://pastebin.com/au8YgTST
Но она не так хороша :)

**Comment by IgorTimofeev** [comment]
Она была написана на устаревшем API, которое более не поддерживается. Восстановить работоспособность на последней версии не составит особых проблем, но мне лично впадлу хд

**Comment by EVRICA** [comment]
Исходников не осталось?

**Comment by IgorTimofeev** [comment]
Осталось:
https://github.com/IgorTimofeev/MineOS/blob/71a02372a5d245fe0dd02261cb1b32d423bafde9/Applications/CodeDoor/CodeDoor.lua

Но сомневаюсь, что это шибко поможет. API этих уже не существует

**Comment by EVRICA** [comment]
❤

**Comment by EVRICA** [comment]
омагад, работает!
фикс на коленке

FIXED

if you want only CodeDoor without MineOS
follow instruction:

1. assemble tier3 PC (gpu tier3, monitor tier3 & so on... )
2. install OpenOS
3. cd to /lib dirrecrory and download ECSAPI.lua:
cd /lib
wget https://raw.githubusercontent.com/EVRICA/CodeDoor/main/ECSAPI.lua
to past links into opencomputers terminal hit "insert"
4. under /home dirrectory create "CodeDoor" folder by:
cd /home
mkdir CodeDoor
4. and create "Config.cfg" under /home/CodeDoor
cd CodeDoor
edit Config.cfg
Ctrl+s (save)
Ctrl+w (exit)
5. download "CodeDoor.lua" into "/home/CodeDoor/"
wget https://raw.githubusercontent.com/EVRICA/CodeDoor/main/CodeDoor.lua
Ctrl+s (save)
Ctrl+w (exit)
6. launch
CodeDoor

**Comment by IgorTimofeev** [comment]
Нихуево, я уж думал, не осталось трудолюбивых людей, способных восстановить код по кускам. Можно в маркет заливать <3
