### ISSUE TITLE
No servers showing up in drop down boxes, username not showing in top right, buttons not working, etc.

### ISSUE THREAD

**Issue by tlaskowskiiv** [IgorTimofeev/MineOS#294]
Hi there. I recently updated my MineOS webos to the latest version (after not knowing one could do that for multiple months). I am not saying correlation is causation, but it was only after updating that I began having this issue.

Now, whenever I log into the website created by MineOS's web server, there are multiple issues I can immediately see. Firstly, all drop down boxes who do not have hardcoded values show nothing in them. This includes the Currently Selected Server drop down box, the ID box in the Profiles tab, and the localization tab in the top right corner.

Additionally, my username is not showing up in the top right, where it normally should. It is interesting to note that in the Profiles tab, I am given the error `No profiles Are Available; Check Internet Connectivity And Refresh The Profile List.` Refreshing the profile list in the top right yields no results.

I am able to create servers, but once the server is created, it does not show up in the dropdown box, the down symbol is a gray check instead of a red x, and it does not show the max players, among other things. Accepting the EULA and attempting to start the server does nothing.

I have tried multiple methods of fixing this. I tried updating the webos on my original TurnKey install, resetting the webos on said install, creating an *entirely new* install of Ubuntu Server, and installing MineOS by hand, resetting the webos on the new install, and updating it on the new install as well. All of these have not changed things.

Is this a problem on my end? What should I do?

Here is an image of what I mean
![Screenshot 2020-12-14 224214](https://user-images.githubusercontent.com/47758739/102168129-b6854500-3e5d-11eb-8e90-3d5c49d6676b.png)

**Comment by IgorTimofeev** [comment]
Wtf is this shit? Wrong repo, bro

**Comment by ProjectHSI** [comment]
LOL
This is not the repo you're looking for.
To clear up confusion, there's actually two things called MineOS, they're both related to Minecraft.
This repo is related to the not-at-all standalone operating system for OpenComputers. A mod that adds computers to Minecraft.

This MineOS this OP is referring to is server software for running a Minecraft server, while this server could run MineOS (OpenComputers) this is clearly a configuration issue with the server software.
