### ISSUE TITLE
Не могу разобраться с filesystem 

### ISSUE THREAD

**Issue by aqua-s-team** [IgorTimofeev/MineOS#296]
Не могу сделать сохранение настроек своей проги.

![image](https://user-images.githubusercontent.com/60589309/102587872-27b74780-413f-11eb-917f-f643aa605541.png)

Выдает ошибку `system fatal error: not enough memory`
На скрине все расписал.

**Comment by IgorTimofeev** [comment]
Значит, таблица либо дохуя жирная, либо рекурсивная - и её сериализация невозможна без потери данных. По фразе "not enough memory" догадаться ж можно

**Comment by CoolCat467** [comment]
Также может быть нехватка места на жестком диске. IgorTimofeev, вероятно, прав, и это может быть что-то рекурсивно пытающееся сохранить.
кстати перевод наверное мусор

(There may also be a lack of hard disk space. Igor Timofeev is probably right, and it might be something recursively trying to preserve.)
(translation is probably trash by the way)
