### ISSUE TITLE
erreur d'installation 

### ISSUE THREAD

**Issue by GachaFan** [IgorTimofeev/MineOS#302]
![image](https://user-images.githubusercontent.com/71570182/102789593-a06b0d80-43a4-11eb-91b1-b73dea4a0ef3.png)
=(
(d'après FuzeIII (un youtubers de 1 million d'abo) c'est a cause que le serveur n'autorise pas l'installation, mais moi je joue en solo)

**Comment by PlanetExpressShip** [comment]
J'ai la meme erreure
I have the same error

**Comment by GachaFan** [comment]
ok, quand je quitte le monde sa dit "shutting down internal server" (et apparament sa bug car le serveur n'autorise pas l'installation et je ne sais pas comment on fait pour autoriser l'installation sur un serveur) (alors que je suis en solo =| )

**Comment by CoolCat467** [comment]
May be capitalization. #304 has a similar issue. It's "pastebin run 0nM5b1jU" exactly, no capitalization changes. See how the stack traceback in both situations says there was an error in "/bin/pastbin.lua"? That file is provided by OpenOS, not MineOS installer. Try again with correct capitalization, and if it fails again it might be something else.

**Comment by GachaFan** [comment]
> Peut être une capitalisation. [# 304](https://github.com/IgorTimofeev/MineOS/issues/304) a un problème similaire. C'est exactement "pastebin run 0nM5b1jU", aucun changement de capitalisation. Voyez comment le suivi de la pile dans les deux situations indique qu'il y a eu une erreur dans "/bin/pastbin.lua"? Ce fichier est fourni par OpenOS, pas par l'installateur MineOS. Essayez à nouveau avec une capitalisation correcte, et si cela échoue à nouveau, cela peut être autre chose.

Apparemment c'est un problème que le serveur "internal serveur" (qui est utiliser ne solo pour forge) bloque le téléchargement de mineOS pour éviter qu'on installe n'importe quoi sur le serveur. Mais moi je ne sais pas comment on fait pour autoriser le téléchargement

**Comment by GachaFan** [comment]
J'ai trouver une technique qui règle le problème et j'ai réussis finalement a installer totalement MineOS

https://user-images.githubusercontent.com/71570182/102926965-4ea2b000-4496-11eb-96dd-73e17dd82993.mp4

**Comment by GachaFan** [comment]
J'ai trouver une technique qui règle le problème et j'ai finalement réussis a installer totalement MineOS

https://user-images.githubusercontent.com/71570182/102927048-75f97d00-4496-11eb-98ca-b9715fed454e.mp4

**Comment by CoolCat467** [comment]
I really don't know if it's the internal server causing problems, but if anything maybe use the github install command.
