### ISSUE TITLE
Callback-метод :onResize не передает ссылку на окно

### ISSUE THREAD

**Issue by Gnog3** [IgorTimofeev/MineOS#303]
В документации GPU API -> GUI.window callback функция onResize указана через двоеточие, а также принимает два аргумента. Это означает, что еще должна быть передана ссылка на окно. Но на деле и в исходниках это не так.
https://github.com/IgorTimofeev/MineOS/blob/master/Libraries/GUI.lua#L2176

**Comment by IgorTimofeev** [comment]
А, таки нашёлся легаси-мусор... ну и хуй с ним. Сейчас фиксану доку, спасибо
