### ISSUE TITLE
I cant install it gives me an eror

### ISSUE THREAD

**Issue by PlanetExpressShip** [IgorTimofeev/MineOS#304]
![Screenshot 2020-12-20 203442](https://user-images.githubusercontent.com/65982287/102812111-7e698f00-4394-11eb-87f1-3126a2c17c78.png)

**Comment by CoolCat467** [comment]
You didn't type in the command correctly. It's "pastebin run 0nM5b1jU", not 0nm5b1ju. Capitalization is important.

**Comment by CoolCat467** [comment]
Interesting, #302 has something similar... Then again, capitalization was not done correctly there either...

**Comment by PlanetExpressShip** [comment]
still getting it
![Screenshot 2020-12-21 160244](https://user-images.githubusercontent.com/65982287/102821960-0a37e700-43a6-11eb-8713-7c0e60be4447.png)

**Comment by GachaFan** [comment]
apparament c'est un problème de serveur qui refuse d'installer (quand je joue sur forge en solo c'est un internal serveur)

**Comment by GachaFan** [comment]
j'ai une bonne nouvelle et une mauvaise, la bonne c'est que j'ai trouver une technique magic/miracle (qui marche pour moi) qui permet d'accéder a l'instalateur de mineOS et la mauvaise c'est que en plein milieu du téléchargement de mineOS il y a sa 
![image](https://user-images.githubusercontent.com/71570182/102923980-fae19800-4490-11eb-90a6-c7a277a8301a.png)

**Comment by GachaFan** [comment]
voici la vidéo qui montre ma technique 

https://user-images.githubusercontent.com/71570182/102927048-75f97d00-4496-11eb-98ca-b9715fed454e.mp4

**Comment by CoolCat467** [comment]
Interesting

**Comment by CoolCat467** [comment]
If anything maybe use the github install command instead of pastebin.

**Comment by CoolCat467** [comment]
@PlanetExpressShip I think issue can be closed now

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/106446833-ca2e4e80-6491-11eb-8ccc-f1a1f0c29167.png)
