### ISSUE TITLE
Camera app does not work

### ISSUE THREAD

**Issue by OverdueWeevil2** [IgorTimofeev/MineOS#314]
![image](https://user-images.githubusercontent.com/67264530/105071516-c5cb6400-5a95-11eb-9672-407297a6d804.png)

**Comment by IgorTimofeev** [comment]
Maybe you should attach the fucking camera from fucking computronix mod to your computer? xd

**Comment by OverdueWeevil2** [comment]
Where can I find the Computronix mod?

**Comment by IgorTimofeev** [comment]
In a galaxy far far away
