### ISSUE TITLE
Длина строки с неанглийскими буквами вычисляется неверно

### ISSUE THREAD

**Issue by Senliast** [IgorTimofeev/MineOS#315]
Доброе время суток, собственно название уже все говорит. Если в строке только английские буквы - длина
возвращается правильно, стоит написать русские - и уже неправильно, каждая русская буква считается за 2.
Пробовал и с str.width() и с string.len(str), одно и то же.
Что за говно? Час себе ломал голову почему строка не центрируется.
Можно это как-то исправить?

https://imgur.com/a/9s7ALYi

**Comment by Senliast** [comment]
P.S. кажется это происходит только если текст был изменён, т.е. другой, чем при создании объекта. Если текст не менять - считается правильно.

**Comment by IgorTimofeev** [comment]
@Senliast Потому что луа не может в юникод по дефолту, и вместо кол-ва символов в строке выдает кол-во байт в ней. Для длины строк юзай unicode.len из опенкомпов или utf8.len из Lua 5.3+
