### ISSUE TITLE
A new OS but not test.

### ISSUE THREAD

**Issue by cs-sugar** [IgorTimofeev/MineOS#316]
Who can help me test whether my secondary development system cloudcandyos based on mineos can run normally and stably? Installation code: 

    wget -f https://raw.githubusercontent.com/cs-sugar/CloudCandyOS-Minecarft-OpenComputers/master/Installer/BIOS.lua  && flash BIOS.lua && reboot

**Comment by cs-sugar** [comment]
In addition to the fact that I know there are some bugs in the App Store, can you check for bugs in other places for me.

**Comment by cs-sugar** [comment]
It is based on mineos in general.

**Comment by CoolCat467** [comment]
No, it's just a copy of the entire repository but changing any instance of "MineOS" with "CloudCandyOS" and redirecting all the links to that repository.

This is not an issue. This is advertising a bad copy of this OS.

**Comment by IgorTimofeev** [comment]
Dude...

![Без имени-1](https://user-images.githubusercontent.com/11760002/105413336-8bfe8700-5c68-11eb-8f9c-b1aa4d62bcc8.png)

**Comment by cs-sugar** [comment]
But during the installation, due to a bug in the app store, it can't be installed normally...

**Comment by cs-sugar** [comment]
> Dude...
> 
> ![Без имени-1](https://user-images.githubusercontent.com/11760002/105413336-8bfe8700-5c68-11eb-8f9c-b1aa4d62bcc8.png)

Well, I see.

**Comment by IgorTimofeev** [comment]
>But during the installation, due to a bug in the app store, it can't be installed normally...

Installer doesn't interfere with AppMarket API at all, wtf are you talking about? It's a non-required app that can be removed safely in repo forks
