### ISSUE TITLE
Who can make a software to control nanomachines with mineos?

### ISSUE THREAD

**Issue by cs-sugar** [IgorTimofeev/MineOS#317]
I ate a nano machine, but I don't know how to control it with mineos, who can make a software to control it easily.

**Comment by cs-sugar** [comment]
Who can?

**Comment by MrFredber** [comment]
mineos has a program in the appstore to control nanobots. it was created 2 years ago by the author of the os.

**Comment by CoolCat467** [comment]
Yes, this is true and I've used it myself.

**Comment by MrFredber** [comment]
...but this app is not easily controls nanobotes?

**Comment by cs-sugar** [comment]
Which program can be installed and run? Why didn't I see it?

**Comment by MrFredber** [comment]
Sorry. i've seen this app 2 years ago. It's called "Nanomachines"

**Comment by cs-sugar** [comment]
> Sorry. i've seen this app 2 years ago. It's called "Nanomachines"

Okey,I well test it.

**Comment by CoolCat467** [comment]
It works. I did it myself quite recently.

**Comment by CoolCat467** [comment]
This "issue" can be closed now I would think.

**Comment by IgorTimofeev** [comment]
@CoolCat467 
![image](https://user-images.githubusercontent.com/11760002/105785293-98961e80-5f8b-11eb-8c1f-d85b9bb913b1.png)
