### ISSUE TITLE
Who can write a program that can flash EEPROM and control the movement of UAVs, harvest crops, and go to the path point, and the firmware of UAVs?

### ISSUE THREAD

**Issue by cs-sugar** [IgorTimofeev/MineOS#318]
I need to use the UAV, but there is no graphical interface to control the UAV. I don't know which God can write a program that can be used to flash EEPROM, control the UAV to move, go to the path point and harvest crops, or even control the micro controller.

**Comment by CoolCat467** [comment]
I'm not doing that, and really you should do that yourself, but there was an old program for MineOS a long time ago that harvested crops with drones. Files can be found in the old "testBranch" : https://github.com/IgorTimofeev/MineOS/tree/testBranch/Applications/Drone%20farmer

**Comment by CoolCat467** [comment]
It probably doesn't work right anymore, but it should be a good to help you start doing what you want.

**Comment by CoolCat467** [comment]
This "issue" can probably be closed now.

**Comment by IgorTimofeev** [comment]
:()((9
