### ISSUE TITLE
What happened to some games on the MineOS? 

### ISSUE THREAD

**Issue by cs-sugar** [IgorTimofeev/MineOS#319]
When will there be games like floppy bird, angry birds, fruit cutting, chess, Plants vs. Zombies? I seem to have seen floppy bird in MineOS AppStore before, but now I can't see it.

**Comment by CoolCat467** [comment]
Development on MineOS stopped years ago. The only new changes are adding localizations and bug fixes. If you want your games, program them yourself. The GUI library isn't that hard to use compared to straight up controlling the screen.

**Comment by IgorTimofeev** [comment]
@cs-sugar, flappy bird was developed by my friend using old version of screen buffer library that is no longer part of standalone version of OS. He desn't want to re-code it. So @CoolCat467 is right, just write games yourself lol

**Comment by cs-sugar** [comment]
Can you give me the original floppybird source code?

**Comment by MrFredber** [comment]
XD. Flappy bird, not floppy bird

**Comment by MrFredber** [comment]
initially, the source code was on github, but the author deleted it.

**Comment by MrFredber** [comment]
Maybe you find it if you check the old commits

**Comment by cs-sugar** [comment]
Okey
