### ISSUE TITLE
Everyone can see your ip on IRC chat 

### ISSUE THREAD

**Issue by Ellie3231** [IgorTimofeev/MineOS#324]
is big ploblem Security  Everyone can see your reall  ip address
one guy tell me my reall  ip address they can kill me 
Im now very  scared  and dont use  IRC chat .

**Comment by kebufu** [comment]
很快就到你家门口

**Comment by 493505110** [comment]
开门，社区送温暖

**Comment by CoolCat467** [comment]
Can you explain the issue more in depth? What do you mean by "Everyone can see your real ip address"? People on the internet can lie you know. That sort of magor issue sounds like a problem from whatever IRC server you are connecting to. If this is real though, I would like more information on exactly what is happening so myself or other people smarter than me can fix it.

**Comment by snaildos** [comment]
How? Via disconnecting?

**Comment by TFTWPhoenix** [comment]
Hi, this is normal for IRC. Someone having your IP is not scary at all. All websites and internet services use your IP address to send data to and from your computer. IRC literally shows your IP next to your name when you join. If you are still uncomfortable with this a VPN is a good way to fix that.

**Comment by CoolCat467** [comment]
Issue can probably be closed now then, @Ellie3231

**Comment by kingofsponges** [comment]
this is an issue with the irc server, and not regarding the client.

this issue should be closed. if you do not feel comfortable with your ip being shown, look for a server that doesn't show user ips.

**Comment by ProjectHSI** [comment]
Bug is currently being tested --- Running Test IRC Server on a Ubuntu Virtual Machine server.

**Comment by ProjectHSI** [comment]
This is why you don't get lazy. Don't just abandon your comment after 10 DAYS. OOF.

**Comment by kingofsponges** [comment]
i said this is not a bug, rather an intended feature of most irc servers. so you either chat on servers that do not show user ips or connect with a vpn.

**Comment by Hatry1337** [comment]
инетернет не анонимен

**Comment by Smok1e** [comment]
xd
