### ISSUE TITLE
Bad Argument #3

### ISSUE THREAD

**Issue by INEEDCHATPROGRAAAAAMS** [IgorTimofeev/MineOS#331]
I installed it as you said, but immediately afterward, I got a Bad argument #3 error. I found the issue has something to do with the device's internet connection, but can't figure out anything past that.

**Comment by kebufu** [comment]
Are you live in China? If you live in China, you can use this mirror.
`wget -f https://mirror.opencomputers.ml:1337/MineOS/IgorTimofeev/MineOS/master/Installer/BIOS.lua /tmp/bios.lua && flash -q /tmp/bios.lua && reboot`

**Comment by GusarevKirill** [comment]
Is this issue active?

**Comment by MrFredber** [comment]
Yes

**Comment by GusarevKirill** [comment]
> Yes

Хуёво

**Comment by MrFredber** [comment]
Ага...
