### ISSUE TITLE
Вопрос по перехвату ошибок

### ISSUE THREAD

**Issue by MrFredber** [IgorTimofeev/MineOS#333]
Я делаю свою ОС и не понимаю, как сделать перехват ошибок? Пытался сделать сам через xpcall (не работало), посмотрел, как работает это у тебя и всё равно не понял.

**Comment by IgorTimofeev** [comment]
```lua
local result, reason = xpcall(функция, debug.traceback)
if result then
  --код выполнился успешно
else
  -- райтаймовая строковая ошибка reason
end
```

чиво(

**Comment by MrFredber** [comment]
Я то знаю про это, проблема в том, что у меня программы в ос запускается через os.execute, а она отслеживает только то, что программа запустилась, а ошибок не выдаёт.

**Comment by IgorTimofeev** [comment]
Разве os.execute не выдает false и причину ошибки в случае её наличия? А если нет, то разве почему бы не запускать софт через loadfile/xpcall?

**Comment by MrFredber** [comment]
Os.execute выдаёт ошибку только если файла не существует и ещё какая-то хрень. Я пытался вызывать os.execute через xpcall, но он не видел ошибки

**Comment by IgorTimofeev** [comment]
Вообще странная хуйня, т.к. os.execute - это алиас для shell.execute, а в доке shell сказано, что рантаймовые ошибки также отлавливаются:

![image](https://user-images.githubusercontent.com/11760002/112738246-31d4b780-8f72-11eb-9ee0-f181186688dd.png)

Если ни хуя не помогает, то не парься и заюзай чет тип такого:

```lua
if fs.exists(путь) then
  local result, reason = loadfile(путь)
  if result then
    result, reason = xpcall(result, "аргумент1", "аргумент2", debug.traceback)

    if not result then
      -- Рантаймовая ошибка
    end
  else
    -- Синтаксическая ошибка в файле
  end
else
  -- Файл отсутствует
end
```

**Comment by MrFredber** [comment]
попробовал сделать запуск через shell.execute.
При синтаксических ошибках функция ничего не выдаёт, а при реальных ошибках функция говорит, что всё ок:
(после shell.execute сразу идёт print)
![image](https://user-images.githubusercontent.com/33953266/112741420-e7722b80-8faf-11eb-91a0-29cf805a5182.png)

Попробовал твой способ (только без проверки на существование файла) и система говорит, что есть ошибка, хотя программа даже не запустилась:
![image](https://user-images.githubusercontent.com/33953266/112743102-90c01e00-8fbe-11eb-8979-21b8b7210000.png)

В функции я сделал стоп через event.pull("touch"), и после нажатия на экран я вижуэту прекрасную картину:
![image](https://user-images.githubusercontent.com/33953266/112743122-c06f2600-8fbe-11eb-869e-02586ea48736.png)

**Comment by MrFredber** [comment]
Update: я тупанул и забыл проверить, как вставляется в функцию путь к файлу.

Спасибо за помощь.

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/112754781-51a5c300-8fe6-11eb-920c-dd3da208cf24.png)
