### ISSUE TITLE
Перевод голосовых

### ISSUE THREAD

**Issue by gaussandhisgun** [IgorTimofeev/MineOS#335]
Я пока не разобрался с тем, как на гитхабе работают PR, но я только что улучшил клиент ВКонтакте для MineOS до такого уровня, что он стал в некотором смысле превосходить официальный ВК Мессенджер для всех платформ и браузерный ВКонтакте. Теперь (ну, если заменить Main.lua на мой) после голосового сообщения будет отображаться его перевод. В клиентах для ПК/Mac/Linux и в браузере этого нет до сих пор :р

https://github.com/gaussandhisgun/OpenComputersApps/blob/main/VK_voices/Main.lua
![2021-04-08_01 43 39](https://user-images.githubusercontent.com/63512006/113944855-e3df6f80-980d-11eb-8ffd-6c5643a43496.png)
![2021-04-08_01 48 02](https://user-images.githubusercontent.com/63512006/113944858-e5109c80-980d-11eb-87b2-94343b971cf0.png)

**Comment by IgorTimofeev** [comment]
Лул, не знал, что вк-приложуха ещё пашет, т.к. было дохуя жалоб на блокировку аккаунтов и вылеты :D

Спс, заберу фичу себе
