### ISSUE TITLE
error

### ISSUE THREAD

**Issue by krisz0** [IgorTimofeev/MineOS#339]
![Minecraft 1 12 2 2021 04 17  13_27_39](https://user-images.githubusercontent.com/82708433/115111538-211bce00-9f81-11eb-85c7-1c08749ffc5a.png)

**Comment by MrFredber** [comment]
This is the pastebin error. And this error exist for 7 months

**Comment by kebufu** [comment]
you can use `wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /tmp/bios.lua && flash -q /tmp/bios.lua && reboot`

**Comment by IgorTimofeev** [comment]
0nM5b1jU, not 0nm5b1ju, pastebin links become case-sensitive since 2021
