### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Domi299** [IgorTimofeev/MineOS#342]
I had a problem downloading MineOS into Minecraft, it wrote this text
Thanks!!
![Névtelen](https://user-images.githubusercontent.com/82725124/115122430-38c27900-9fb8-11eb-95fd-4852fb292f5b.png)

**Comment by IgorTimofeev** [comment]
If alternative installing method doesn't works - nothing to help you, sorry:

```lua
wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /tmp/bios.lua && flash -q /tmp/bios.lua && reboot
```
