### ISSUE TITLE
Невозможно установить MineOS

### ISSUE THREAD

**Issue by Senliast** [IgorTimofeev/MineOS#343]
После запуска установщика появляется ошибка "Unrecoverable error, computer halted". При следующем включении компьютера ошибка сохраняется, помогает замена BIOS на новый. "https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/Main.lua" возвращает 404, не найдено.

**Comment by Anntallex** [comment]
same

**Comment by IgorTimofeev** [comment]
Спасибо, псны, ща фиксану. Объебался сегодня с PR
