### ISSUE TITLE
own screensaver

### ISSUE THREAD

**Issue by samuelmill2003** [IgorTimofeev/MineOS#347]
i want own screensaver but i dont have good gif to lua converter. please help

**Comment by MrFredber** [comment]
Do you want a screensaver with a animation or what?

**Comment by IgorTimofeev** [comment]
> gif to lua converter

There's no such software yet for MineOS. You can be the pathfinder and develop your own format <3

**Comment by CoolCat467** [comment]
Trailblazer would be a more fitting word.

**Comment by IgorTimofeev** [comment]
> Trailblazer would be a more fitting word.

![image](https://user-images.githubusercontent.com/11760002/115383172-2f1a5a80-a1de-11eb-8894-6df20544269c.png)

**Comment by kebufu** [comment]
you can use Python language with `PIL` module to convert.

**Comment by CoolCat467** [comment]
Well, not to convert on its own, but definitely would be able to load in the images and allow you to convert them.

**Comment by kingofsponges** [comment]
> > gif to lua converter
> 
> There's no such software yet for MineOS. You can be the pathfinder and develop your own format <3

this is not an issue regarding mineos. gif to lua converters do not exist, as lua is a language used outside minecraft.
go on and try create your own. by now, close this issue.

**Comment by IgorTimofeev** [comment]
okay:(

**Comment by kingofsponges** [comment]
uh not you

i asked the author.

**Comment by kingofsponges** [comment]
you can reopen if you want

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/121783902-0a2cdd00-cbba-11eb-9f15-4e86ca43468d.png)

**Comment by kingofsponges** [comment]
haha

**Comment by Smok1e** [comment]
![image](https://github.com/IgorTimofeev/MineOS/assets/33802666/44532549-1223-43d0-9612-2fa32298f564)
