### ISSUE TITLE
Feature: a app that allows you to create apps and upload them in the apps store

### ISSUE THREAD

**Issue by Nikolas-500** [IgorTimofeev/MineOS#348]
...

**Comment by MrFredber** [comment]
If i correctly understood you, this feature exist in app store.

**Comment by MrFredber** [comment]
You just create an account and upload an app

**Comment by IgorTimofeev** [comment]
If you mean visual UI editor - nah, it's too ambitious for a opensource minecraft OS, and the benefits are doubtful. Why u no just use code-behind way to develop apps?

**Comment by CoolCat467** [comment]
Probably because new to lua and lua is weird in some ways; Takes time to learn intricacies.

**Comment by IgorTimofeev** [comment]
Wtf, lua is the most newbie frendly language in any ways and time saver

**Comment by Nikolas-500** [comment]
thanks

**Comment by Nikolas-500** [comment]
Thanks
