### ISSUE TITLE
A way to allow MineOS switch to OpenOS.

### ISSUE THREAD

**Issue by kebufu** [IgorTimofeev/MineOS#349]
https://user-images.githubusercontent.com/31839741/115956352-c5c47f80-a52e-11eb-813e-d46a1ce86b05.mp4

**Comment by 493505110** [comment]
我觉得可以在应用商店上传个软件，用这个软件来改MineOS

**Comment by MrFredber** [comment]
> 我觉得可以在应用商店上传个软件，用这个软件来改MineOS

In English, please

**Comment by IgorTimofeev** [comment]
No thanks, this will never be implemented. I adhere to the logic that operating systems should standalone with minimal mutual support. You can switch to OpenOS through BIOS in any time using Alt key and selecting boot volume
