### ISSUE TITLE
Scaling (see picture)

### ISSUE THREAD

**Issue by Malinicula** [IgorTimofeev/MineOS#350]
So i have tier 3 of every component and when i boot up mine os everything is huge. Is there ant way to adjust scaling or something
![Minecraft 1 12 2 25_04_2021 13_42_25](https://user-images.githubusercontent.com/77625868/115990482-2655ca00-a5cc-11eb-8a90-59ed460e408a.png)

**Comment by MrFredber** [comment]
Picture is kinda cursed.... Most likely your screen resolution is sets wrong

**Comment by MrFredber** [comment]
Check resolution settings in category "screen"

**Comment by Malinicula** [comment]
I used the auto scaling feature

**Comment by MrFredber** [comment]
That's why your resolution is small

**Comment by Malinicula** [comment]
it wouldnt let me set it any higher it would just reset to this resolution

**Comment by MrFredber** [comment]
You tried firstly turn off this function, and then change resolution?

**Comment by Malinicula** [comment]
yea like after i turned auto scaling off i set my resolution and nothing happened. And after reboot it reset to this res

**Comment by MrFredber** [comment]
Maybe you have a script, added in autostart, that resets the resolution?

**Comment by Malinicula** [comment]
Nope

**Comment by MrFredber** [comment]
Then use the recovery script. In installer type your previous username to save the data.

**Comment by IgorTimofeev** [comment]
Seems like you are using APU, not CPU. It has Tier 2 GPU

**Comment by ff66theone** [comment]
Yeah it already happened to me. but the main problem with tier two graphics is the **operations are 2x slower than tier 3** graphics. if I wanted, I could live with this on a tablet !
