### ISSUE TITLE
а

### ISSUE THREAD

**Issue by BrightYC** [IgorTimofeev/MineOS#354]
на форуме писал про прогрессбар, чинится изменением UIRequireTotal = 14

https://github.com/IgorTimofeev/MineOS/blob/master/OS.lua#L99

кстати тут еще фигня такая, короче:

![image](https://user-images.githubusercontent.com/28766913/119236847-41234c00-bb42-11eb-83c0-37bbf8132a13.png)

В чем прикол: я в фотошопе нарисовал короче иконку, а она там сохраняется каким-то новым OCIF, а маркет судя по всему только 6 и грузит, в итоге у меня на приложухе тупо File not exists весит(((

![image](https://user-images.githubusercontent.com/28766913/119236865-5bf5c080-bb42-11eb-802d-b36019725cbc.png)

При чем на раб столе она типо грузится, но в маркете - неа((

**Comment by IgorTimofeev** [comment]
> на форуме писал про прогрессбар, чинится изменением UIRequireTotal = 14

Спасибо, ща фиксану <3

> а маркет судя по всему только 6 и грузит

Бля, точно, про него забыл совсем, когда 7 формат релизил... держи еще

![image](https://user-images.githubusercontent.com/11760002/119238408-eb06d680-bb4a-11eb-8d3a-c4ae765b5e1c.png)

**Comment by BrightYC** [comment]
> Спасибо, ща фиксану <3
❤️

Тут такое дело, в GUI вообще есть какой-либо механизм фокуса на объект/контейнер? перерыл вообще весь код гуишки, не нашел ничего, кроме isScreenEvent. Проблема вот в чем:

![image](https://user-images.githubusercontent.com/28766913/119239620-0249c200-bb53-11eb-9db6-c104534dc577.png)

оно как то вще решается, или не?

**Comment by IgorTimofeev** [comment]
> Тут такое дело, в GUI вообще есть какой-либо механизм фокуса на объект/контейнер

Увы, нет, все контейнеры равноправны, и систему фокуса не завезли

**Comment by hohserg1** [comment]
А завезут когда-нить? Есть какие-то способы костылем это сделать? Например, для своей апки где-то хранить глобальную переменную со ссылкой на сфокусированное окно. Где лучше хранить такую переменную?

**Comment by IgorTimofeev** [comment]
Не завезут, т.к. на майн и майноську уже 2 года как насрать. А изначально не завезли, т.к. попросту не возникало потребности в такой фиче. А сфокусированное окно можно получить, покопавшись в сырцах Libraries/System.lua:

![image](https://user-images.githubusercontent.com/11760002/119246563-39d46080-bb8b-11eb-8839-b5b7b3155d35.png)

![image](https://user-images.githubusercontent.com/11760002/119246572-49ec4000-bb8b-11eb-92ca-761ebdc4b26f.png)

Поэтому следующего кода должно быть достаточно:

```lua
local windowsContainer = system.getWindowsContainer()
local focusedWindow = windowsContainer.children[#windowsContainer.children]
-- Делай чо надо с окном в фокусе
```

Ну а если недостаточно, то пiхуй, фиксов не будет))0

**Comment by IgorTimofeev** [comment]
@BrightYC Добавил нативную фокусировку окон через `GUI.focusedObject` при создании, удалениии и выборе окошек. Вдруг еще актуально
