### ISSUE TITLE
Банит ли все ещё ВК за использование клиента MineOS? 

### ISSUE THREAD

**Issue by ghost** [IgorTimofeev/MineOS#355]
Хотел спросить, блокировки за использования клиента ВК актуальны на данный момент?

**Comment by MrFredber** [comment]
А разве блокировка была при использовании клиента?

**Comment by SyberiaK** [comment]
> А разве блокировка была при использовании клиента?

Я так понимаю, что да.
![IMG_20210606_101053](https://user-images.githubusercontent.com/85413642/120913306-8e113180-c6af-11eb-86aa-dd8c5bc0a33f.jpg)

**Comment by HiPriv228** [comment]
Нет не банит

**Comment by Domaman202** [comment]
я даже войти блять не смог, о  чём вы

**Comment by misha99fr** [comment]
я тоже

**Comment by Smok1e** [comment]
как может банить за то, что не работает?)0
