### ISSUE TITLE
я срать хочу

### ISSUE THREAD

**Issue by Domaman202** [IgorTimofeev/MineOS#359]

**Comment by IgorTimofeev** [comment]
так сходи

![image](https://user-images.githubusercontent.com/11760002/122966128-9c3e9d80-d391-11eb-8e8a-cdcc80202b32.png)

**Comment by Domaman202** [comment]
мне нужно приложение "посрать" в MineOS

**Comment by MrFredber** [comment]
Чего бля? В дурку набирать?

**Comment by IgorTimofeev** [comment]
накодь!
