### ISSUE TITLE
How can I make MineOS run behind my Nginx reverse proxy with a subpath ?

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [IgorTimofeev/MineOS#361]
Hi,

I already have an Nginx reverse proxy server, that I use for my personal site, Organizr, Jellyfin, Sonarr, Radarr, Webmin, Transmission....
I would like to add MineOS to those services. But I would like to ask for help to do this, as MineOS doesn't provide any nginx config file (most server apps with webui do).

All my other apps require that I set a subpath in the app' settings. Here, I would like to tell MineOS to have a /mineos subpath. But I didn't find how to do that.

Then, I would be able to set a proxy pass in my Nginx config.

Could someone help me to do that ?
Any answer is welcome, have a great day

**Comment by IgorTimofeev** [comment]
> MineOS doesn't provide any nginx config file (most server apps with webui do).

Why do you think that MineOS is "server app with webui"? Are you sure you're in right repo? This repo represents homewritten OS in Lua for Minecraft OpenComputers mod

**Comment by CoolCat467** [comment]
@LeVraiRoiDHyrule Igor is correct, this is not the sort of software that would even support usage with Nginx.

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> > MineOS doesn't provide any nginx config file (most server apps with webui do).
> 
> Why do you think that MineOS is "server app with webui"? Are you sure you're in right repo? This repo represents homewritten OS in Lua for Minecraft OpenComputers mod
> 
> Maybe you mean [this](https://github.com/hexparrot/mineos)?

I just checked, and you're right: I am absolutely not in the right repo, I'm a total idiot. That's not at all the MineOS I though it was.
I was looking to post in the repo of this : http://minecraft.codeemo.com/

Sorry for disturbing!
Have a great day and sorry again!

**Comment by IgorTimofeev** [comment]
:D

No problem, bro
