### ISSUE TITLE
Unable to download any app (app market)

### ISSUE THREAD

**Issue by tt-thoma** [IgorTimofeev/MineOS#364]
Read the title
![image](https://user-images.githubusercontent.com/72872981/124135616-098ab680-da95-11eb-963c-d6ad5eb55071.png)

**Comment by IgorTimofeev** [comment]
Don't know about it, sorry. Maybe github.com is blacklisted on your server? Most apps are hosted here

**Comment by MrFredber** [comment]
You can't download any app, or you can't update them?

**Comment by tt-thoma** [comment]
Both

**Comment by tt-thoma** [comment]
Maybe forgot the `https://`

**Comment by tt-thoma** [comment]
> Don't know about it, sorry. Maybe github.com is blacklisted on your server? Most apps are hosted here

No, I installed MineOS correctly

**Comment by MrFredber** [comment]
Maybe the links in app market is corrupted

**Comment by tt-thoma** [comment]
Is there a way to see the underprocess / enter in a debug mode ?

**Comment by IgorTimofeev** [comment]
No, the "debug mode" is on your screen already, it tells you "invalid URL address". Why? Who knows. I'll add an output for the specific reason the request was not successful and update the internet library, but this is unlikely to help

**Comment by MrFredber** [comment]
Right now the internet library updated. As I understood correctly, now you may have a detailed error. Try to update this library manually and recreate this problem.

**Comment by tt-thoma** [comment]
Uuuh my "Paths" library is missing
Gonna reinstall...

**Comment by tt-thoma** [comment]
Nope.
Invalid URL-Adress

**Comment by tt-thoma** [comment]
Wait the computer is missing librairies because I tried to update them

**Comment by tt-thoma** [comment]
"unsupported protocol"

**Comment by tt-thoma** [comment]
![image](https://user-images.githubusercontent.com/72872981/124280113-5932b600-db59-11eb-92cf-1d9fed4280cc.png)
That is excactly what I was thinking about...
(This is an external bug)

**Comment by tt-thoma** [comment]
If you wondering I'm using [OCemu](https://github.com/zenith391/OCEmu) to get infinite RAM and when I compile it it don't compile the https socket handler
I added dlls and it worked but not completly I see

**Comment by CoolCat467** [comment]
OCemu is sort of notorious here for not working quite right in most cases.
