### ISSUE TITLE
MineOS features such as apps or settings crashing instantly with LUA errors?

### ISSUE THREAD

**Issue by AngelSimmer64** [IgorTimofeev/MineOS#368]
Hi there, MineOS works fine for me except for when I go into the appstore or anything, it always fades into a LUA error string? I can't unfortunately use any apps or the finder or appstore app?

**Comment by MrFredber** [comment]
Stupid questions: you rebooted your pc? have you tried reinstalling the system?

**Comment by AngelSimmer64** [comment]
Yes I have, I’ve reinstalled it all and wiped hard drives etc and started over, changed LUA, watched YouTube videos and everything. I’m at a bit of a loss unfortunately

**Comment by IgorTimofeev** [comment]
> when I go into the appstore or anything, it always fades into a LUA error string

Every time I honestly don't understand why people are complaining about the errors WITHOUT FUCKING SCREENSHOT OR ERROR TEXT

**Comment by MrFredber** [comment]
Same.

**Comment by CoolCat467** [comment]
It is immensely difficult to diagnose errors when one does not even know what the error is.

**Comment by AngelSimmer64** [comment]
My apologies I didn’t attach the screenshot, I thought that it did attach. When I get home from work today I’ll send it over.

**Comment by unkown367** [comment]
is it the  topmostwindow : focus ( ) error?

![2021-07-12](https://user-images.githubusercontent.com/87345729/125372972-489cef80-e352-11eb-9640-bcee8d275352.png)

**Comment by AngelSimmer64** [comment]
> is it the topmostwindow : focus ( ) error?
> 
> ![2021-07-12](https://user-images.githubusercontent.com/87345729/125372972-489cef80-e352-11eb-9640-bcee8d275352.png)

Yes it’s this! I barely can do anything without it popping up

**Comment by CoolCat467** [comment]
You will likely have to update all system software to the newest version, as a major change happened quite recently involving the way the GUI library works with the focused window. If update fails software may have to be modified.

**Comment by IgorTimofeev** [comment]
Weird error, it happens mostly on partially updated computers, but now I'm not sure

@AngelSimmer64, in your case you should perform global system update in AppMarket. If you can't do it because of window focusing error, you can reinstall system without HDD formatting (installer will overwrite main libraries)

**Comment by AngelSimmer64** [comment]
@IgorTimofeev I can't get past clicking on the app store, it just brings up the topmosterror window, even if I click settings or anything - can you tell me more or direct me to any information regarding installing mineOS again without HDD formatting? Thank you so much.

**Comment by CoolCat467** [comment]
@AngelSimmer64 I would assume just running the installer, but I'm not certain. Just in case, if I were you I'd make a backup of my system by having MineOS on another small hard drive, mount the main drive, and move everything important to something like a floppy so that in the event something goes wrong nothing is lost.

**Comment by AngelSimmer64** [comment]
I haven't got anything on there that I care about, I used a pastebin link to run an installation for MineOS but left it at that after installing openOS initially on the floppy disk

**Comment by MrFredber** [comment]
You just need to run the installer and set the username that you have in the system. But some settings maybe resets.

**Comment by IgorTimofeev** [comment]
Fixed that stupid error, sorry for wasting your time
