### ISSUE TITLE
Questions with System GUI

### ISSUE THREAD

**Issue by MrFredber** [IgorTimofeev/MineOS#376]
I have a questions with GUI (not library):

1) Should the colors of the sliders be red?
![image](https://user-images.githubusercontent.com/33953266/127011187-accb9946-d8db-4943-acab-ebfd01d02587.png)

2) Why interface transparency doesn't work without interface blurring?
![image](https://user-images.githubusercontent.com/33953266/127013518-7ca71cd1-54e7-4224-856a-dc71698db913.png)
![image](https://user-images.githubusercontent.com/33953266/127013618-eb4debc6-e1bc-4ac0-b9f9-5e4695895f14.png)

P.S. Sorry for russian text on screenshots. I'm lazy to switch the language :3

**Comment by IgorTimofeev** [comment]
Да лан, все мы русские))0

1. Да, я по приколу добавил красный цвет слайдерам, оказывающим дохуя влияния на производительность
2. Потому что прозрачность работает только с отдельными типами виджетов (верхняя менюшка, док в нижней части и контекстное меню), а приложения типа проводника и настроек эту опцию игнорируют. Почему? Да хз, мне прозрачность там не нужна была - вот и не стал реализовывать поддержку. Хотя в теории это не составит труда, так что могу и добавить

**Comment by MrFredber** [comment]
Но как опция для настройки дизайна под себя эта вещь нужна, так как я помню у тебя раньше была такая штука, а потом ты её выпилил + не всем может понравится блюр, как у Windows или MacOS, хотя вещь выглядит неплохо :3

Кароч, добавь плиз)

**Comment by IgorTimofeev** [comment]
Выглядит хуево, потому что текст серый в проводнике, и сливается. Надо добавлять доп. слайдеры по прозрачности панелек тогда уж, а также слайдеры по радиусу блюра. Мне оч лень(

**Comment by CoolCat467** [comment]
So issue is that it's difficult to modify localization files once in place?

**Comment by MrFredber** [comment]
@CoolCat467 No, issue is that it's difficult to implement effects customisation

@IgorTimofeev а где у тебя в приложениях находится переменные настройки блюра? Просто я делаю свою оську и в вашу библиотеку GUI не вчитывался

**Comment by IgorTimofeev** [comment]
> а где у тебя в приложениях находится переменные настройки блюра

Вообще они должны быть в методе system.getUserSettings(), но я не уверен, что вообще их туда пихал. Возможно, радиусы и прочее просто захардкожены в system.lua
