### ISSUE TITLE
Error when installing MineOS

### ISSUE THREAD

**Issue by LuckyGamer111** [IgorTimofeev/MineOS#378]
As soon as I run the command to download and run the file from Pastebin, it does nothing and throws this error
![error](https://user-images.githubusercontent.com/87702792/128947122-ca6c9783-b17e-4bb6-99d4-e7eb23bb3385.png)

if you're wondering im running a tier 3 GPU, tier 2 internet card, tier 2 wireless network card, tier 3 CPU, 2x Tier 3.5 RAM and a tier 3 hard disk with OpenOS on it, no floppies inserted
i havent tampered with the OS or even touched a file on that computer

**Comment by LuckyGamer111** [comment]
used the other link directly from github and it worked, sorry

**Comment by IgorTimofeev** [comment]
Maybe this was because of pastebin links become case-sensitive since Jan 2021. Btw thanks for reply

**Comment by MrFredber** [comment]
Problem in characters. Now since 2020 pastebin is case sensitive and you need to write "0nM5b1jU"
