### ISSUE TITLE
Бля я пороль от APPMARKET-а забыл чё делать

### ISSUE THREAD

**Issue by Domaman202** [IgorTimofeev/MineOS#381]
я в рот ебал, я пороль от APPMARKET-а забыл, ебаните на почту мне его пж

**Comment by Domaman202** [comment]
почта - vip.domaman@mail.ru
ник - domaman202
пороль - *а я чё блять помню*

**Comment by IgorTimofeev** [comment]
Дык на почту тебе пасс присылается же, плюс есть фича восстановления. Сам справляйся

**Comment by DartPower** [comment]
🤣

**Comment by Domaman202** [comment]
у меня на почти 20к сообщений 
как я тебе блять его найду

**Comment by Domaman202** [comment]
21к*

**Comment by Domaman202** [comment]
![image](https://user-images.githubusercontent.com/51743763/130378837-9b76b00b-7fee-4be8-a2bf-c7e4a782fc2f.png)
бля

**Comment by Domaman202** [comment]
> Дык на почту тебе пасс присылается же, плюс есть фича восстановления. Сам справляйся

ГДЕБЛЯТЬ

**Comment by IgorTimofeev** [comment]
> у меня на почти 20к сообщений
как я тебе блять его найду

Поиском, блядь

> ГДЕБЛЯТЬ

В маркете, блядь

**Comment by Domaman202** [comment]
![image](https://user-images.githubusercontent.com/51743763/130452760-711e18dc-3abf-4245-aedf-190263933c79.png)
где блять в твоём ёбаном маркете эта хуйня

**Comment by IgorTimofeev** [comment]
> где блять в твоём ёбаном маркете эта хуйня

Упс, выпилили))0
Тады саси и пиздуй на почту искать по отправителю пасс
