### ISSUE TITLE
[BUG] GUI libaray shows openos console on using it self (without mineos)

### ISSUE THREAD

**Issue by thegame4craft** [IgorTimofeev/MineOS#388]
When i try to draw a image using 
```lua
local img = image.create(160, 50, 0x000000, 0x000000, 0x00, " ", true)
workspace:addChild(gui.image(1, 2, img))
```
then openos shows its terminal and the programm exists. if i comment out the `workspace:addChild(...)` line everything works perfect. I know that the gui (and other libarays) are written for mineos, but i wanna to make a openos-desktop and don't want to write my own. 

If you need the full code, please write it.

p.s There are no lua errors.

**Comment by IgorTimofeev** [comment]
If you consider yourself competent enough to port libraries from one OS to another, then you are able to solve this issue on your own. How the fuck am I supposed to figure out what went wrong in **your** library version? 

> If you need the full code, please write it

If you need a fix, please WRITE IT LoooooL

**Comment by CoolCat467** [comment]
@thegame4craft If this is indeed for another project, please close this issue. It does not appear to affect MineOS users.

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/133271447-092f23a1-2e32-4f53-a9ea-d72dab4bf155.png)
