### ISSUE TITLE
Lol, 103%

### ISSUE THREAD

**Issue by MrFredber** [IgorTimofeev/MineOS#389]
Hmmmmm :D

https://user-images.githubusercontent.com/33953266/132866507-5baa0074-76b2-400e-a736-2c66f9a112d3.mp4

**Comment by IgorTimofeev** [comment]
Во глазастый, а! Спасибо, исправил <3

https://github.com/IgorTimofeev/MineOS/commit/ceb8b40136133cdafcad3e137c2df8dc03137e8a
