### ISSUE TITLE
can not install MineOS

### ISSUE THREAD

**Issue by Mcletsplay002** [IgorTimofeev/MineOS#394]
get this error after downloading
![2021-09-26_17 09 27](https://user-images.githubusercontent.com/75625792/134813568-c5f22bc3-43e4-45d5-bc00-dfcc5cb00cdb.png)
my components
![2021-09-26_18 01 27](https://user-images.githubusercontent.com/75625792/134815261-9a3bc9fb-470f-46d7-935c-ea55ae13df01.png)

**Comment by Domaman202** [comment]
rewrite eeprom

**Comment by Mcletsplay002** [comment]
with what should I rewrite it

**Comment by PublicVoidUpdate** [comment]
Using a open manual, then rerun the MineOS command

**Comment by Mcletsplay002** [comment]
culd you say me what open manual is please

**Comment by PublicVoidUpdate** [comment]
When you make a eeprom with lua bios you use the open computers manual. It's a part of the main mod

**Comment by Mcletsplay002** [comment]
https://youtu.be/pG4HO9VIQ3Q
can you lock at this video thats my problem

**Comment by IgorTimofeev** [comment]
@Mcletsplay002 seems like bios currupts while running installer scrinpt. Maybe pastebin.com sends some weird data to you. Did you tried another installing method?

![image](https://user-images.githubusercontent.com/11760002/134969762-0e73c690-40f3-466f-a69e-6995a03ba374.png)

**Comment by Mcletsplay002** [comment]
yes same error

**Comment by Mcletsplay002** [comment]
https://youtu.be/Hb01mPqTgkg

**Comment by IgorTimofeev** [comment]
Not same, hehe. It gives info about missing ssl certificate in java vm truststore:

![image](https://user-images.githubusercontent.com/11760002/134973662-735eb5a5-6f5d-4518-b7bb-c407eca97082.png)

You can try fix on client/server side:
https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

**Comment by Mcletsplay002** [comment]
thanks but i dont know how to fix it

**Comment by Mcletsplay002** [comment]
I gave up
