### ISSUE TITLE
MineOS crashing when booting from another bootloader

### ISSUE THREAD

**Issue by MiguelEXE** [IgorTimofeev/MineOS#396]
MineOS crash when loading OS.lua from another bootloader
![image](https://user-images.githubusercontent.com/52385139/135784456-76245367-df24-4cb3-af85-3844ab785c0f.png)
**Note:** the bootloader does not send any arguments to OS.lua

**Comment by MrFredber** [comment]
How did you know that you have a different loader if the MineOS loader is visible in the picture?
And check if the "Paths" library is in its place or not

**Comment by MiguelEXE** [comment]
> How did you know that you have a different loader if the MineOS loader is visible in the picture? And check if the "Paths" library is in its place or not

Im creating another bootloader.
the bootloader set computer.getBootAddress to the address where MineOS is located, then load the OS.lua file

**Comment by MiguelEXE** [comment]
btw the bootloader dosent pcall the load function (so the error of MineOS goes directly to MineOS EFI)

**Comment by MiguelEXE** [comment]
https://user-images.githubusercontent.com/52385139/135930369-3e8f138e-a999-45d1-935b-c46096e56376.mp4

the error happening in the bootloader.
