### ISSUE TITLE
mineos is broken

### ISSUE THREAD

**Issue by thefurrywolf** [IgorTimofeev/MineOS#397]
![Screenshot (7)](https://user-images.githubusercontent.com/81545837/140592465-9f16f39a-065b-4634-9ef1-739c0d54da0f.png)

**Comment by MrFredber** [comment]
No is not. MineOS Working ONLY on tier 3 computers with tier 3 components.

**Comment by SashaTalk** [comment]
Issue should be closed?

**Comment by MrFredber** [comment]
Yep

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/147836949-f3c035e1-4f04-472b-87c7-a0361bfbe124.png)
