### ISSUE TITLE
Gui Error while booting up

### ISSUE THREAD

**Issue by Redtimmystone** [IgorTimofeev/MineOS#398]
Hi,
i used Mineos with my friends before a lot but now i always get the same error even when i change every component of the pc.
![Screenshot 2021-11-06 104939](https://user-images.githubusercontent.com/93820205/140605461-507b794a-ee7a-47af-8f58-646cd6e6c28c.png)

**Comment by MrFredber** [comment]
This is a library bug. Try to change eeprom to the original by mod OpenComputers and reinstall system
