### ISSUE TITLE
библиотека web

### ISSUE THREAD

**Issue by makarhuyaker** [IgorTimofeev/MineOS#402]
она есть гдето? типо https://raw.githubusercontent.com/IgorTimofeev/OpenComputers/master/lib/web.lua не существует и из репозитория все удалено

**Comment by IgorTimofeev** [comment]
https://github.com/IgorTimofeev/MineOS/blob/master/Libraries/Internet.lua

Веб была просто альт. названием для интернет-либы, т.к. на момент плотной интеграции с опеносью она конфликтовала с местной интернет-либой. Сейчас майноська сама по себе, поэтому интернет

**Comment by makarhuyaker** [comment]
ясно
