### ISSUE TITLE
pastebin run 0nm5b1ju not working

### ISSUE THREAD

**Issue by Brazenpo34** [IgorTimofeev/MineOS#405]
I don't know why maybe I'm this stupid but when I enter pastebin run 0nm5b1ju, that's not working and sent me this message in the console and in red:

/bin/pastebin.lua:28: https://pastebin.com/raw/0nm5b1ju:
stack traceback:
   [C] : in function 'error'
   /lib/internet.lua:51: in function 'for iterator'
   /bin/internet.lua:28: in function 'get' 
   /bin/pastebin.lua:60: in function 'run' 
   /bin/pastebin.lua:141: in main chunk
   (... tail calls... )
   [C] : in function xpcall'
   machine:798: in function 'xpcall'
   /lib/process.lua:63: in function </lib/process.lua:59>

I'm using Open computer in the latest version of 1.10.2 minecraft. I have all required components and can't find the problem. Please help 😭

**Comment by IgorTimofeev** [comment]
`0nM5b1jU`, not `0nm5b1ju`, it's case sensitive
