### ISSUE TITLE
infopanel

### ISSUE THREAD

**Issue by Day16may** [IgorTimofeev/MineOS#407]
Здравствуй, недавно открыл для себя данный мод, и был приятно удивлен возможностями майнкрафта, на сколько он вырос 
Но суть в другом, открыл я этот мод как и многие благодаря тебе, начал смотреть обзоры/гайды и наткнулся на InfoPanel
сразу влюбился в интерфейс и возможности, но увы пролистав 10 страниц магазина приложений так его и не нашел, не мог бы ты залить его туда, либо подсказать где его взять, думаю по обзорам смогу поставить, если это конечно не запрещено в целях сохранения прав

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/148244557-30224f09-4c17-4fb6-8c6f-6cda0c5aafd5.png)
