### ISSUE TITLE
GUI API - Standalone usage

### ISSUE THREAD

**Issue by Yldales** [IgorTimofeev/MineOS#409]
Hello,

Is it still possible to use the [GUI API](https://github.com/IgorTimofeev/GUI) without MineOS (on OpenOS) ?
Importing MineOS's libraries into `/home/lib` and using `local GUI = require("GUI")` inside a .lua script throw the following error:

```
/lib/package.lua:64: module 'GUI' load failed:
/lib/package.lua:64: module 'Screen' load failed:
/home/lib/Screen:15: attempt to index a nil value (global 'unicode')
```

Sorry if this question is trivial. 
Thanks in advance.

**Comment by IgorTimofeev** [comment]
> Is it still possible to use the GUI API without MineOS (on OpenOS)

No, it's deeply integrated to MineOS. Only old version can be used (without any support, ofc)

**Comment by Yldales** [comment]
Fine, thanks :)
