### ISSUE TITLE
При удалении нет прогресса

### ISSUE THREAD

**Issue by SashaTalk** [IgorTimofeev/MineOS#410]
Привет. При копировании файлов появляется затемнение, и пишется что копируется. При удалении такого нет.
Контекстное меню, виджеты вверху, время и прочие процессы останавливаются до окончания удаления
![2022-01-08_16 50 42](https://user-images.githubusercontent.com/76222964/148646703-ecc7eeab-797c-447e-aa3e-9f577f6f4e56.png)

**Comment by IgorTimofeev** [comment]
Дык оно же мгновенное, че там отображать? fs.remove для папок работает как единая операция же, не?

**Comment by SashaTalk** [comment]
> Дык оно же мгновенное, че там отображать? fs.remove для папок работает как единая операция же, не?

Нене, я папку удалял. Может потому что много подпапок было? Да и папка весила что-то около мегабайта.

**Comment by IgorTimofeev** [comment]
Дык удаление папок мгновенное в опенкомпах, оно не требует рекурсивной переборки всех вложенностей. Я мог бы сделать прогресс, но нахуя, если эт только замедлит систему искусственно

**Comment by SashaTalk** [comment]
Попробовал в локальном мире, папки и вправду удаляются мгновенно. Значит с сервером проблема
