### ISSUE TITLE
GeoScan2

### ISSUE THREAD

**Issue by armdn** [IgorTimofeev/MineOS#413]
Will be GeoScan2 available in new version of MineOS? It is useful for my space station in GC.

**Comment by IgorTimofeev** [comment]
No, unless someone will port it from old MineOS versions 

![image](https://user-images.githubusercontent.com/11760002/152270594-ef6b10aa-0c68-4a88-ab6b-5c13dd0eeca7.png)

**Comment by Smok1e** [comment]
![image](https://github.com/IgorTimofeev/MineOS/assets/33802666/9f7fcbb1-9b75-43fa-a48b-514c706e16b6)
