### ISSUE TITLE
running minecraft commands in minecode IDE

### ISSUE THREAD

**Issue by polrbare** [IgorTimofeev/MineOS#414]
i was attempting to create a program that would take user inputs from text boxes in a gui and build a command with it and run it, while i am fairly confident with getting the gui together, im not sure how to execute commands in the IDE, i was thinking like how a command block would run the commands at the location of the block, however i cant seem to find any information about this, im hoping its possible to run commands from minecode. if anyone knows, that would be awsome

**Comment by IgorTimofeev** [comment]
> how to execute commands in the IDE

What do you mean by IDE commands & running them from minecode?

**Comment by polrbare** [comment]
like, on the default mineOS program "minecode" i dont know if its possible to run normal minecraft commands from the computer through code like "/gamemode creative" i have a debug card in, i just dont know how to actually tell it to execute commands.

**Comment by MrFredber** [comment]
try to create an input and send everything you get at the input to the debug card with the command debug.runCommand([string from input])
P.S. debug = require("Component").debug

**Comment by MrFredber** [comment]
This is from official documentation: https://ocdoc.cil.li/component:debug?s[]=debug&s[]=card

**Comment by Bumer-32** [comment]
это нужно закрывать

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/197504230-bf536e13-5ad9-4a69-9dc9-eb001d2c3078.png)
