### ISSUE TITLE
app store server is ded

### ISSUE THREAD

**Issue by lis0** [IgorTimofeev/MineOS#415]
yeah

**Comment by AleksanderPVP** [comment]
Confirmed. App Store server dead. Can't connect from Exaroton server or a singleplayer world.

**Comment by ti-bone** [comment]
Domain is died and selling for 40k rubles

![image](https://user-images.githubusercontent.com/59691680/159461785-1eb385db-a6c5-4e73-bf6f-8055a1e5d67a.png)

And WayBack Machine not archieved it

![image](https://user-images.githubusercontent.com/59691680/159461988-86742eda-2bfc-491d-a3e3-a5c01192fc83.png)

**Comment by IgorTimofeev** [comment]
No backups, server is private and not available to perform any backups

**Comment by MrFredber** [comment]
Press F to pay respect...
Now you know, that everything in your life needs to backup.
Goodbye all community work.....

**Comment by IgorTimofeev** [comment]
> Now you know, that everything in your life needs to backup

Nah, I just don't care about stuff like that. Dead? Ok, it wasn't something important anyway

**Comment by MrFredber** [comment]
On this screenshot some dude already brought this domain?

**Comment by IgorTimofeev** [comment]
Idc really. Domain owner is my friend, he gave me access to 2nd level name for AppMarket stuff. If domain is dead - ok  ¯\\\_(ツ)\_/¯
The server itself is located in St. Petersburg on a tiny single-board pc without public ssh/db access. I'm far away from home in siberia, the trip was planned for a couple of weeks, but in the end it dragged on for six months. So no fixes, no backups, no care

**Comment by RandomTNT** [comment]
игроек, скинь код сервера апп маркета

**Comment by IgorTimofeev** [comment]
@RandomTNT не-а

**Comment by RandomTNT** [comment]
Ладно

вс, 22 мая 2022 г., 22:15 IgorTimofeev ***@***.***>:

**Comment by snaildos** [comment]
Is the market fixed? If not, I am happy to host on my infrastructure that has off-site backups, etc, etc.

**Comment by MrFredber** [comment]
Issue with market was fixed.

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/191592222-710e32c4-93ab-47a5-8c56-eeb1c5b6fda3.png)

**Comment by ti-bone** [comment]
Хуяси)
