### ISSUE TITLE
Существует ли программа для управления турелями из мода OpenModularTurrets?

### ISSUE THREAD

**Issue by Hemerald27** [IgorTimofeev/MineOS#416]
Привет! появиться ли подобная программа в новых версия MineOS? Раньше вроде была ,но в последних версиях операционной системы её не стало... В крайнем случае есть ли возможность её как-то портировать (P.S. я не программист но где то слышал что язык lua не такой сложный как кажется)

**Comment by MrFredber** [comment]
Эта программа не появится сама, если ты сам её не портируешь, потому что разработка ОС завершена ещё 3 года назад. Исходники должны лежать в папке Applications, но этой приложухи там нет. Может она где-то в старых коммитах завалялась?

**Comment by CoolCat467** [comment]
Old version from here: https://github.com/IgorTimofeev/MineOS/tree/testBranch/Applications/TurretControl
Version from old fork: https://github.com/4kamaz/MineOS/tree/master/Applications/TurretControl
