### ISSUE TITLE
Adding variables to buttons

### ISSUE THREAD

**Issue by cadergator10** [IgorTimofeev/MineOS#417]
Hello, so I wanted to make a modular security system, and in order to do that, I would need to pass variables through the on touch function. I wanted to know if there was a way to do that, cause I have no idea. Basically, each button has a different integer it needs to pass to the same function (eg the 1st button passes 1 to the function, and the 2nd button passes 2 to it.)

Here is an example of what I wanted to do:

```
--Function I want to run
function runMe(variable)
    GUI.alert("I was given " .. variable)
end

--initialization of buttons and assigning function
local button = window:addChild(GUI.button(everything needed to set up button)
button.onTouch = runMe, 1

local button2 = window:addChild(GUI.button(everything needed to set up button)
button2.onTouch = runMe, 2
```

**Comment by IgorTimofeev** [comment]
Hm, I see 2 obvious ways:

1) Easy, higher memory consumption with unique function for each button:
```lua
function runMe(variable)
    GUI.alert("I was given " .. variable)
end

button1.onTouch = function()
  runMe(1)
end

button2.onTouch = function()
  runMe(2)
end

...
```

2) Smart, with user-defined variable in each button object. But be careful with naming, because your custom variable name can override something "inside" like x/y/width/height, for example:

```lua
function onButtonTouch(workspace, button, ...)
    GUI.alert("I was given " .. button.myVariable)
end

button1.myVariable = "Yep, it's button 1"
button1.onTouch = onButtonTouch

button2.myVariable = "Ohh, it's button 2"
button2.onTouch = onButtonTouch
...
```

**Comment by cadergator10** [comment]
Awesome! Thank you so much :)
