### ISSUE TITLE
0nM5b1jU doesn't work

### ISSUE THREAD

**Issue by WPNick** [IgorTimofeev/MineOS#418]
https://pastebin.com/0nM5b1jU deleted from pastebin.com.

**Comment by 3elDU** [comment]
Эхх, прошла эпоха.
Даже сюда политоту впихнули, пидоры.

**Comment by MrFredber** [comment]
What? This paste was deleted on 4 march, i used him today. Nice.

**Comment by IgorTimofeev** [comment]
Wtf, they just deleted my acc with all installers. Fuck politicians xd

![image](https://user-images.githubusercontent.com/11760002/156923704-9cb82d59-49b3-4c05-95c4-82fec6dc6b64.png)

Pls use alternative installation method

**Comment by MrFredber** [comment]
Охуенно, у-воу-воу

**Comment by MrFredber** [comment]
This issue can be closed.

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/178814605-9288799c-730a-4aba-9982-3378f9bb7262.png)
