### ISSUE TITLE
MineOS не работает

### ISSUE THREAD

**Issue by Skwantik** [IgorTimofeev/MineOS#419]
другой способ скачать mineOS (wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /tmp/bios.lua && flash -q /tmp/bios.lua && reboot) по некоторым причинам не работает у меня 
Все время пишет о том, что скачивание неудачно, а после начинается перезагрузка системы и удаление биос как такового

**Comment by MrFredber** [comment]
Выглядит, как ненормальное поведение мода, т.к. все ссылки работают нормально.

**Comment by MrFredber** [comment]
А ты устанавливаешь систему сразу с дискеты OpenOS, или сначала устанавливаешь OpenOS на жёсткий диск, а потом пробуешь поставить систему?

**Comment by Skwantik** [comment]
![изображение_2022-03-15_162202](https://user-images.githubusercontent.com/101645439/158386829-9c6e0943-327c-4d75-acb3-66c174ea148c.png)
Вот что происходит

**Comment by MrFredber** [comment]
А, да, забыл. Есть такая приколюха в моде, что "временная" память (/tmp) на самом деле не временная. То есть после перезагрузки зачастую всё, что туда было сохранено, всё остаётся и почему-то не удаляется. А новое не может туда сохранится, т.к. срабатывает ограничение на объём временной памяти.

Попробуй заново установить OpenOS и указать другие пути в командах, например:
wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /home/bios.lua && flash -q /home/bios.lua && rm /home/bios.lua && reboot

**Comment by Skwantik** [comment]
> wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /home/bios.lua && flash -q /home/bios.lua && rm /home/bios.lua && reboot

Всё в точности так же, но один момент никак не успеваю заскринить, где пишет: Download... Failed.

**Comment by MrFredber** [comment]
А ты на сервере это делаешь или в локальном мире?

**Comment by Skwantik** [comment]
> А ты на сервере это делаешь или в локальном мире?

На сервере

**Comment by Skwantik** [comment]
> Ну тогда это может быть блокировка загрузок на сервере, либо блокировка сайта GitHub в стране, где он стоит (хотя GitHub вроде не блокировали). Короче - это не проблема MineOS.

понял, спасибо

**Comment by IgorTimofeev** [comment]
> другой способ скачать mineOS (wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /tmp/bios.lua && flash -q /tmp/bios.lua && reboot) по некоторым причинам не работает у меня

Звучит странно, т.к. ранее инсталлер попросту ссылался на гитхабовские файлы, и если раньше он работал - то и сейчас должен без проблем. Тем не менее можно попытаться вручную прошить биос через команду **flash** установочным файлом по ссылке выше

**Comment by ti-bone** [comment]
> > другой способ скачать mineOS (wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /tmp/bios.lua && flash -q /tmp/bios.lua && reboot) по некоторым причинам не работает у меня
> 
> Звучит странно, т.к. ранее инсталлер попросту ссылался на гитхабовские файлы, и если раньше он работал - то и сейчас должен без проблем. Тем не менее можно попытаться вручную прошить биос через команду **flash** установочным файлом по ссылке выше

Щас какая-то хуйня с сертами, через вгет и на арче и на опенос

Через сафари работает
![image](https://user-images.githubusercontent.com/59691680/159186318-c8ae5332-9753-4e15-ac2b-76c43ed29eb5.png)
![image](https://user-images.githubusercontent.com/59691680/159186350-1c8dacbd-9aec-4e59-8bbd-11feafa2a1ad.png)

Если вручную скопировать биос и прошить, то при включении такое;
![image](https://user-images.githubusercontent.com/59691680/159186585-6d4c01c5-7296-4089-9230-1e653cb67e4f.png)

**Comment by IgorTimofeev** [comment]
> Щас какая-то хуйня с сертами, через вгет и на арче и на опенос

Ооо, знакомая хуйня, на центосе та же история была. Пофиксил, если память не изменяет, через повторную верификацию сертификатов через openssl, и чет там с keychain еще было

> Кстати, у тебя пастебин отлетел, скорее всего связано с текущими событиями

Угу, вряд ли восстановят. Помянем, чо

**Comment by ti-bone** [comment]
> > Щас какая-то хуйня с сертами, через вгет и на арче и на опенос
> 
> Ооо, знакомая хуйня, на центосе та же история была. Пофиксил, если память не изменяет, через повторную верификацию сертификатов через openssl, и чет там с keychain еще было
> 
> > Кстати, у тебя пастебин отлетел, скорее всего связано с текущими событиями
> 
> Угу, вряд ли восстановят. Помянем, чо

Попробуй аппеляцию подать, хуй знает, мож разбанят

Можно и пересоздать впринципе, вроде всё есть в Wayback Machine, сам всякую хуйню оттуда беру

**Comment by IgorTimofeev** [comment]
> Попробуй аппеляцию подать пока возможно, хуй знает, мож разбанят

Хех, это первое, что я сделал. Игнорят уже с неделю. На пересоздание в принципе пофигу, к пастбину доверия больше нет, поэтому пусть оська ставится с гитхаба. Разве что длина команды стала жирноватой

**Comment by ti-bone** [comment]
> > Попробуй аппеляцию подать пока возможно, хуй знает, мож разбанят
> 
> Хех, это первое, что я сделал. Игнорят уже с неделю. На пересоздание в принципе пофигу, к пастбину доверия больше нет, поэтому пусть оська ставится с гитхаба. Разве что длина команды стала жирноватой

Вот пидорасы

**Comment by FrostyReplacement21** [comment]
Показывает белый экран

**Comment by inventor055** [comment]
Приветствую, таже проблема, но белый экран после вводы команды на установку с гита
![image](https://github.com/IgorTimofeev/MineOS/assets/125007252/f194494a-a954-4c47-a2eb-46a5b765a0ad)

**Comment by IgorTimofeev** [comment]
> Приветствую, таже проблема, но белый экран после вводы команды на установку с гита

У тебя экран 1 тира, а надо 3

**Comment by inventor055** [comment]
Понял, благодарю за помощь, теперь всё работает

**Comment by inventor055** [comment]
А такой вопрос, как закрывать окна?

**Comment by IgorTimofeev** [comment]
> А такой вопрос, как закрывать окна?

window:remove()

**Comment by inventor055** [comment]
а где ее вводить?

**Comment by inventor055** [comment]
и почему после того как я около минуты не исп пк он выкл с сообщением об недостатке энергии

**Comment by inventor055** [comment]
![image](https://github.com/IgorTimofeev/MineOS/assets/125007252/9a97ac59-c84c-4f02-8012-ced56a3fc2fb)

**Comment by inventor055** [comment]
Хотя я еммму пост энергию rf с помощью труб из mekanism, провода проводят около 200к rf энергия есть

**Comment by MrFredber** [comment]
Скорее всего у тебя чанки выгружаются с подачей энергии и комп начинает питаться от внутреннего буфера

**Comment by inventor055** [comment]
Понял, но я не выгружал чанки т.к. я постоянно нахожусь на базе. Я понял, оказывается у пк есть что-то типа ограничение на вход энергии, достаточно будет с еще двух сторон подвести энергию и всё будет хорошо,!

**Comment by IgorTimofeev** [comment]
> а где ее вводить?

Хз, что ты имеешь в виду под "закрывать окна". Тыкаешь на красную кнопку - окно закрылось. Если нужно программно закрывать окна, прям из кода, то `window:remove()`

**Comment by inventor055** [comment]
![image](https://github.com/IgorTimofeev/MineOS/assets/125007252/91efac6f-c916-4ae0-b25c-258115a25d87)
можешь подсказать, где эта красная кнопка?

**Comment by IgorTimofeev** [comment]
> можешь подсказать, где эта красная кнопка?

![Безымянный](https://github.com/IgorTimofeev/MineOS/assets/11760002/bc3e5f4e-9f80-4cfb-aafe-f518df20924a)

**Comment by inventor055** [comment]
Спасибо!

**Comment by inventor055** [comment]
![image](https://github.com/IgorTimofeev/MineOS/assets/125007252/dc96a29c-6611-4554-b0d6-3d27f26235b5)
При попытке добавить эффект в избранное

**Comment by IgorTimofeev** [comment]
> При попытке добавить эффект в избранное

Спасибо, пофиксил

**Comment by inventor055** [comment]
а как это обновить?

**Comment by inventor055** [comment]
OC переустановить?

**Comment by inventor055** [comment]
![image](https://github.com/IgorTimofeev/MineOS/assets/125007252/1b64b5b8-c2d7-49e4-b774-8a327afb02da)
После выполнения reinstall

**Comment by inventor055** [comment]
теперь нано боты не работают и всё остальное тоже

**Comment by inventor055** [comment]
![image](https://github.com/IgorTimofeev/MineOS/assets/125007252/fc24a3bc-7425-4ee6-970f-5ef703337a8b)
после ручной перезагрузки пк
