### ISSUE TITLE
Icon says it's 7x3 when it's 8x4

### ISSUE THREAD

**Issue by cadergator10** [IgorTimofeev/MineOS#422]
I updated my icon to use braille for more higher detailed icons, but it says it is 7x3, but I made it 8x4. I'll be able to post the image in a bit (at school)

**Comment by cadergator10** [comment]
The issue with this that I forgot to say was that the app store doesn't let me. I open it with the picture editor, which shows 8x4. BUT the app store doesn't let me use the pic as it thinks it's 7x3.

**Comment by cadergator10** [comment]
Here is link https://github.com/cadergator10/opencomputer-security-system/blob/main/src/database/MineOS/Icon.pic
It does manage to download the pic right from the github raw link before you say anything

**Comment by MrFredber** [comment]
Which version of OCIF this icon is saved?

**Comment by IgorTimofeev** [comment]
> BUT the app store doesn't let me use the pic as it thinks it's 7x3

Thx, It's known issue in AppMarket picture analyzing system. Cant fix it until reach home where host is located, sorry

**Comment by IgorTimofeev** [comment]
Should be fixed <3

**Comment by cadergator10** [comment]
Thank you!
