### ISSUE TITLE
как открыть shell?

### ISSUE THREAD

**Issue by b2nzy** [IgorTimofeev/MineOS#427]
в старой версии MineOS Можно было вернутся в shell. Возможно ли сейчас?

**Comment by MrFredber** [comment]
По умолчанию это вырезано за ненадобностью. Была иссуа, где чел возвращал эту возможность, но я не могу её найти.

**Comment by IgorTimofeev** [comment]
Из коробки никак, т.к. никакого shell попросту нет. Хочешь командную строку со всеми дефолтными скриптами из OpenOS - ставь OpenOS. Еще можно из маркета скачать эмулятор OpenOS, довольно неплохо работающий
