### ISSUE TITLE
Несколько выпадающих списков в контекстном меню

### ISSUE THREAD

**Issue by SashaTalk** [IgorTimofeev/MineOS#430]
Странно, что никто этого не заметил раньше. Проверил везде где только можно - проблема та же.
![image](https://user-images.githubusercontent.com/76222964/163709054-e36e7865-52f1-4cfe-a726-eddce6532f08.png)

**Comment by Bumer-32** [comment]
разве это не пофиксили уже?

**Comment by SashaTalk** [comment]
> разве это не пофиксили уже?

я не знаю, иссуя создана полгода назад

**Comment by MrFredber** [comment]
https://github.com/IgorTimofeev/MineOS/pull/471
это уже пофиксили

**Comment by SashaTalk** [comment]
тогда закрываю
