### ISSUE TITLE
Issue when opening settings,&monitor switching issue,also recovery script issue

### ISSUE THREAD

**Issue by sussymogus1** [IgorTimofeev/MineOS#444]
To whom it may concern: YES I REINSTALLED IT, MORE THAN 5 TIMES
Issue when running settings app : Plays a beep noise and opens text, but closes it before I can read it. Steps to reproduce : open settings app in newest version. _Cannot add screenshot as it disappears too early_
Issue when running recovery script, (403). Steps to reproduce : open Efi with ALT, and run recovery thing only for tinyurl to not exist
Issue when switching monitors : efi shows error
_Before switching_
![monitorbefore](https://user-images.githubusercontent.com/106500364/171081822-85d929e9-fbbe-467c-836b-015233ebda2b.PNG)
After:
![monitorafter](https://user-images.githubusercontent.com/106500364/171081863-deb10a8d-4598-4909-bd9d-51bf6c06e02f.PNG)

**Comment by sussymogus1** [comment]
also I removed the 2nd keyboard incase its causing issues but no

**Comment by MrFredber** [comment]
> Cannot add screenshot as it disappears too early
You can shot a video and take screenshot from it with any video editor

**Comment by IgorTimofeev** [comment]
> Issue when running settings app
Fixed, thx. Problem was in incorrect localization file

> Issue when running recovery script, (403)
Unable to reproduce, recovery works fine. Maybe your server blocks tinyurl or something?

**Comment by sussymogus1** [comment]
Thanks, my router had tinyurl on the blocklist for some reason
Didnt even think of that
