### ISSUE TITLE
Вопрос гению, который добавил новую фичу

### ISSUE THREAD

**Issue by MrFredber** [IgorTimofeev/MineOS#446]
Зачем создавать ярлык по иконке, а не по выбранному файлу?
(я посмотрел, в чём прикол ошибки, но хз, как называются нужные переменные в библе)

https://user-images.githubusercontent.com/33953266/171377765-1aac5423-ce09-45fb-bfa5-d900f5162d0d.mp4

И чё за "точный режим", который можно включить в настройках? я так и не понял, чё это изменяет.

**Comment by IgorTimofeev** [comment]
Баг фиксанул, гений послан на хуй, но передает привет маме. Точный режим - эт, кароч, флаг для мониторов, позволяющий отсылать ивенты touch/drag/drop/scroll с дробными координатами. В 99% случаев юзлесс хуйня, но ранее ось ее не поддерживала и вылетала, а сейчас норм хавает
