### ISSUE TITLE
Ну как так можно обосраться?

### ISSUE THREAD

**Issue by MrFredber** [IgorTimofeev/MineOS#451]
https://user-images.githubusercontent.com/33953266/173409378-6746cd4e-1b53-4976-8767-48e90192d0de.mp4

**Comment by MrFredber** [comment]
Я отрендерил с кодеком h.265, поэтому видео не везде показывается. Возможность отредерить в доступном кодеке появится позже, если нужно

**Comment by MrFredber** [comment]
This is because i render in wrong codec (h.265/HEVC), which most browsers don't understand. This video don't have any sound.

**Comment by MrFredber** [comment]
I can remake video only after 8 hours

**Comment by IgorTimofeev** [comment]
\> Сдохла юзлесс микро-фича в одном из десятков приложений, которой пользуется 1.5 инвалида
\> Ну как так можно обосраться? Ахахахаха, НУ ВЫ ВИДЕЛИ? ВОТ ЭТО ПОЗОР, ЕПТА, УЖАС, СМЕРТЬ, RUINA IMPERII

Ничо не знаю, на чистой оси все работает, соси бибу))0

![image](https://user-images.githubusercontent.com/11760002/173496690-03edc4c6-43a4-4263-8d1a-df117dd5a4d1.png)

**Comment by IgorTimofeev** [comment]
Мб маркет криво обнову накатил, без старой сломанной версии фиг знает, как фиксить, НО УЧТЁМ, СПС!

**Comment by MrFredber** [comment]
Кста я реально несколько раз замечал, будто маркет обновляет цифры в versions.cfg, а сам их как будто не скачивает. Помню, было это, когда в фотошопе наконец-то появилась поддержка языковых пакетов. Я обновляю фотошоп и не вижу перевода. Но как только я откатываю циферки и заново обновляю, то всё сразу появилось. Прикольный баг короче :)

**Comment by IgorTimofeev** [comment]
Угу, странная хрень, пару раз такое тоже замечал, но отловить так и не смог, забив хуй
