### ISSUE TITLE
Im cryed, that can't install!!

### ISSUE THREAD

**Issue by LAGSNES** [IgorTimofeev/MineOS#452]
I trying flash the BIOS.lua, the programs puts a error.

my friend tryed flash, but can't reboot.
![image](https://user-images.githubusercontent.com/106414868/174255423-be61e829-52a8-44ba-b297-46a91dba5a73.png)

**Comment by MrFredber** [comment]
Remove all files in /tmp directory and try again

**Comment by IgorTimofeev** [comment]
What is "BIOS.lua"? Where did you get it? What should it do? Do you want to use MineOS EFI as default firmware for your EEPROM? Or do you want to use "installer firmware"?

**Comment by SteveUbuntu0** [comment]
> What is "BIOS.lua"? Where did you get it? What should it do? Do you want to use MineOS EFI as default firmware for your EEPROM? Or do you want to use "installer firmware"?

Oh, I'm is he's friend.
He just want use the "install firmware" to install the MineOS.
The "BIOS.lua" is get it on the "https://github.com/IgorTimofeev/MineOS/blob/master/Installer/BIOS.lua"

**Comment by MrFredber** [comment]
Why? The only way normally install MineOS - is through the installer
Installer is automatically flash the bios to MineOS EFI

**Comment by SteveUbuntu0** [comment]
> Why? The only way normally install MineOS - is through the installer Installer is automatically flash the bios to MineOS EFI

What's your mean? 
We can't to use this command:"wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /tmp/bios.lua && flash -q /tmp/bios.lua && reboot"

**Comment by MrFredber** [comment]
How anyone can help you without any information? Maybe you screenshot the error message or whatever you have?

**Comment by IgorTimofeev** [comment]
> Oh, I'm is he's friend.
He just want use the "install firmware" to install the MineOS.
The "BIOS.lua" is get it on the "https://github.com/IgorTimofeev/MineOS/blob/master/Installer/BIOS.lua"

On the screenshot above @LAGSNES is trying to run **existing** main.lua script using OpenOS, which isn't "normal way" to install MineOS. Where did you get this script? From [here](https://github.com/IgorTimofeev/MineOS/blob/master/Installer/BIOS.lua#L5)? If so, this script can't be launched from OpenOS, because it designed for "clean" OpenComputers hardware without any OSes, and you should use installation command from this repo homepage

> We can't to use this command:"wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /tmp/bios.lua && flash -q /tmp/bios.lua && reboot"

Why can't you? The error on screenshot says there's some inappropriate characters on 8 line. Are you sure your internet provider doesn't block githubusercontent.com or it's not blacklisted on your server/modconfig?

![image](https://user-images.githubusercontent.com/11760002/174474658-efd4232b-7402-4fc3-9cb0-7861f35e9ff4.png)

**Comment by CoolCat467** [comment]
If wget command does not work (internet provider blocks it or blacklisted on your server), then you could go to https://github.com/IgorTimofeev/MineOS/blob/master/Installer/BIOS.lua and copy paste the code into the Minecraft computer in file `/tmp/bios.lua` and then just do `flash -q /tmp/bios.lua && reboot`. It would be better to fix wget, but it is more simple to copy paste.

**Comment by IgorTimofeev** [comment]
> If wget command does not work (internet provider blocks it or blacklisted on your server)

If so, he won't be able to install any lib anyway :p

**Comment by SteveUbuntu0** [comment]
> If wget command does not work (internet provider blocks it or blacklisted on your server), then you could go to https://github.com/IgorTimofeev/MineOS/blob/master/Installer/BIOS.lua and copy paste the code into the Minecraft computer in file `/tmp/bios.lua` and then just do `flash -q /tmp/bios.lua && reboot`. It would be better to fix wget, but it is more simple to copy paste.

ahh, We in China.

**Comment by SteveUbuntu0** [comment]
> > Oh, I'm is he's friend.
> > He just want use the "install firmware" to install the MineOS.
> > The "BIOS.lua" is get it on the "https://github.com/IgorTimofeev/MineOS/blob/master/Installer/BIOS.lua"
> 
> On the screenshot above @LAGSNES is trying to run **existing** main.lua script using OpenOS, which isn't "normal way" to install MineOS. Where did you get this script? From [here](https://github.com/IgorTimofeev/MineOS/blob/master/Installer/BIOS.lua#L5)? If so, this script can't be launched from OpenOS, because it designed for "clean" OpenComputers hardware without any OSes, and you should use installation command from this repo homepage
> 
> > We can't to use this command:"wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /tmp/bios.lua && flash -q /tmp/bios.lua && reboot"
> 
> Why can't you? The error on screenshot says there's some inappropriate characters on 8 line. Are you sure your internet provider doesn't block githubusercontent.com or it's not blacklisted on your server/modconfig?
> 
> ![image](https://user-images.githubusercontent.com/11760002/174474658-efd4232b-7402-4fc3-9cb0-7861f35e9ff4.png)

We will try download from "https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua "

**Comment by GusarevKirill** [comment]
> > What is "BIOS.lua"? Where did you get it? What should it do? Do you want to use MineOS EFI as default firmware for your EEPROM? Or do you want to use "installer firmware"?
> 
> Oh, I'm is he's friend. He just want use the "install firmware" to install the MineOS. The "BIOS.lua" is get it on the "https://github.com/IgorTimofeev/MineOS/blob/master/Installer/BIOS.lua"

"unexpected symbol near '<'" - I think may be there is HTML code inside, but not Lua?
Check it: `edit /tmp/main.lua` and what do you see?

**Comment by Xanderplayz16** [comment]
Maybe try using a VPN. Using a VPN is like connecting your computer to the internet 
in a different place but you are still where you are. I recommend hide.me VPN. The free tier is good, and it is one of the lesser known VPN's so china probably will not block it. Download is [here](https://hide.me/en/)

**Comment by Smok1e** [comment]
> I trying flash the BIOS.lua, the programs puts a error.
> 
> my friend tryed flash, but can't reboot. ![image](https://user-images.githubusercontent.com/106414868/174255423-be61e829-52a8-44ba-b297-46a91dba5a73.png)

Here's how you can install MineOS EFI without using wget, without an internet card, and even with a read-only filesystem:

https://user-images.githubusercontent.com/33802666/201628533-9bdc7e20-abbd-4b97-aea5-13819159de0b.mp4

1. Open `https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/EFI/Minified.lua`

2. Select all text with **ctrl+a** and copy it with **ctrl+c**

3. In OpenOS, type `edit /tmp/efi.lua`, paste the copied text using the **insert** key or the **middle mouse button**

4. Press **ctrl+s** and then **ctrl+w** to save the file and exit

5. In OpenOS, type `flash -q /tmp/efi.lua "MineOS EFI"` and wait for the operation to complete

You now have MineOS EFI

**Comment by MrFredber** [comment]
But what MineOS EFI can give him if he can't use wget command and can't install MineOS?

**Comment by Smok1e** [comment]
> But what MineOS EFI can give him if he can't use wget command and can't install MineOS?
Хз, решение проблемы я предоставил, остальное дело не моё

**Comment by MrFredber** [comment]
![](https://user-images.githubusercontent.com/33953266/201650451-f9e004c5-f60e-47ac-94a6-84b1d907835a.png)
