### ISSUE TITLE
Memory fills up as my program is stopped and started again

### ISSUE THREAD

**Issue by cadergator10** [IgorTimofeev/MineOS#459]
Is there a proper way to exit a program? I have it set to window:remove() when the exit button is pressed, but if the pc is on for too long, memory goes up to 99% as program is restarted.

**Comment by IgorTimofeev** [comment]
Hm, the "proper way" is to call window:remove() to let window object to be collected by GC later. But your case looks like a worst possible problem with a memory leak which detection is almost impossible without memory profiler or some extra tools. I also encountered same shit in a couple of apps - but decided that the game was not worth the candle

**Comment by kingofsponges** [comment]
mineos is known for being memory intensive at times
