### ISSUE TITLE
Есть ли возможность вернуть фичу?

### ISSUE THREAD

**Issue by MrFredber** [IgorTimofeev/MineOS#460]
Как-то заглядывался на старую гифку, которую ты поставил в README.MD, и заметил, что во время разворачивания Finder на фулскрин задник левой панели показываает рабочий стол.
А сейчас за эффектом замыливания почему-то просто чёрный цвет вместо рабочего стола.
Можно ли это пофиксить?

https://user-images.githubusercontent.com/33953266/178436026-5139b7cb-a01d-4263-87fa-277fa99e5e09.mp4

**Comment by IgorTimofeev** [comment]
Занятная инфа, спасибо . Эт, видимо, баг фуллскрин разворота, когда отрисовка раб. стола отключается ради экономии ресурсов. По-хорошему тут надо учитывать юзерские  настройки прозрачности и блюра, чтоб отключать отрисовку только при их отсутствии. НО ЛЕНЬ

**Comment by IgorTimofeev** [comment]
> Понять бы - где отключается прорисовка раб. стола

[Тута](https://github.com/IgorTimofeev/MineOS/blob/master/Libraries/System.lua#L1819-L1839)
