### ISSUE TITLE
Download bug.

### ISSUE THREAD

**Issue by Leonardo5681** [IgorTimofeev/MineOS#461]
![Immagine 2022-07-12 140137](https://user-images.githubusercontent.com/92219720/178486271-652464e6-f31c-4183-ba49-958aa72adc06.png)

I tried to install MineOS with pastebin run 0nM5b1jU but failed.Fix this bug please!

**Comment by IgorTimofeev** [comment]
Pastebin acc was deleted because of war on Ukraine. Use alternative installation method from repo:

![image](https://user-images.githubusercontent.com/11760002/178490310-f85bb53e-b7ba-47f9-89b9-967aeb407d07.png)

**Comment by Leonardo5681** [comment]
Why for Ukraine war???

Il giorno mar 12 lug 2022 alle ore 14:32 IgorTimofeev <
***@***.***> ha scritto:

**Comment by MrFredber** [comment]
Why? The alternative command work same way as pastebin command

**Comment by Leonardo5681** [comment]
It doesn't work. Help otherwise I won't be able to install MineOS anymore

**Comment by IgorTimofeev** [comment]
> otherwise I won't be able to install MineOS anymore

Sounds ok for me if that was a threat xd

Use "insert" key on your keyboard or middle mouse button or whatever you've set in game settings to paste "real world" clipboard to opencomputers

**Comment by Leonardo5681** [comment]
I changed the "Copy to clipboard" button to another key and now it works. Thanks. (If you can please do another pastebin code though)

**Comment by MrFredber** [comment]
> Btw here's copy of original pastebin installer, but performance isn't guaranteed:
https://pastebin.com/vhg5uu1b

He already do that

**Comment by Leonardo5681** [comment]
But if you try to update and contribute to the Opencomputers mod project you will make me really happy

**Comment by IgorTimofeev** [comment]
> But if you try to update and contribute to the Opencomputers mod project you will make me really happy

I've already asked MightyPirates if it's possible to add MineOS installer as loot disk - for now then answer is "no". Anyway OpenComputers hasn't received updates for 3 years, so this is unlikely

**Comment by Leonardo5681** [comment]
However how do you contribute to the mineos type project for beta testing

**Comment by Leonardo5681** [comment]
Anyway thanks I created the pastebin code to install mine os if you want I will send it to you
