### ISSUE TITLE
can't download, says download failed

### ISSUE THREAD

**Issue by Duckifer** [IgorTimofeev/MineOS#465]
i can't download the OS, it says download failed then this
![Screenshot 2022-08-01 161523](https://user-images.githubusercontent.com/110425839/182238496-df40f29c-e057-48a1-bef2-9debc6302e4d.png)

**Comment by go00** [comment]
Do you have a internet card in OpenComputer computer?

**Comment by Bumer-32** [comment]
install openOS and internet

**Comment by vasya156** [comment]
try from pastebin

**Comment by Bumer-32** [comment]
it`s a bug OC 1.7.6 not mineOS
update to OC 1.7.7 and you can close issue

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/188455436-ac3f6526-43b6-4221-9904-86805d4cf4bc.png)
