### ISSUE TITLE
Uninstalling MineOS on a tablet

### ISSUE THREAD

**Issue by matthyno** [IgorTimofeev/MineOS#466]
I've been looking around and I can't seem to find a way to get OpenOS back on a tablet. It always goes to "MineOS EFI", and I don't know how to overwrite that. Please help!

**Comment by Leonardo5681** [comment]
Hi, to uninstall mine os let's say you have to make a new tablet unless you can reset the eeprom with some apps in the store only you have to have a backup of the efi openos and you have to disassemble the tablet to remove the eeprom

**Comment by IgorTimofeev** [comment]
insert openos floppy
turn on computer
hold alt
set openos floppy as bootable
back
back
