### ISSUE TITLE
Краш системы

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#467]
![Biblioteka GUI slozhnaya!](https://user-images.githubusercontent.com/79054301/183267473-fb4b775e-1213-4641-9d20-373a659800aa.jpg)

**Comment by Bumer-32** [comment]
БИбЛИОТЕКА GUI? СЛОЖНА

**Comment by MrFredber** [comment]
Ну и нахуя нам всем эта инфа?

**Comment by IgorTimofeev** [comment]
😔
