### ISSUE TITLE
Критическая ошибка при удалении ярлыка.

### ISSUE THREAD

**Issue by Procybit** [IgorTimofeev/MineOS#468]
Если прикрепить ярлык (именно ЯРЛЫК) в Dock, а впоследствии его удалить, система сразу крашнется, и будет продолжать крашится при каждом последующем входе в профиль.

![](https://i.gyazo.com/409378f39bc169ae8a5626f491f15efb.png)

P.S. Можно подшаманить над ~/Settings.cfg через OpenOS, и профиль починится, но это поможет только до следующего (случайного) удаления другого ярлыка :)

**Comment by Procybit** [comment]
Я типа ошибку пофиксил, но это новая фича, так что чекните пулл реквест (https://github.com/IgorTimofeev/MineOS/pull/469).

**Comment by IgorTimofeev** [comment]
Упс))0

Спасибо за фикс!
