### ISSUE TITLE
why

### ISSUE THREAD

**Issue by tysonlmao** [IgorTimofeev/MineOS#470]
Did you really find it necessary to use adhesive to hold your mod mod together? Fix pls

**Comment by PublicVoidUpdate** [comment]
?

**Comment by tysonlmao** [comment]
no

**Comment by PublicVoidUpdate** [comment]
this isn't a mod it's software for a mod, is not held together by adhesive, it's optimized as hell, but that's due to the fact we are working on terrible hardware (oc-computers) so this issue isn't even a thing.

**Comment by PublicVoidUpdate** [comment]
fuckin chad^^^
