### ISSUE TITLE
После обновы на 1.7.6 сломалась ос

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#472]
Игооорь

после обновы OC система сломалась!

конкретно проблемы с символами  браиля (или с double buffering)

у меня лично сломались кнопки и на иконках в местах с символами браиля тоже проблемы

![image](https://user-images.githubusercontent.com/79054301/187866009-2a05925f-a07d-4f2d-8f92-4c4c23448135.png)

**Comment by IgorTimofeev** [comment]
Ну шо тут сказать... ебал я в рот такие обновы))0

**Comment by Bumer-32** [comment]
мммм как понятно сказано!

решение (не через 5 лет) делать планируешь или назад на 1.7.5 переходить?

**Comment by Bumer-32** [comment]
а иссуху можно закрывать
ток что узнал что это баг мода а не майн оси

кайфуем

**Comment by IgorTimofeev** [comment]
> решение (не через 5 лет) делать планируешь или назад на 1.7.5 переходить?

Даже если бы это была проблема не мода, а майноси, то фиксить все равно не стал бы. Это ж иконки перерисовывать надо, искать брайлевые замены, вся фигня
