### ISSUE TITLE
сломаны кнопки закрыть скрыть и развернуть

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#473]
после обновы на OC 1.7.7 символы браиля починились

а кнопки действий нет!
![image](https://user-images.githubusercontent.com/79054301/188324873-3b2ef872-1fe0-4f1f-8c41-42216392b725.png)

Игорь ну испрааавь а

**Comment by IgorTimofeev** [comment]
Не, мне похуй, лень искать кружочки

**Comment by Bumer-32** [comment]
ну пазязя

эмулатор то не не разрешает с другими модами работать

**Comment by Bumer-32** [comment]
НУ ИГАРЬ НУ СДЕЛАЙ ЧТО ТО

**Comment by IgorTimofeev** [comment]
@Axeer 

![image](https://user-images.githubusercontent.com/11760002/189907746-22345835-3cc3-407a-b21b-8d4c21d386d9.png)
