### ISSUE TITLE
cant install mineOS 

### ISSUE THREAD

**Issue by jirka086** [IgorTimofeev/MineOS#474]
![image](https://user-images.githubusercontent.com/53871380/189475406-0022a676-bb76-42cb-8874-829e76d9df2e.png)
i run the install script

`wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /tmp/bios.lua && flash -q /tmp/bios.lua && reboot` 

after dowloanding, rebooting, loading this appears

**Comment by IgorTimofeev** [comment]
Is your server on aarch64?
Same problem: #369
Mod issue: https://github.com/MightyPirates/OpenComputers/issues/3466
