### ISSUE TITLE
всё сломано НА...

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#476]
![image](https://user-images.githubusercontent.com/79054301/189992209-c5820c91-5bbd-4c59-866c-a90df6ab486b.png)

упс
при установочке

**Comment by Axeer** [comment]
Пока накатывай майнось поверх установленной опеноси
Проблему скоро исправлю

**Comment by IgorTimofeev** [comment]
Да в пизду, ревертну коммит и сделаю мелкие кругляхи. На чистой майноси освершна не было никогда, так шо)00

**Comment by Axeer** [comment]
Сори за кринж в мэйне, не знал о возможности установки майноси отдельно от опена. Буду более аккуратным
