### ISSUE TITLE
Система ломается во время включения (загрузки обоев) или любой другой момент

### ISSUE THREAD

**Issue by dnrovs** [IgorTimofeev/MineOS#481]
Когда устанавливаю MineOS на ПК максимальной мощности (креативный, все комплектующие максимального или креативного уровня), при запуске (обычно после того как ввел пароль, начинают загружатся обои рабочего стола), и тут возникает ошибка на синем экране:
`Unrecoverable Error`
`too long without yielding`
Вот скриншот ошибки:
![image](https://user-images.githubusercontent.com/63865083/192372098-3912f80e-e923-43c8-b4bf-de727275ca50.png)
Когда я беру ПК 2-3 уровня со средними комплектующими, все работает нормально, только на максимальном ПК такая проблема

**Comment by IgorTimofeev** [comment]
Обычно эта проблема связана с нехваткой ресурсов и ебической загрузкой вирт. компа на хуевом реальном железе. Тут можно лишь гадать на кофейной гуще. Мб обои слишком жирные (если установлены не дефолтные), мб модов в сборке дофига, и опенкомпы банально не вытягивают, мб проблема в креативных компонентах из стороннего мода, мб конфиг опенкомпов был поправлен, мб еще чо

**Comment by dnrovs** [comment]
> Обычно эта проблема связана с нехваткой ресурсов и ебической загрузкой вирт. компа на хуевом реальном железе. Тут можно лишь гадать на кофейной гуще. Мб обои слишком жирные (если установлены не дефолтные), мб модов в сборке дофига, и опенкомпы банально не вытягивают, мб проблема в креативных компонентах из стороннего мода, мб конфиг опенкомпов был поправлен, мб еще чо

Понял, всё же наверное из-за того что железо говно, или из-за большого количества модов. Без обоев (дефолтных), просто с серым экраном, оно запускается нормально. Спасибо за ответ

**Comment by dnrovs** [comment]
На сервере всё работает отлично, походу моё _корыто_ не вытягивает этот мод нормально.

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/198017187-35297bcb-54cb-4564-96bf-1728ffca7d0c.png)
