### ISSUE TITLE
Multiscreen выдаёт ошибку

### ISSUE THREAD

**Issue by alcnode** [IgorTimofeev/MineOS#482]
Указываю количество экранов, начинаю калибровку. При клике на экран, выдаёт ошибку(см. скриншот). В чём проблема, как фиксить?
![image](https://user-images.githubusercontent.com/36013473/193693482-3b8b7f11-c423-4081-8645-33efe5b956b4.png)

**Comment by IgorTimofeev** [comment]
Исправил, спасибо. Потребуется перекачать приложение
