### ISSUE TITLE
Не работает Multiscreen

### ISSUE THREAD

**Issue by Hemerald27** [IgorTimofeev/MineOS#483]
Добрый день, Игорь Тимофеев. Не работает Программа мультискрин не пашет, такое замечал на последних версиях опен ПК, на 1,7,10 все норм.
![Снимок экрана (692)](https://user-images.githubusercontent.com/99420965/193810791-44ea399a-8893-4a40-ab2b-14d1c8737739.png)
это ошибку прога выдала в цвете, но обычно на первом мониторе который тыкаешь пальцем, она зависает и выбивает ошибку в черно белом режиме.
![image](https://user-images.githubusercontent.com/99420965/193811105-ea5d5ffd-fc17-4d3b-be66-e0a6c23bd567.png)
выглядит так, что с этим делать ума не приложу. Согласен могу попробовать сам разобратся. (так было с турелями но в итоге плюнул и другую прогу переписал)

**Comment by IgorTimofeev** [comment]
Спасибо, пофикшено сегодня в #482
