### ISSUE TITLE
Gui of installer is buggy

### ISSUE THREAD

**Issue by cybr-dev** [IgorTimofeev/MineOS#485]
I am using the latest version of OC together with the native arm packages!

When I try to install mine OS get this buggy screen!
![2022-10-06_21 14 55](https://user-images.githubusercontent.com/21309649/194399864-fe6cda9d-4608-4211-bfbb-fd59ea83f716.png)

**Comment by dnrovs** [comment]
You are probably using a first level monitor. As far as I know, the OS needs a level 2 or higher monitor to function.

**Comment by cybr-dev** [comment]
Thanks, case closed!
