### ISSUE TITLE
I cant run this simple script that broadcasts a message then waits for one

### ISSUE THREAD

**Issue by LittleTimmy52** [IgorTimofeev/MineOS#486]
It works upuntil it trys to receive a message

error:
![Captu3re](https://user-images.githubusercontent.com/90333044/196064742-46b6b511-b2ae-40be-ba3d-94c85f16bcc4.PNG)
![Capture1](https://user-images.githubusercontent.com/90333044/196064743-475c2bde-3493-4335-812b-75c90c62c67f.PNG)

code:
```local component = require("component")
local event = require("event")
local m = component.modem -- get primary modem component
m.open(123)
print(m.isOpen(123)) -- true
-- Send some message.
m.broadcast(123, "this is a test")
-- Wait for a message from another network card.
local _, _, from, port, _, message = event.pull("modem_message")
print("Got a message from " .. from .. " on port " .. port .. ": " .. tostring(message))

**Comment by IgorTimofeev** [comment]
> local event = require("event")

Event name filtering is OpenOS-only feature. MineOS adheres to the principle of "purity" of libraries without redundant checks, so you have to add them yourself:

```lua
while event.pull() ~= "modem_message" do
 -- Do something
end
```
