### ISSUE TITLE
проводнику насрать на часовые пояса

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#488]
https://user-images.githubusercontent.com/79054301/197170099-408c7823-e29f-41eb-b616-488daf39307f.mp4

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/197219998-6182117a-dfb9-41b4-94e4-52019e47c935.png)

**Comment by MrFredber** [comment]
Там же кста в обнове OpenComputers поменяли систему дат. Может быть в этом проблема?

**Comment by IgorTimofeev** [comment]
> Там же кста в обнове OpenComputers поменяли систему дат. Может быть в этом проблема?

Та не, я просто забыл про часовые пояса хд

**Comment by IgorTimofeev** [comment]
Ладно, ладно, пофиксил, спасибо
