### ISSUE TITLE
"Свойства" ломаються при "точном режиме"

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#494]
при ПКМ - свойства
![image](https://user-images.githubusercontent.com/79054301/197455706-41ae773f-ed1c-4d6a-b7a8-0907df251e51.png)

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/197506554-72f7a7e0-aced-4fb8-92e7-3e4c20c3a749.png)

Вродь заебись все. На какой ярлык надо кликнуть, чтоб оно сдохло?

**Comment by Bumer-32** [comment]
на любой

**Comment by IgorTimofeev** [comment]
Ну бля, я ж кинул скрин выше, где кликаю на любой - и все заебись. Какие-то специфические системные опции активны? Хоть что-то кастомное имеется?

**Comment by Bumer-32** [comment]
из либ ни-че-го, из прог было - уже нет и то вроде либ оно не требовало, собственные приложухи были но там они ни куда не лезли
онли значки были "Black MineOS" но и там ничего

но бл на втором пк всё работаеn
ссылался на кривую установку но НЕТ ни GUI ни Color ни Screen не были повреждены

**Comment by Bumer-32** [comment]
хотелось бы узнать из за чего это могло произойти вдруг чё

**Comment by Bumer-32** [comment]
ЕМАН НАШЁл

это происходить при "точном режиме", что это вообще такое?

**Comment by MrFredber** [comment]
это когда у тебя разрешение экрана не 160х50, а 160.0х50.0
а также эвент touch вместо целых чисел выдаёт дробные

**Comment by Bumer-32** [comment]
М.б тогда в свойствах нужно math.floor() или чёт тип того добавить?

**Comment by IgorTimofeev** [comment]
> ЕМАН НАШЁл
> это происходит при "точном режиме", что это вообще такое?

О, спасибо, уважаю. Сейчас исправлю
