### ISSUE TITLE
Не установленное установленное говно из app market

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#496]
по умолчанию picture view ставиться, а вот апп маркет так не думает и придлагает поставить ещё один

**Comment by IgorTimofeev** [comment]
Апдейт старого или еще один? По дефолту все софтины ставятся как "необновленные"

**Comment by Bumer-32** [comment]
небольшая обновка информации

вот так происходит не только с picture view. и при чём не только с приложениями! к примеру обои так же не установлены.
это точно не единичный случай (т.к ос я переустановил)
![зображення](https://github.com/IgorTimofeev/MineOS/assets/79054301/225af42e-4127-4876-90fb-d0ff86127557)

**Comment by misha99fr** [comment]
попробуй переустановить MineOS

**Comment by Bumer-32** [comment]
> попробуй переустановить MineOS

ты блять серьёзно? или фраза

> это точно не единичный случай (т.к ос я переустановил)

для тебя пустой звук?

**Comment by misha99fr** [comment]
блять, я не заметил, че ты такой злой

**Comment by Bumer-32** [comment]
> блять, я не заметил, че ты такой злой

всем можно мне нельзя? злой и злой, что тут такого?

**Comment by misha99fr** [comment]
тебе никто не запрещает
