### ISSUE TITLE
закуривший переполненный таскбар

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#497]
![image](https://user-images.githubusercontent.com/79054301/197619555-957956cc-3aba-4a09-99db-e6f1cf3e18d3.png)
не я конеш понимаю никто столько приложух не запустит в силу оперативы но вдруг люди захотят в док закрепить реально много приложений?
нужно как то запилить систему переполнения, но эт откладываться в долгий ящик ведь всем лень это 100%

**Comment by Smok1e** [comment]
![kavun](https://github.com/IgorTimofeev/MineOS/assets/33802666/3e3f1ee3-f5d8-473a-ab84-1069d425b50b)
