### ISSUE TITLE
Магазин не определяет язык

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#498]
![image](https://user-images.githubusercontent.com/79054301/198092094-464b3b18-a1ed-4c85-bcad-caccc49161aa.png)
хочу изменить описание приложухи но фигушки

(Игорь может сделать описание импортом файла? так удобнее будет)

**Comment by IgorTimofeev** [comment]
Апиха яндекс.трайнслейта сдохла, видимо. Ну и хуй с ней, отрубил переводы, ошибка должна исчезнуть, спасибо

**Comment by Bumer-32** [comment]
я вот тут подумад, и понял что эт может быть заблоканый yandex в Украине. Так что можно подрубить но с учётом того что иногда подключения может не быть)

**Comment by IgorTimofeev** [comment]
Та неее, эт яндекс попросту оффнул бесплатный перевод для плебса вроде нас. Вообще есть много обходных путей для решения этой проблемы, но проще попросту отключить переводы. Старый ж проект, мейнтейнить некому
