### ISSUE TITLE
При нажатии кнопку "открыть" (публикацию) в настройках appMarket приложение открывается не в том табе

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#499]
https://user-images.githubusercontent.com/79054301/198351681-0349cad2-fba4-4b6a-8299-92dbe1556ae3.mp4

**Comment by IgorTimofeev** [comment]
Так и было задумано, чо уж там

**Comment by braisedev** [comment]
Не баг а фича
