### ISSUE TITLE
appmarket тоже насрать на часовые поеса в диалогах  --500 УСУА УРА🎉🎊🥳🎈

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#500]
![image](https://user-images.githubusercontent.com/79054301/198352507-a8c95f2e-ab03-4cc6-bffe-008ec8d79e9e.png)
![image](https://user-images.githubusercontent.com/79054301/198352517-6db0507c-b828-4a21-acd0-fb5403940df0.png)

**Comment by IgorTimofeev** [comment]
Fixed by @Hatry1337 at https://github.com/IgorTimofeev/MineOS/pull/525
