### ISSUE TITLE
text.wrap()  в либе Text не работает

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#505]
![image](https://user-images.githubusercontent.com/79054301/201676009-0d7af6bb-eb82-4f68-8188-92b1be587e30.png)
взял код прямо из документации

**Comment by IgorTimofeev** [comment]
Oшибка связана с **однострочным** виджетом GUI.text, которому скормили **таблицу** врапнутых стринг вместо одной стринги. Чо за код из документации, ну-ка, ну-ка?

**Comment by Bumer-32** [comment]
> Oшибка связана с **однострочным** виджетом GUI.text, которому скормили **таблицу** врапнутых стринг вместо одной стринги. Чо за код из документации, ну-ка, ну-ка?

А, его туда пихать нельзя?

а под кодом из документации я подозревал

local data = "Those days, the Third Age of Middle-earth, are now long past, and the shape of all lands has been changed; but the regions in which Hobbits then lived were doubtless the same as those in which they still linger: the North-West of the Old World, east of the Sea."

text.wrap(data, 24)
обёрнутое в текст

**Comment by IgorTimofeev** [comment]
Ну дык

![image](https://user-images.githubusercontent.com/11760002/201765777-1096dbda-93a2-441b-817a-18812b722546.png)

![image](https://user-images.githubusercontent.com/11760002/201765837-b841281e-4aa0-40aa-85b6-2f0d22d2a009.png)

Смекашеь? Тебе **textBox** нужен, не **text**. Там и авто-перенос поддерживается, и скроллинг, и прочая хуйня
