### ISSUE TITLE
Нужно импортнуть Event в ВК

### ISSUE THREAD

**Issue by Procybit** [IgorTimofeev/MineOS#507]
![](https://i.gyazo.com/2f2d6601d6877101aa56c59747ad13b3.png])

(Это клиент ВК)
Надо в верх главного файла дописать
`local event = require("Event")`
проверил, работает

**Comment by MrFredber** [comment]
Так в чём проблема? создай pull request, где ты вписываешь эту строчку.
Profit.

**Comment by Procybit** [comment]
> Так в чём проблема? создай pull request, где ты вписываешь эту строчку. Profit.

А приложения разве не отдельно от ОСи поставляются?

**Comment by MrFredber** [comment]
> А приложения разве не отдельно от ОСи поставляются?

Обновления поставляются с сервера Игоря, а при чистой установки оськи все приложения скачиваются с гитхаба. При этом, когда ты комичишь в гитхаб обновление проги - обновление появляется и в магазине приложений (не знаю, Игорь ли сам копипастит обновление, или скрипт так делает)
Я так обновление делал для приложения погоды

**Comment by MrFredber** [comment]
Погоди, а снизу end разве не лишний?
![image](https://user-images.githubusercontent.com/33953266/204138129-d65d2933-de0c-4432-87a5-2f69092082a2.png)

**Comment by MrFredber** [comment]
а, ты строчку снизу удалил. Сорянба

**Comment by IgorTimofeev** [comment]
![image](https://user-images.githubusercontent.com/11760002/204138243-b66be4ba-21e8-40d1-baf2-c61b94852852.png)

**Comment by Procybit** [comment]
> а, ты строчку снизу удалил. Сорянба

это не я, это всё гитхаб)

**Comment by MrFredber** [comment]
всм ты закрыл закрытый issue? как?
> это не я, это всё гитхаб)

а, ну хотя можешь не отвечать

**Comment by IgorTimofeev** [comment]
> а, ну хотя можешь не отвечать

![image](https://user-images.githubusercontent.com/11760002/204140088-24d980d3-31d6-4ca5-b037-8f98763aa7a3.png)
