### ISSUE TITLE
Насчёт App Market'а...

### ISSUE THREAD

**Issue by Procybit** [IgorTimofeev/MineOS#509]
Кто знает, ответьте плз
1. Где и на чём он хостится?
2. Как восстановить пароль (не спрашивайте, сам не знаю)?
3. Кто "ответственный" за App Market?

**Comment by MrFredber** [comment]
1) https://youtu.be/drklO7W61GU
2) Никак. Только если Игоря упросить
3) Игорь.

**Comment by Procybit** [comment]
спс
