### ISSUE TITLE
supervisor error

### ISSUE THREAD

**Issue by ProffessionalNoob** [IgorTimofeev/MineOS#513]
when i use "supervisorctl start mineos" i get a spawn error and when i do "supervisorctl status" it gives a fatal error and i dont know how to fix it.
i installed mine os with debian (no gui) .

**Comment by Procybit** [comment]
I think you've confused two different products with the same name.

Here is the github repository of a fun virtual operating system for the minecraft mod (the OpenComputers mod allows you to do this). Just look at the [main page](https://github.com/IgorTimofeev/MineOS#readme) :)

And about your issue, I think you need to go [here](https://discourse.codeemo.com/).

Good luck with solving the problem!
