### ISSUE TITLE
(Not issue) hi!

### ISSUE THREAD

**Issue by f908** [IgorTimofeev/MineOS#514]
Will you give out an tutorial how to host your own app market server? becuase the default one is down as i'm writing this.

**Comment by IgorTimofeev** [comment]
AppMarket sources are proprietary, so no

![image](https://user-images.githubusercontent.com/11760002/208230559-953b76da-2345-4d09-bdf5-7d7866513538.png)

**Comment by f908** [comment]
> AppMarket sources are proprietary, so no
> 
> ![image](https://user-images.githubusercontent.com/11760002/208230559-953b76da-2345-4d09-bdf5-7d7866513538.png)

Ok thanks.

**Comment by CoolCat467** [comment]
@f908 If you understand Russian, some information about how it is hosted is available in the video https://www.youtube.com/watch?v=drklO7W61GU&t=652s . Also see https://github.com/IgorTimofeev/MineOS/issues/504 for information regarding creating your own system.
