### ISSUE TITLE
MineOS: "Web request failed : unknown host"

### ISSUE THREAD

**Issue by PoivronPoivreux** [IgorTimofeev/MineOS#515]
Hello, I have a problem because when I launch the App Market a message appears telling me "Web request failed : unkown host" would you have a solution ?

**Comment by Bumer-32** [comment]
Maybe the mineos server is blocked in your country

**Comment by SerSquirt** [comment]
This happens to me too. Really annoying because I can't download any software for MineOS!

**Comment by PoivronPoivreux** [comment]
MineOS don't works in which countries?

**Comment by IgorTimofeev** [comment]
@PoivronPoivreux In addition to countries-specific issues, the problem may be with a friend who kindly provided the  [mineov.modder.pv](http://mineos.modder.pw/) domain.

All this is hosted without any guarantees, and if any of the layers "dies" - we just need to wait ¯\\_(ツ)_/¯
