### ISSUE TITLE
Colors got messed up

### ISSUE THREAD

**Issue by LittleTimmy52** [IgorTimofeev/MineOS#517]
so... I try to use the zorya boot loader like thing, It did something to the eeprom, it all broke lets say, i try many times to get the eeprom back to normal, then i just put a new one in, but wait, that wont work, so... in effort to keep my data, i put a new disk, and save the old one, i install mineos, but shut it down after its done flashing the eeprom, i put the old disk back in, boom its all working but the colors were broke, the grey on the lock screen was a brown and all the applications using light grey went dark purple, essentially #e1e1e1 and #2d2d2d no longer showed as the 2 greys but as the aforementioned brown and purple, so i put all new components and with a new disk install mineos and its still broken, I broke the case and put a new one and nothing worked. what am i to do

**Comment by LittleTimmy52** [comment]
I DID IT AFTER MY HOURS OF FIDDELING, i didnt need to resort to posting this.

to those who wonder how i fixed it, the open os i installed first was somehow messed up so... i got a new one and all is well

**Comment by IgorTimofeev** [comment]
relax bro drink a cup

![image](https://user-images.githubusercontent.com/11760002/209464452-f96a1c34-87c7-4591-8538-c595a20715fc.png)
