### ISSUE TITLE
🛑 Cannot install MineOS

### ISSUE THREAD

**Issue by KryptonMiner** [IgorTimofeev/MineOS#521]
![image](https://user-images.githubusercontent.com/79050258/214288891-adb93ca6-91b5-4acf-914b-e4b886eb3573.png)
![image](https://user-images.githubusercontent.com/79050258/214288902-be74ceca-5071-4da8-ac5c-6a15b2ebda22.png)

**Comment by MihlanDOta** [comment]
I have the same issue. Have you solved it?

**Comment by Def-Try** [comment]
Can you provide more information about computer and minecraft itself? Like components connected, lua architecture, minecraft version and given RAM.

**Comment by TheSainEyereg** [comment]
[That is it](https://github.com/IgorTimofeev/MineOS/commit/517df14cb78eb30387e265790fa44b950b449608)

**Comment by IgorTimofeev** [comment]
Fixed in #545

**Comment by zortordor** [comment]
Получаю эту же ошибку. BIOS при установке ломается.
