### ISSUE TITLE
Suggestion, remote control MineOS computer with a T2 tablet and/or a boiled down version of MineOS for one

### ISSUE THREAD

**Issue by LittleTimmy52** [IgorTimofeev/MineOS#522]
I like MineOS, but its not really portable, I can barley run it on a maxed out T3 computer, so a T2 tablet probly wont run well. Please consider this suggestion to make some boiled down version or some form of remote desktop. Thanks.

**Comment by IgorTimofeev** [comment]
Too much icons to redraw, too much work for abandoned project, sorry

**Comment by LittleTimmy52** [comment]
Well ok then
