### ISSUE TITLE
io.read() apparently wont work

### ISSUE THREAD

**Issue by LittleTimmy52** [IgorTimofeev/MineOS#526]
I've been trying to make a simple console script that takes an input, but i cant use io.read(), ive looked and tried, but I cant get it to take input other thsan with ..., but i cant put that in a function for some reason and thats where i have io.read()

**Comment by IgorTimofeev** [comment]
But there's no io library here

**Comment by LittleTimmy52** [comment]
Yes i was aware of this, i tried just slapping the io and some other
library for Io both from openos but it never worked. All i wish to know is
how i can take console input.

**Comment by CoolCat467** [comment]
There is no console in MineOS. Read [wiki](https://github.com/IgorTimofeev/MineOS/wiki) about how interacting with users in MineOS is done.

**Comment by IgorTimofeev** [comment]
Yep, it's a UI-only OS. Use text inputs, buttons, etc.

**Comment by LittleTimmy52** [comment]
Ok then thanks.
