### ISSUE TITLE
ОС может сломаться во время обновления

### ISSUE THREAD

**Issue by Def-Try** [IgorTimofeev/MineOS#527]
Если выйти из игры/выключить компьютер во время обновления скриптов ОС/установки ОС на компьютер, комп может не запуститься.

Предложение: 
 Во время установки перепрошивать EEPROM только после скачки и установки всех файлов.
 Во время обновления системы заменять скрипты только после того как всё скачается.

**Comment by IgorTimofeev** [comment]
Во время установки - вряд ли, биос и так прошивается на самом последнем этапе, когда все системные файлы загружены и готовы к работе. Если установка была прервана, то при вторичном включении она автоматически повторится

А касаемо замены после скачивания - хорошая мысль, и попутно к ней было бы замечательно прикрутить сверку хеш-сумм после скачивания (либо хардкодить их в Files.cfg, либо брать напрямую через API гитхаба).

НО ЕСТЬ НЮАНС: ЛЕНЬ

![image](https://user-images.githubusercontent.com/11760002/220308108-9dca7796-ab27-4f53-9cd0-0c4140b5fcf1.png)

**Comment by IgorTimofeev** [comment]
Сначала прошивается биос-установщик ОС, а не биос самой ОС. Это необходимо на случай "подмены" дефолтных функций сторонними ОСями, внедряющих свои фичи (типа event/thread в OpenOS) и препятствующих нормальному функционированию майноськи

Т.е. даже если что-то пойдёт не так - биос-установщик будет траить установку до скончания веков. Хз, как это сделать иначе, не конфликтуя с другими ОСями, поэтому ВОТ

**Comment by Def-Try** [comment]
Может быть завтра скину процесс установки в виде видео, вдруг что-то не так понял. Но если на словах, то идёт установка по шагам:
Загрузка > Выбор языка > Выбор диска > Создание пользователя > Прошивка EEPROM > Установка ОС > Перезагрузка.
Да, из OpenOS прошивается сначала биос-установщик, но после создания пользователя перед установкой файлов прошивается MineOS EFI.

**Comment by Def-Try** [comment]
Прямо сейчас прочитал Installer/Main lua, в стадии загрузки(Downloading) сначала идёт прошивка EEPROM и только потом установка файлов

**Comment by Def-Try** [comment]
![Screenshot_20230222-220212~2](https://user-images.githubusercontent.com/71168720/220662007-21d90c1c-a0d5-472d-aa0f-2909fe59b095.png)
(вот скрин)

**Comment by IgorTimofeev** [comment]
Бля, много буков, сложна, похуй
