### ISSUE TITLE
Market Servers Down

### ISSUE THREAD

**Issue by A2d3e2** [IgorTimofeev/MineOS#531]
The market servers keep timing out, I have tried this on multiple networks and it will still not connect to [http://mineos.modder.pw/](http://mineos.modder.pw/)

**Comment by chocovannii** [comment]
Agreed. No reply from market servers. Does anyone has a backup repository?

**Comment by IgorTimofeev** [comment]
Apparently, the host decided to die just a day after I left for vacation xd

all sources and backups are on home computer, so rip market for a long while

**Comment by A2d3e2** [comment]
Oh well, have a good vacation then. Notifiy us when you get home and get the servers back up and running 👍

**Comment by IgorTimofeev** [comment]
Thanks ❤️

**Comment by IgorTimofeev** [comment]
> You know if MCModder is trying to get this server back or not

MCmodder is my friend who gave me the subdomain for free use. The market is hosted on my home server, which is down. What happened there - who knows. Maybe the drive died or a relay tripped due to network congestion. I'll find out when I get home in 3-7 months

**Comment by IgorTimofeev** [comment]
It should work now 🐢
