### ISSUE TITLE
Сломанная вкладка Хоткеи Picture edit

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#532]
![image](https://user-images.githubusercontent.com/79054301/224415424-a4db4435-6e6f-4a2a-96a3-847191d9bab7.png)
вылазит при нажатии на вкладку хоткеи в Picture edit

**Comment by IgorTimofeev** [comment]
Пиздец хд

![image](https://user-images.githubusercontent.com/11760002/236191152-7e4c0ef6-6211-4df4-b201-6b39ba82af15.png)

Исправлено, спс!
