### ISSUE TITLE
How am I able to use Arguments?

### ISSUE THREAD

**Issue by Mad-Mushroom** [IgorTimofeev/MineOS#535]
Good Evening,
I am trying to open a Lua program (in MineOS) with arguments, but I don't know how. The Lua way with the table "arg" doesn't work...
In depth I#m trying to pass a layout of a window to another program so it can draw in the other window (i know it sounds dump).
But I do not know how to use Arguments...

Thanks a lot for Help :D
Also thanks to _IgorTimofeev_ for replying so fast on Issues :)

- MadMushroom

**Comment by IgorTimofeev** [comment]
```lua
local args = {...}
```

You can also take a look here:
https://github.com/IgorTimofeev/MineOS/wiki/System-API#systemparsearguments-table-arguments-table-options

And here:
https://github.com/IgorTimofeev/MineOS/blob/47ecff679e712aebd6248a79d9602327a0fcbb94/Applications/Finder.app/Main.lua#L11
https://github.com/IgorTimofeev/MineOS/blob/47ecff679e712aebd6248a79d9602327a0fcbb94/Applications/Finder.app/Main.lua#L611-L615

**Comment by Mad-Mushroom** [comment]
Thank you :D
