### ISSUE TITLE
Feature request: Exportable app install json

### ISSUE THREAD

**Issue by cadergator10** [IgorTimofeev/MineOS#536]
This kind of has to do with the site being down. But if there was a way to create a JSON which you can import into the app market to download all of the required files and stuff when the server is down, that would be helpful. It could also help for private apps you may want to only use yourself and don't necessarily want to publicize.

**Comment by IgorTimofeev** [comment]
Too much work for dead project, sorry

**Comment by PublicVoidUpdate** [comment]
So Mineos is confirmed dead? Damn.

**Comment by IgorTimofeev** [comment]
Yep, it's been 4 years now :d

**Comment by CoolCat467** [comment]
@cadergator10 This script will save app installation data as json file (using my new library): https://github.com/CoolCat467/MineOS-Market-Client/blob/main/examples/export_app_install_json.py
