### ISSUE TITLE
MineOS Website

### ISSUE THREAD

**Issue by cadergator10** [IgorTimofeev/MineOS#538]
This is less of an issue report and more of a question. i was wondering if in the future I could make a website for the MineOS applications?

[It would be something similar to this except more towards the MineOS system and better as I learn ASPNET](https://cadespc.com)

The reasoning for why I'm asking is kind of just for fun and also to make adding apps in MineOS easier. The main issue I have with MineOS is that in order to make changes to your application you have to load up minecraft and do it all in there. Plus its a little limited in what you can change in some cases (eg: changing a little bit of the description means rewriting it all)

I wouldn't be able to do it soon tho, as I'm working on my website and program atm, but I'm available.

**Comment by IgorTimofeev** [comment]
Interesting idea. Do you want to use App Market API or design your own database/API like  Galaxy Store / TapTap instead of Google Play?

**Comment by cadergator10** [comment]
> Interesting idea. Do you want to use App Market API or design your own database/API like Galaxy Store / TapTap instead of Google Play?

I was gonna try and make it around the App Market API that's already set up. That way, it could work off of the same SQL databases and also so I wouldn't need to modify the app market code. I have some ideas on how to make it, but it'll come up as I start work on it

**Comment by IgorTimofeev** [comment]
Okay, good luck then! API is pretty shitcoded xd

**Comment by cadergator10** [comment]
lol I can always make a new API. I just would have to figure out a way to convert the old SQl stuff to the new database so no data is lost and stuff.

**Comment by IgorTimofeev** [comment]
DB structure & data will not be available until i return home, so meow

**Comment by cadergator10** [comment]
lol all good. I got other stuff I'm working on. Trying to make a forum. Enjoy the rest of your vacation

**Comment by dnrovs** [comment]
i know this is old af but
https://github.com/dnrovs/mineos-market-web

**Comment by IgorTimofeev** [comment]
i know this is old af but
https://github.com/dnrovs/mineos-market-web

Nice work! With .pic parser it would look fantastic

**Comment by dnrovs** [comment]
> With .pic parser it would look fantastic

[done](https://mineos-market.vercel.app/publication/175)
