### ISSUE TITLE
BlueScreen after logging in 

### ISSUE THREAD

**Issue by Axor58** [IgorTimofeev/MineOS#540]
![image](https://user-images.githubusercontent.com/75118423/233798256-8702e332-2130-47ac-8b85-dd5862ce060a.png)
 Somebody who knows how to fix it ? :D

**Comment by CoolCat467** [comment]
I think I saw a similar issue to this recently, I think re-installing might help you.

**Comment by IgorTimofeev** [comment]
This is a kind of "magic" error, I can't reproduce it on either lua 5.2 or 5.3 when installing a clean system. Maybe you have some specific features of the client? Which version of the game, which forge?

**Comment by IgorTimofeev** [comment]
Fixed in #545, thanks <3
