### ISSUE TITLE
MineCode IDE is completely unusable

### ISSUE THREAD

**Issue by TheSainEyereg** [IgorTimofeev/MineOS#545]
Не юзабельная вообще. Полсле обновления системы в IDEшке сдохло выделение, а также хррен теперь что сотрешь. Если стирание доходит до начакла строки, то краш всей системы.

### Ifub djcghjbpdtkltybz^
0. Переключите раскладку.
1. Скачайте майн ось.
2. Обновите ее через маркет.
3. Запустите майн код.
4. Попытайтесь что-то стереть.

Пруф гифками (гитхаб не хочет встраивать их):
[гифка 1](https://olejka.ru/r/ad03059a2a.gif)  [гифка 2](https://olejka.ru/r/1e9516a75e.gif)

Ошибка скрином:
![pic](https://olejka.ru/s/468eb30e3e.png)

**Comment by IgorTimofeev** [comment]
Вот это я понимаю репорт! Спасибо, основную проблему пофиксил. Суть была та же, что и в иссуях #521 и #540 - криво заполнялся экранный буфер при flush, а также хуёво парсился трейс ошибок на различных хостах

Касаемо выделения/удаления текста в IDE - фиг знает, не смог отловить, всё работает в штатном режиме. Траил и с чистой установкой системы, и с апдейтом через маркет, и с precise режимом монитора. Было предположение, что из-за кривого flush система выжирала больше памяти, чем должна, что приводило к out of memory при работе с IDE, но на гифке с этим проблем нет, так что вдвойне хз

Но сейчас хотя бы система выдаст человеческую ошибку без BSOD'ов, по которой уже можно будет отладить IDE. Пусть пока иссуя висит открытой, мб кто-то выдаст дальнейшие подробности

**Comment by TheSainEyereg** [comment]
Да, спасибо, теперь комп действительно не крашит. Кстати, вот скриншот ошибки при стирании символа в MineCode IDE:
![lol](https://olejka.ru/s/99b1d2998c.png)
p.s. Майн ось была начисто установлена, после чего обновлена с маркета.

А вот что выдаст стирание символа если систему с маркета не обновлять:
![useful](https://olejka.ru/s/cd78abf48f.png

Всё же думаю, что nil в ошибке после обновления важнее будет чем ошибка в IDE

**Comment by IgorTimofeev** [comment]
С java и unicode.sub - знакомая ошибка. Полгода назад создал [иссую ](https://github.com/MightyPirates/OpenComputers/issues/3579) в репе мода - должно быть пофикшено в последних версиях. Надо либо обновлять, либо даунгрейдить мод

> system fatal error: nil

Это уже самый странный случай, т.к. система не смогла распарсить стектрейс ошибки. Чтобы хоть как-то жить дальше - она просто игнорирует её и пытается восстановить рабочее пространство. О причинах можно только догадываться

**Comment by IgorTimofeev** [comment]
Проблема инпута пофикшена спустя тыщу лет, благодарю
