### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by obvTiger** [IgorTimofeev/MineOS#548]
When running the install script i get this error:
![image](https://github.com/IgorTimofeev/MineOS/assets/83970850/faf8b8a6-1086-4a96-88ac-0fc97955581b)

this is my internet server config 
  internet {
    blacklist=[]

    enableHttp=true

    enableHttpHeaders=true

    enableHttpMethods=[]

    enableHttpRedirects=50

    enableTcp=true

    maxTcpConnections=4

    requestTimeout=0

    threads=4

    whitelist=[]
  }

**Comment by Bumer-32** [comment]
this is a problem with your computer or server, not MineOS

**Comment by MidasRX** [comment]
i have this problem too

**Comment by MidasRX** [comment]
I HAVE A SOLUTION !!! 
its a problem with the version of the mod 
the good version is : OpenComputers-MC1.12.2-1.7.7+5413028.jar
