### ISSUE TITLE
Не могу сделать апдейт ОСьки и вообще чего-либо через маркет.

### ISSUE THREAD

**Issue by Roma1825** [IgorTimofeev/MineOS#551]
Переустанавливал, делал установку на разных ПК и серваках (именно в самом мире)
ошибка следующая:
API request not succeded: Missing arguments: file_id, language_id
При попытке в разделе обновлений обновить всё, прога крашается и вылазит консоль с следующим содержимым на скрине.
![изображение](https://github.com/IgorTimofeev/MineOS/assets/28810000/92a5fd7c-6313-429a-9aa9-147214cb60f3)

**Comment by Roma1825** [comment]
Обновить ручками ОСь как-либо возможно?

**Comment by IgorTimofeev** [comment]
Не-а, только поставить с нуля. Да и незачем, ничего серьёзного в ней не обновлялось уже годами

**Comment by IgorTimofeev** [comment]
Трайнул обнову - всё ок. Хз, че там сдохло, ну и похуй

![image](https://github.com/IgorTimofeev/MineOS/assets/11760002/ff4b3d08-e4a3-4a54-8095-4500716aed15)

**Comment by IgorTimofeev** [comment]
Вероятно, какая-то отдельно взятая приложуха не хочет обновляться - но это надо в индивидуальном порядке рассматривать, с ходу сложно сказать

**Comment by Roma1825** [comment]
Окей. Откатимся к изначальному кейсу. Без ВПН эта штука в принципе ругается либо на неизвестный хост.
Врубаю ВПН - что-то грузится. Но во всех вкладках кроме Overview одинаковые значки (даже если листать страницы содержимое как-бы прогружается снова но остается прежним).
Проблема в том что оно реагирует API request not succeded: Missing arguments: file_id, language_id на попытку обновить что угодно. Не важно конкретная это прога или всё сразу.
Так что скорее всего приколюхи моего интернета чем проблема маркета скорее всего.

**Comment by Bumer-32** [comment]
не уверен конеч, но было что то похожее когда у меня сдох файл versions.cfg. к примеру во время установки приложения вырубился пк и скобочка не записалась вот и файл сдох. поможет либо вручную починить файл либо переустановить ось

**Comment by IgorTimofeev** [comment]
Спасибо за доп. инфу, я накатил временный фикс на маркет, должно работать

Проблема была актуальна только мода с версией 1.8+. В нём сломана таблица хедеров, а также некорректно устанавливается content-type во время запросов через интернет-плату. Иссуй накидал, по идее должны устранить:

https://github.com/MightyPirates/OpenComputers/issues/3617
https://github.com/MightyPirates/OpenComputers/issues/3618
