### ISSUE TITLE
OpenOS port for the GUI and image libraries?

### ISSUE THREAD

**Issue by Apfelmoes** [IgorTimofeev/MineOS#552]
Hi, i've been trying to use the legacy version of the GUI and image libraries on OpenOS for a while now. I've been struggling with countless errors, most of which i can fix myself, but a lot of the errors have to do with the image library which I have had a lot of trouble with. Is there anyone who has already ported the image or gui library?

Kind regards,
Apelmoes

**Comment by IgorTimofeev** [comment]
Yeah, I saw your sufferings in discord xd

Unfortunately, there is no stable and up-to-date port. It is quite problematic to get rid of all Minios dependencies and its specific filesystem methods like readBytes/readUnicodeChar/readTable

Probably the easiest way would be to simply copy these methods into the script layer for compatibility, or even go through autoreplacing, for example:

```lua
file:readBytes(4) -> string.unpack("> I4", file:read(4))
```

**Comment by Apfelmoes** [comment]
> Yeah, I saw your sufferings in discord xd
> 
> Unfortunately, there is no stable and up-to-date port. It is quite problematic to get rid of all MineOS dependencies and its specific filesystem methods like readBytes/readUnicodeChar/readTable
> 
> Probably the easiest way would be to simply copy these methods into some sort of compatibilty script, or just go through autoreplacing, for example:
> 
> ```lua
> file:readBytes(4) -> string.unpack("> I4", file:read(4))
> ```

I decided to try porting it anyway (and succeeded!)

I did have to port the whole filesystem library from MineOS to OpenOS but that wasn't too hard, i'll make a repo once everything is polished.
