### ISSUE TITLE
Отсутствует класс serialization.

### ISSUE THREAD

**Issue by Velonn** [IgorTimofeev/MineOS#553]
Т.к умер маркет а впн качать лень, решил написать свое приложение для сервера ну крч соц сеть. Для его работы нужны следующие классы: 
local component = require("component")
local event = require("event")
local filesystem = require("filesystem")
local internet = require("internet")
local serialization = require("serialization")
И вот как раз последний отсутствует. Какие нибудь решения, идеи?

**Comment by IgorTimofeev** [comment]
Ты путаешь майнось с опеносью:

https://github.com/IgorTimofeev/MineOS/blob/master/Libraries/Text.lua#L6

**Comment by Velonn** [comment]
> Ты путаешь майнось с опеносью:
> 
> https://github.com/IgorTimofeev/MineOS/blob/master/Libraries/Text.lua#L6

и чо делать? у меня приложение код сам есть а класса нету, прикольно было бы иметь соц сеть

**Comment by IgorTimofeev** [comment]
Ты рофлишь что ли бля

local text = require("text")

text.serialize({1, 2, 3})
text.deserialize("{1, 2, 3}")
