### ISSUE TITLE
Отсутствуют необходимые файлы при установке Ray Walk в App Market

### ISSUE THREAD

**Issue by MrFredber** [IgorTimofeev/MineOS#554]
После обновления игры от @MrPixel92 игру нельзя установить через App Market. Надо бы добавить зависимостей.
![image](https://github.com/IgorTimofeev/MineOS/assets/33953266/eea203a4-988b-4053-87ac-c33e02d41038)

**Comment by Smok1e** [comment]
Пофиксил
