### ISSUE TITLE
error Unable to install it on a multiplayer server

### ISSUE THREAD

**Issue by Ilemath217** [IgorTimofeev/MineOS#555]
Hello
 solo it works but when I want to do it on my own Minecraft server which is running on a pterodactyl instance When I paste the command j directly an error and after the opencamputer computer goes blue screen how can I fix the problem? please

**Comment by MrFredber** [comment]
No one can help you without the error information on the bluescreen. Can you take a screenshot?

**Comment by misha99fr** [comment]
i think, he means, access error, when paste the install command on mc server, The OpenPC reboots and shows error

**Comment by Ilemath217** [comment]
Here is what it does to me precisely from my local server I specify is the first time that I have this type of error to install mineos

Video :
http://mc-serv.freeboxos.fr:3000/api/shares/QzODY4M/files/9bedff9a-01bf-4970-b789-bce90bf58b34?download=false

**Comment by misha99fr** [comment]
oh, i have the same trouble

**Comment by Ilemath217** [comment]
in fact the problem is the first time it's happened to me this kind of thing in multiplayer I think it just can't download the files because of security but how to authorize I don't know
