### ISSUE TITLE
App makert

### ISSUE THREAD

**Issue by Programivan** [IgorTimofeev/MineOS#557]
Hello why app makert don't working

**Comment by IgorTimofeev** [comment]
Hello ok fuck it

**Comment by Programivan** [comment]
Hello.I'm playing singleplayer and don't working App Makert Why???

**Comment by Programivan** [comment]
in Ukraine

**Comment by Programivan** [comment]
And add please internet browser

**Comment by IgorTimofeev** [comment]
Idk really bro, host is located in Russia & current geopolitical fuck up allows normal people like us to do business like this(
