### ISSUE TITLE
Где в MineOS, находиться программа InfoPanel

### ISSUE THREAD

**Issue by misha99fr** [IgorTimofeev/MineOS#559]
Мне просто для моего сервера надо

**Comment by MrFredber** [comment]
Если ты не нашёл его в маркете, значит его надо вручную скачать с гитхаба в папке Applications

**Comment by MrFredber** [comment]
А, его нет в этой папке. Значит надо поискать в старых версиях этой папки.

**Comment by misha99fr** [comment]
спасибо большое

**Comment by IgorTimofeev** [comment]
Если старые версии панельки найдутся - не факт, что они будут совместимы с актуальной версией гуйки. Придётся вручную шлифовать напильником
