### ISSUE TITLE
Вопрос(не проблема)

### ISSUE THREAD

**Issue by misha99fr** [IgorTimofeev/MineOS#562]
Хотелось спросить, а будет ли порт MineOS, под Opencomputers 2?

**Comment by MrFredber** [comment]
Во-первых: OpenComputers 2 уже заброшен, т.к. последний коммит был год назад
Во-вторых: основная разработка MineOS уже давно была завершена, а это значит, что кроме мелких багфиксов Игорь(основатель ОС) ничего другого делать не будет.

Если тебе интересно, то ты сам можешь сделать порт. Никто тебе этого не запрещает.

P.S. если ты реально будешь делать порт - тебе обязательно надо будет ссылкой указать на этот репозиторий, что оригинальная ос находится здесь.

**Comment by misha99fr** [comment]
Хорошо, спасибо
