### ISSUE TITLE
иконки не фиксируються на рабочем столе

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#569]
если иконки перетаскивать по рабочему столу, то после перезапуска всё сброситься как было.
так понимаю это из того что после перетаскивания в файлике .icons ничего не происходит...
может добавить что то по типу кнопки "сохранить расположение иконок" в контекстное меню?

**Comment by IgorTimofeev** [comment]
По задумке оно должно сохраняться в .icons автоматически, хз, почему этого не происходит. Над чекнуть

**Comment by Smok1e** [comment]
Пофиксил
