### ISSUE TITLE
чё за нахрен

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#572]
![зображення](https://github.com/IgorTimofeev/MineOS/assets/79054301/2d241e98-fa77-4a68-abd7-a9f7b9cf1050)
значиться увидел я изминения в апп маркете - скачал вручную новую версию и получил вот это! что это блет? кстати подключиться я так и не смог, грузит грузит и ошибка реквест таймоут после которого интерфейс встаёт в норму

**Comment by Bumer-32** [comment]
А, тут такой ещё прекол - загрузилось всё с впном но почему если перейти на домен http://mineos.buttex.ru/MineOSAPI/2.04/ то там какой то бред вместо старой надписи?

**Comment by Smok1e** [comment]
Сервак упал, завтра будем фиксить

Адрес, кстати, в Украине может не работать, блочат на кой то хуй без разбору айпишники из рф

**Comment by Smok1e** [comment]
> А, тут такой ещё прекол - загрузилось всё с впном но почему если перейти на домен http://mineos.buttex.ru/MineOSAPI/2.04/ то там какой то бред вместо старой надписи?

а не похуй ли кому-то на эту надпись? ладно, заодно и это пофиксим

**Comment by CoolCat467** [comment]
Sort of hijacking this conversation, but would it be possible to support `@duck.com` domains for the `register` script? [@duck.com info page](https://duckduckgo.github.io/duckduckgo-help-pages/email-protection/what-is-duckduckgo-email-protection/)

**Comment by Smok1e** [comment]
> Sort of hijacking this conversation, but would it be possible to support `@duck.com` domains for the `register` script? [@duck.com info page](https://duckduckgo.github.io/duckduckgo-help-pages/email-protection/what-is-duckduckgo-email-protection/)

There is a whitelist of domains, but i can add duck.com if you want so.

**Comment by CoolCat467** [comment]
> > Sort of hijacking this conversation, but would it be possible to support `@duck.com` domains for the `register` script? [@duck.com info page](https://duckduckgo.github.io/duckduckgo-help-pages/email-protection/what-is-duckduckgo-email-protection/)
> 
> There is a whitelist of domains, but i can add duck.com if you want so.

That would be great yes

**Comment by Smok1e** [comment]
@Bumer-32, Поднял апиху, с впном должно работать.

@CoolCat467, Now you should be able to use **@duck.com** email to register a MineOS account. Have a nice day!
