### ISSUE TITLE
when starting wget -f, the BIOS crashes

### ISSUE THREAD

**Issue by Menellan** [IgorTimofeev/MineOS#573]
<img width="1254" alt="image" src="https://github.com/IgorTimofeev/MineOS/assets/149504292/8c7c7244-6d39-4fde-8380-f9fbef4caf93">

**Comment by Menellan** [comment]
I'm playing on server 1,12,2

**Comment by IgorTimofeev** [comment]
Seems like something blocks downloading of BIOS source code. Maybe github is blacklisted on your server, maybe some proxy fails

**Comment by lhilo3** [comment]
I figured out the situation and the problem is on the server side

**Comment by lhilo3** [comment]
Because OpenOS 1.8.3
