### ISSUE TITLE
Hello, my issue is that I can't figure out how to install pufferfish into my server. 

### ISSUE THREAD

**Issue by iisnifffarts** [IgorTimofeev/MineOS#574]
How do I do this please answer someone and I will be very greatful!!!!!!1111111111111!11

**Comment by CoolCat467** [comment]
This is the main repository for the OpenComputers minecraft mod graphical operating system MineOS. If you are referring to how get pufferfish added to Minecraft, pufferfish were added to the game in the 1.13 Aquatic Update. If you are referring to installing some sort of MineOS application, you should be able to use the `App Market` program to install it. If you are referring to something else, this is not the right place.

[How To Get PUFFERFISH In Minecraft (And Their Uses) - YouTube](https://www.youtube.com/watch?v=nyWf5DI-Vvo)
![fugu](https://github.com/IgorTimofeev/MineOS/assets/52022020/21489dc3-10ca-41e4-83f8-5dd262511c65)

**Comment by CoolCat467** [comment]
If this is the unrelated thing, issues #453 and #245 seem to be from people looking for a similar thing.

**Comment by iisnifffarts** [comment]
> This is the main repository for the OpenComputers minecraft mod graphical operating system MineOS. If you are referring to how get pufferfish added to Minecraft, pufferfish were added to the game in the 1.13 Aquatic Update. If you are referring to installing some sort of MineOS application, you should be able to use the `App Market` program to install it. If you are referring to something else, this is not the right place.
> 
> [How To Get PUFFERFISH In Minecraft (And Their Uses) - YouTube](https://www.youtube.com/watch?v=nyWf5DI-Vvo) ![fugu](https://user-images.githubusercontent.com/52022020/279794455-21489dc3-10ca-41e4-83f8-5dd262511c65.png)

Im not talking about minecraft pufferfish im talking about the fork of paper

**Comment by CoolCat467** [comment]
> > This is the main repository for the OpenComputers minecraft mod graphical operating system MineOS. If you are referring to how get pufferfish added to Minecraft, pufferfish were added to the game in the 1.13 Aquatic Update. If you are referring to installing some sort of MineOS application, you should be able to use the `App Market` program to install it. If you are referring to something else, this is not the right place.
> > [How To Get PUFFERFISH In Minecraft (And Their Uses) - YouTube](https://www.youtube.com/watch?v=nyWf5DI-Vvo) ![fugu](https://user-images.githubusercontent.com/52022020/279794455-21489dc3-10ca-41e4-83f8-5dd262511c65.png)
> 
> Im not talking about minecraft pufferfish im talking about the fork of paper

https://github.com/pufferfish-gg/Pufferfish seems to be what you are looking for then.

**Comment by iisnifffarts** [comment]
@CoolCat467 How do I create a custom profile in the webiste???

**Comment by CoolCat467** [comment]
> @CoolCat467 How do I create a custom profile in the website??? I want to do that so I can use puffer fish with it or if that is not the way tell me how!

I haven't the slightest idea. I would suggest re-opening this issue in the correct repository I listed previously, https://github.com/pufferfish-gg/Pufferfish. This is an entirely unrelated project.

**Comment by IgorTimofeev** [comment]
hmm

![image](https://github.com/IgorTimofeev/MineOS/assets/11760002/c12ee095-9f82-4425-8b98-4a10c7142c54)
