### ISSUE TITLE
Is offline install possible? 

### ISSUE THREAD

**Issue by sudo-000** [IgorTimofeev/MineOS#575]
Instead of wget from your github repo, I want to let it grab files from my own device for installation. 
I set up a file server with chfs, and typed wget -f http://127.0.0.1/chfs/shared/Installer/BIOS.lua /tmp/bios.lua. 

But this happened when I tried to do it: 
![image](https://github.com/IgorTimofeev/MineOS/assets/107282563/dd7da1eb-dda1-476c-91ab-834eb89ed332)

How can I solve this issue?

**Comment by CoolCat467** [comment]
Not completely sure off the top of my head, but I think this is an issue with the way OpenComputers itself works. From a security standpoint, it would not be safe to allow random people on a minecraft server talk to the server computer's local network addresses. There might be a configuration option for it somewhere, but I am not sure.

This is not an issue with MineOS itself.

**Comment by MrFredber** [comment]
I heard that open computers has problems with Internet addresses, so they completely blocked access to sites via http. https only

**Comment by IgorTimofeev** [comment]
You can use this
https://github.com/IgorTimofeev/MineOS/releases/tag/HDD

**Comment by PublicVoidUpdate** [comment]
you could probably put the install files on a floppy.

**Comment by Smok1e** [comment]
> Instead of wget from your github repo, I want to let it grab files from my own device for installation. I set up a file server with chfs, and typed wget -f http://127.0.0.1/chfs/shared/Installer/BIOS.lua /tmp/bios.lua.
> 
> But this happened when I tried to do it: ![image](https://private-user-images.githubusercontent.com/107282563/292792162-dd7da1eb-dda1-476c-91ab-834eb89ed332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTQ4NDYsIm5iZiI6MTcwMzU5NDU0NiwicGF0aCI6Ii8xMDcyODI1NjMvMjkyNzkyMTYyLWRkN2RhMWViLWRkYTEtNDc2Yy05MWFiLTgzNGViODllZDMzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxMjQyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWQ3YjA2ZWYzNDlmNjYwNDllNzkxNTdmZTk2ZDFhZmJlY2UzYTQ2M2JlMTMwMzdhYTcwNjAxMjIzMzBiNjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TnpjDEh5hTVlbdswsKdaAsNSlORVzy946VD_BQR4YIk)
> 
> How can I solve this issue?

The problem is that you are connecting to `127.0.0.1` (localhost) from opencomputers, which is not allowed by default by security reasons. If that was possible, any public server player could potentially get access to server's local network.

To get this actually work, you'll have to locate the opencomputers config file at `.minecraft/config/opencomputers/settings.conf` and change `"deny private"` in 675th line to `"allow private"`. Then restart minecraft and you should now be able to download this file from localhost.

![image](https://github.com/IgorTimofeev/MineOS/assets/33802666/e5c251d3-1cd5-4996-8598-1387478b62d5)

**Comment by Smok1e** [comment]
> I heard that open computers has problems with Internet addresses, so they completely blocked access to sites via http. https only

nope

**Comment by IgorTimofeev** [comment]
If you need to run installer & download files hosted on your local machine, simple sources copy-pasting won't work, because pre-installation BIOS redirects you to GitHub:
https://github.com/IgorTimofeev/MineOS/blob/master/Installer/BIOS.lua#L5

Then installer itself downloads all files from this repo anyway:
https://github.com/IgorTimofeev/MineOS/blob/master/Installer/Main.lua#L16

You'll have to overwrite them to address of your host. Btw are you really want to fuck with it?

**Comment by sudo-000** [comment]
> If you need to run installer & download files hosted on your local machine, simple sources copy-pasting won't work, because pre-installation BIOS redirects you to GitHub: https://github.com/IgorTimofeev/MineOS/blob/master/Installer/BIOS.lua#L5
> 
> Then installer itself downloads all files from this repo anyway: https://github.com/IgorTimofeev/MineOS/blob/master/Installer/Main.lua#L16
> 
> You'll have to overwrite them to address of your host. Btw are you really want to fuck with it?

I'll just do a simple search & replace to all the lua files and let them pull files from 127.0.0.1 instead of github. 
This step is easy actually.

**Comment by sudo-000** [comment]
> > Instead of wget from your github repo, I want to let it grab files from my own device for installation. I set up a file server with chfs, and typed wget -f http://127.0.0.1/chfs/shared/Installer/BIOS.lua /tmp/bios.lua.
> > But this happened when I tried to do it: ![image](https://private-user-images.githubusercontent.com/107282563/292792162-dd7da1eb-dda1-476c-91ab-834eb89ed332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1OTQ4NDYsIm5iZiI6MTcwMzU5NDU0NiwicGF0aCI6Ii8xMDcyODI1NjMvMjkyNzkyMTYyLWRkN2RhMWViLWRkYTEtNDc2Yy05MWFiLTgzNGViODllZDMzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNlQxMjQyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWQ3YjA2ZWYzNDlmNjYwNDllNzkxNTdmZTk2ZDFhZmJlY2UzYTQ2M2JlMTMwMzdhYTcwNjAxMjIzMzBiNjU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TnpjDEh5hTVlbdswsKdaAsNSlORVzy946VD_BQR4YIk)
> > How can I solve this issue?
> 
> The problem is that you are connecting to `127.0.0.1` (localhost) from opencomputers, which is not allowed by default by security reasons. If that was possible, any public server player could potentially get access to server's local network.
> 
> To get this actually work, you'll have to locate the opencomputers config file at `.minecraft/config/opencomputers/settings.conf` and change `"deny private"` in 675th line to `"allow private"`. Then restart minecraft and you should now be able to download this file from localhost.
> 
> ![image](https://private-user-images.githubusercontent.com/33802666/292871229-e5c251d3-1cd5-4996-8598-1387478b62d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDIzOTQsIm5iZiI6MTcxNTEwMjA5NCwicGF0aCI6Ii8zMzgwMjY2Ni8yOTI4NzEyMjktZTVjMjUxZDMtMWNkNS00OTk2LTg1OTgtMTM4NzQ3OGI2MmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE3MTQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNmZlOWZlYzA2ODA0MTk4ZjBkZWNlYTU0OWYyMWE2NTcwYjkzY2FjNGRiMjY5MzE3NWFmNjAxMTE3NjQ5MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HlkzsCHqbWfImIUCRDCgVCP0EiBOApW9uXbrlgVuSA0)

Thanks very much! I'll have a try editing the config when I have a chance to try that out later. 
For now I'm busy working on other things that are more important.
