### ISSUE TITLE
Not fully transparent images

### ISSUE THREAD

**Issue by 0leshe** [IgorTimofeev/MineOS#576]
Когда под изображение с прозрачностью подходит другое, у которого используются специальные символы, оно рисует его без символа: сплошной пиксель одного из двух цветов
![image](https://github.com/IgorTimofeev/MineOS/assets/125771937/23719b1b-b51e-491b-b9af-33ea150a53b7)
![image](https://github.com/IgorTimofeev/MineOS/assets/125771937/f27ab212-07cb-4dbd-b91d-bf08d6c8b0c2)

**Comment by Smok1e** [comment]
скинь пикчу с диском

**Comment by 0leshe** [comment]
[HDD.zip](https://github.com/IgorTimofeev/MineOS/files/13795746/HDD.zip)
Не знаю как кинуть её в сырую, намутил архив

**Comment by Bumer-32** [comment]
> ![image](https://private-user-images.githubusercontent.com/33802666/293419056-0af99c0d-173a-4109-89be-bb1d1c9c58b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4OTMxMjcsIm5iZiI6MTcwMzg5MjgyNywicGF0aCI6Ii8zMzgwMjY2Ni8yOTM0MTkwNTYtMGFmOTljMGQtMTczYS00MTA5LTg5YmUtYmIxZDFjOWM1OGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDIzMzM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhODFiMGU4ZDkwYjc1YzVmMmI5OTNjZjViNzMzOTlmMzc3ZTFkMTU4NTQ4YWUyOWI3ZWIwN2ExNTNlOWFjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p32O9hwMP68iPZPan2wihU1-QinA3MA-UXVmybZHxKk) Да, похоже на баг. Я думал, мб, там не прозрачный пиксель, а пробел, но там действительно прозрачный пиксель. Проще всего будет обрезать иконку до 6x4

ого эт чё за прога?

**Comment by Smok1e** [comment]
> > ![image](https://private-user-images.githubusercontent.com/33802666/293419056-0af99c0d-173a-4109-89be-bb1d1c9c58b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4OTMxMjcsIm5iZiI6MTcwMzg5MjgyNywicGF0aCI6Ii8zMzgwMjY2Ni8yOTM0MTkwNTYtMGFmOTljMGQtMTczYS00MTA5LTg5YmUtYmIxZDFjOWM1OGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDIzMzM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhODFiMGU4ZDkwYjc1YzVmMmI5OTNjZjViNzMzOTlmMzc3ZTFkMTU4NTQ4YWUyOWI3ZWIwN2ExNTNlOWFjZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p32O9hwMP68iPZPan2wihU1-QinA3MA-UXVmybZHxKk) Да, похоже на баг. Я думал, мб, там не прозрачный пиксель, а пробел, но там действительно прозрачный пиксель. Проще всего будет обрезать иконку до 6x4
> 
> ого эт чё за прога?

Пилю для себя редактор иконок

https://github.com/Smok1e/MineOSIconEdit

**Comment by IgorTimofeev** [comment]
@0leshe иконка 8x4 пикселя, а сам диск на ней 6x4, т.е. 2 пикселя по краям рисуются символом пробела, который как раз и перекрывает брайлевский символ на дискете. Заюзай инструмент crop в редакторе пикч - и будет заебись
