### ISSUE TITLE
не работает контекстное меню и менюшка с выключением/перезагрузкой/хз чем 

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#577]
новая менюшка у меня открылась но кнопашки не работают
![зображення](https://github.com/IgorTimofeev/MineOS/assets/79054301/d3cc9243-3c44-43b4-8348-04b8250c70da)
стоит заметить что я просто обновил систему не переставляя с нуля, и возможно просто какой либо файл не догрузился

кстати @IgorTimofeev обнови в маркете приложения у которых новая иконка

**Comment by Bumer-32** [comment]
контекстное меню кст работает так же
![зображення](https://github.com/IgorTimofeev/MineOS/assets/79054301/96417ae9-c8ef-416d-b7cd-2475ae450638)

**Comment by IgorTimofeev** [comment]
Ага, там какая-то либа не обновилась по ходу. Мб гуйка, мб система, похуй, поправится

**Comment by Bumer-32** [comment]
в смысле блят поправится? ты обнову кинешь или мне идти систему переустанавливать??

**Comment by IgorTimofeev** [comment]
@Bumer-32 ну дык обнова на гуйку кинута. Если прилетела, обновилась и поправилась - заебись. Если нет - похуй)0

**Comment by IgorTimofeev** [comment]
Там прост сегодня много всякого говна обновилась, мб чет проебал

**Comment by IgorTimofeev** [comment]
ТРУДНО ОТСЛЕЖИВАТЬ СИЙ КОЛОССАЛЬНЫЙ ОБЪЕМ ИЗ 5 ФАЙЛОВ, ПНИМАШ
