### ISSUE TITLE
ЦВЕТА УКРАЛИ

### ISSUE THREAD

**Issue by Bumer-32** [IgorTimofeev/MineOS#579]
![зображення](https://github.com/IgorTimofeev/MineOS/assets/79054301/be2a44c8-10f0-4130-945a-4e930a0a54ab)
осталась только 1 вариант выбора цвета, ни дока, ни контекстного меню

хз правда м.б так и задумовалось

**Comment by IgorTimofeev** [comment]
Ага, так и задумывалось
