### ISSUE TITLE
Текст в контекстном меню такой вкусненький :)

### ISSUE THREAD

**Issue by MrFredber** [IgorTimofeev/MineOS#581]
![image](https://github.com/IgorTimofeev/MineOS/assets/33953266/0ef93b2f-48bd-411f-89ae-63c02ad62ba4)
![image](https://github.com/IgorTimofeev/MineOS/assets/33953266/e8f09a98-738b-4fe1-9fd1-806d0f0a5c1e)

Может какая-то библа не обновилась? Или в GUI баг? Кста, не забудь потом GUI в маркете обновить.

**Comment by IgorTimofeev** [comment]
Втфффф, по идее это очень старая версия либы Screen, где не поддерживалась обработка unicode.isWide. Видимо, забыл обновить, да, спасибо

**Comment by MrFredber** [comment]
Ага. После обновы библы всё стало норм. Пасиб
