### ISSUE TITLE
При установке получаю ошибку. 1.12.2

### ISSUE THREAD

**Issue by FawyWolf** [IgorTimofeev/MineOS#583]
![image](https://github.com/IgorTimofeev/MineOS/assets/84247721/193ce696-dd58-4f86-9172-f994ff4ef825)

И что с этим делать?
Игорь, спаси.

P.S Играю на сервере. Сам его хосщу.

**Comment by Smok1e** [comment]
В какой ситуации возникает ошибка? Скрин ни о чём не говорит.
На какой архитектуре сервер? Не arm64, случайно?

**Comment by FawyWolf** [comment]
> В какой ситуации возникает ошибка? Скрин ни о чем не говорит. На каком архитектурном сервере? Не Arm64, случайно?

Сервер крутится на Винде. Интеловская архетиктура.
Возникает при игре на сервере, при попытке установки ОС. Сначала идет нормально(белый экран с надписью майн ос и полоской загрузки) и ближе к концу крашится. Проверил, в одиночке всё круто работает.
Сервер на Forge.
