### ISSUE TITLE
[BUG] Calculator appp crashes when the calculated number ecceds 65535

### ISSUE THREAD

**Issue by QM8782** [IgorTimofeev/MineOS#586]
**Describe the bug**
This bug is due to the character limit on the Unicode api. This only happens when the answer/input is below 0 or beyond 65535.

**To Reproduce**
Steps to reproduce the error:
1. Open the Calculator application
2. Get the number beyond 65535 or below 0
3. Error pops up

**Expected behavior**
Expect to see an "Out of range error"

**Additional context**
This is the character display issue. Please fix the issue by modifying the code so that if it exceeds the 0-65535 limit, to not show the character. This will greatly impact the app, making the user able to calaculate inputs again without the 0-65535 limit.

**Comment by Smok1e** [comment]
Fixed, thank you for report
