### ISSUE TITLE
I GOT BOOGIE BUGGO

### ISSUE THREAD

**Issue by heheyan0t** [IgorTimofeev/MineOS#587]
**Describe the bug**
the bug is described down below i have multiple bugs actually

**To Reproduce**
IgorTimoffev aint going to the next 
1. Go to 'DOTA2'
2. Go to 'CS:GO2'
3. Go to '7 days to die'
4. Go to 'Fall Guys (also known as ПАДАЮЩИЕ ПАРНИ)'

**Expected behavior**
Go play with us 

**Screenshots**
no

**Minecraft and OpenComputers version**
1.12.2

**Additional context**
stop bullying ppl on discord

**Comment by IgorTimofeev** [comment]
ANYTHING BUT ПАДАЮЩИЕ ПАРНИ
