### ISSUE TITLE
feature request: add LibDeflate

### ISSUE THREAD

**Issue by AlphaTechNinja** [IgorTimofeev/MineOS#591]
I think LibDeflate would be a good addition to the Libraries that we have, as we could compress long strings and files. This would also help with adding compression to the Compressor API. I was working on a system to compress functions in RAM so that the operating system uses less space (this would be an alternative to just offloading libraries as we can keep them in memory still).

 I hope this is added.

**Comment by CoolCat467** [comment]
Why not just add https://github.com/SafeteeWoW/LibDeflate/blob/main/LibDeflate.lua as a app market script?

**Comment by AlphaTechNinja** [comment]
I could

**Comment by AlphaTechNinja** [comment]
I just did
