### ISSUE TITLE
1.7.10 installation HTTP request failed

### ISSUE THREAD

**Issue by apschni** [IgorTimofeev/MineOS#592]
![Безымянный](https://github.com/IgorTimofeev/MineOS/assets/64983176/d2d255da-c868-46ac-842f-ac0437abe7c2)

Any thoughts? MC 1.7.10, OpenComputers 1.8.0

**Comment by Smok1e** [comment]
That seems like a problem with your host ssl settings, not MineOS or Opencomputers
