### ISSUE TITLE
Ошибка при установке 

### ISSUE THREAD

**Issue by EpsMin** [IgorTimofeev/MineOS#593]
При попытке установить MineOS вылетает исключение 
![image](https://github.com/IgorTimofeev/MineOS/assets/114768670/19d0c835-2767-402f-8ad8-40fe6314646a)
После него ПК ребутается  и у него слетает BIOS, нужно его перекрафчивать иначе ПК не запустится вновь.
Пробовал чистить блэклист ip адресов в конфиге мода, не помогло

**Comment by CoolCat467** [comment]
Try updating your computer's SSL certificates
Машинный перевод:
Попробуйте обновить SSL-сертификаты вашего компьютера.
