### ISSUE TITLE
Add ability to add custom app market servers and api docs

### ISSUE THREAD

**Issue by finnaminope** [IgorTimofeev/MineOS#594]
I was thinking of making my own app market. then i realized i would have to make everything from scratch. then i made this issue.

**Comment by finnaminope** [comment]
Im sorry for being nondiscript but thats what happened

**Comment by finnaminope** [comment]
i will probably make a cli version for MineOS first

**Comment by finnaminope** [comment]
I just realized the os development has stopped so im going to be making this in my fork. i may make a pull request eventually.

**Comment by PublicVoidUpdate** [comment]
you could probably alter the existing app if you find where the url is stored.

**Comment by IgorTimofeev** [comment]
The AppMarket API was developed while studying at the university and contains many unconventional patterns that should not be used in modern production. The source code is closed for security reasons. I don't want to waste time shutting down and cleaning up possible security breaches in a "homemade" project I did for fun 8 years ago, so sorry, bro, no sources

![image](https://github.com/IgorTimofeev/MineOS/assets/11760002/343ed056-3845-4c02-b663-1d3b6a933545)

If you still want to do some reverse engineering and dive deep into the structure of requests - go ahead, there are no rules or restrictions. If we were friends, I would have no problem sending you sources and a database dump e to analyze and reproduce the market from scratch, but... yeah

**Comment by Smok1e** [comment]
I don't think this is something that the opensource community is ready to see

![image](https://github.com/IgorTimofeev/MineOS/assets/33802666/63e1edb5-7473-4dc1-ad55-67395df8eac9)

**Comment by CoolCat467** [comment]
There is one detail I am wondering about since we are on this topic, how is statistics "most popular user" calculated?

**Comment by Smok1e** [comment]
> There is one detail I am wondering about since we are on this topic, how is statistics "most popular user" calculated?

The most popular user is the one whose publications have the most reviews number

**Comment by finnaminope** [comment]
@CoolCat467 you are a lifesaver. I actually forgot this project. I will look at the code and try it out.
