### ISSUE TITLE
Установка заканчивается ошибкой

### ISSUE THREAD

**Issue by zortordor** [IgorTimofeev/MineOS#595]
После запуска комманды установки, tmp/bios.lua пустой. 
Пробовал скопировать код отсюда, вставить в bios.lua, флэшануть - тоже ошибка 

**To Reproduce**
1. Вставить одну из комманд для установки
2. Запустить

**Expected behavior**
Установка MineOS

**Screenshots**
![Jre-legacy Screenshot 2024 03 23 - 19 20 23 20](https://github.com/IgorTimofeev/MineOS/assets/129643078/74204a2a-0b14-47a0-9136-f54b5375dd94)

**Minecraft and OpenComputers version**
Майн: 1.12.2; Мод:  пробовал 1.8.3 и 1.7.7

**Additional context**
Видео в подтверждение:
https://youtu.be/jR7jox7bqTE

**Comment by zortordor** [comment]
https://youtu.be/4K29Q-1r-eQ 
Тут пробую скопировать код в новый файл и запустить комп с ним

**Comment by zortordor** [comment]
Мисклик, сори

**Comment by MrFredber** [comment]
У тебя папка /tmp пустая? Если нет, то очисти её и попробуй заново установить ос

**Comment by zortordor** [comment]
> У тебя папка /tmp пустая? Если нет, то очисти её и попробуй заново установить ос

Пробовал, компы полностью новые делал - не помогло

**Comment by Smok1e** [comment]
Для установки майноси запусти команду 
`wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/BIOS.lua /tmp/bios.lua && flash -q /tmp/bios.lua && reboot`

или `pastebin run PDE3eVsL`.

Чтобы вставить в терминал текст, нажми клавишу **insert** или на колёсико мыши

На видео ты качаешь прошивку установщика для EEPROM через http, а не через https. В этом случае файл /tmp/bios.lua - пустой. Почему не работает на втором видосе - хз, для начала попробуй поставить ось правильной командой

**Comment by zortordor** [comment]
Через https ошибка в консоли, что-то про безопасность. Скрины залью позже.

**Comment by IgorTimofeev** [comment]
@zortordor если про pkix, то https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ
