### ISSUE TITLE
Converting .PIC to .PNG or comparable filetype

### ISSUE THREAD

**Issue by cadergator10** [IgorTimofeev/MineOS#597]
Hello, so I for the life of me couldn't find any way online to convert the .PIC file type to another one that is compatable with a web browser. Is there anything known that is capable of doing this, preferably using C# but anything really works?

**Comment by Smok1e** [comment]
There is no converters at the moment, but the format is very simple. You can use sources from [this](https://github.com/Smok1e/OCIFEdit) repo, which can load OCIF (.pic) images and export them to png and implement your own converter

**Comment by CoolCat467** [comment]
I have one I wrote in Python that you could likely adapt [this script I made a while ago](https://github.com/CoolCat467/MineOS-Python3-Port/blob/main/Helpers/brail_image.py)

**Comment by cadergator10** [comment]
Thank yall! This'll help an absolute ton!
