### ISSUE TITLE
Mine OS not installing because of invalid certification blablabla

### ISSUE THREAD

**Issue by pipoulard** [IgorTimofeev/MineOS#598]
okay so i want to install Mine OS in my computer and i have the error "HTTP request failed: /bin/vget.lua:72: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"
![Capture d'écran 2024-04-06 190751](https://github.com/IgorTimofeev/MineOS/assets/128543734/b4d40a2d-1c3d-46bd-b5f1-44524292b77c)
(doesn't work with the pastbin)

i searched in internet and i learned that was a problem with the web certificate (internet explications are not clear) so i tried by multiples ways to add the intallation website certificate in java and this error is still here. 

A year ago i never had this problem and i don't understand how it happened and why i can't fix it 
and also the others posts talking about it are not helping at all (did anyone tried to install Mine OS those last month ??)

quite annoying
pls help me

java version : Version 8 Update 401
opencomputers version : 1.8.3
minecraft : 1.12.2

**Comment by pipoulard** [comment]
why did this label came up here ?

**Comment by CoolCat467** [comment]
Label comes from https://github.com/IgorTimofeev/MineOS/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by pipoulard** [comment]
> Label comes from https://github.com/IgorTimofeev/MineOS/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

okay thx but that was not the main question lol

**Comment by IgorTimofeev** [comment]
@pipoulard Its just virgin java shitting & crying about old ssl certificates while sending http requests, see here how to fix this:
https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ
