### ISSUE TITLE
App Market API is review helpful votes doesn't always match up with listed total

### ISSUE THREAD

**Issue by CoolCat467** [IgorTimofeev/MineOS#599]
Why is it that `reviews` market api endpoint has conflicting data about number of helpful votes sometimes? For example, review id `216` says following:
```lua
{
    comment="fe",
    rating=4,
    timestamp=1521012231,
    user_name="Parlocameon",
    votes={
        negative=0,
        positive=1,
        total=5
    }
}
```
Votes says there are 1 positive vote and 0 negative votes, but somehow total is 5 votes? Does that mean there were 4 votes that were deleted or something?

**Comment by IgorTimofeev** [comment]
Where did you found "negative" field? The `reviews` endpoint query code is

```sql
SELECT
  reviews.id,
  reviews.rating,
  reviews.comment,
  UNIX_TIMESTAMP(reviews.timestamp) AS `timestamp`,

  users.name AS user_name,

  (
    SELECT CONCAT(
      '{total=',
      COUNT(reviews_votes.rating),
      ', positive=',
      SUM(reviews_votes.rating),
      '}'
    )
    FROM reviews_votes
    WHERE reviews_votes.review_id = reviews.id
  ) AS votes
FROM
  reviews
  LEFT JOIN users ON reviews.user_id = users.id
  LEFT JOIN publications ON reviews.publication_id = publications.id
  LEFT JOIN files ON file_id = files.id
WHERE files.id = $fileID
ORDER BY reviews.id DESC
LIMIT $offset, $count
```

Btw API is non-opensource, shitty-coded, and no further help with it will be provided. So if you need, do reverse engineering by yourself xd

**Comment by CoolCat467** [comment]
Thank you, sorry, I should have looked closer into the actual response on my end instead of making assumptions.
