### ISSUE TITLE
Неработает магазин в MineOS версия 1.12.2

### ISSUE THREAD

**Issue by Maximkasup** [IgorTimofeev/MineOS#602]
![Снимок экрана 2024-04-17 105748](https://github.com/IgorTimofeev/MineOS/assets/136704071/6e259e42-8cc3-42ab-98db-93a14b636565)

**Comment by Bumer-32** [comment]
это точно не проблема с сервером т.к. он вообще то работает.
у тебя интернет карта работает? что нить скачать можешь по прямой ссылке?
так же возможно что сервер в твоей стране заблочили (как у меня), ***попробуй юзать впн***. хотя кстати у меня ошибка друга - connection time out т.к. я подключиться не могу и время ожидания подключения выходит

**Comment by Maximkasup** [comment]
[ это точно не проблема с сервером т.к. он вообще то работает. у тебя интернет карта работает? что нить скачать можно по прямой ссылке?] Да. Качает с пастебин карта работает

**Comment by Maximkasup** [comment]
Кстати на 1.7.10 работает магазин

**Comment by Bumer-32** [comment]
Майнось переустановить пробовал?

**Comment by Maximkasup** [comment]
Да

**Comment by Bumer-32** [comment]
тогда я хз, я в сети OC не особо шарю и не могу понять что случилось. возможно чёт блокает. если кстати ты играешь на сервере возможно это сервер блокирует что либо. нужно звать кого то кто шарит - @IgorTimofeev

**Comment by IgorTimofeev** [comment]
Да я сам хуй знает. Если пастбин работает - это не означает, что другие сервисы будут. Мб в конфиге прописан вайтлист хостов, мб провайдер охуел, мб ещё что-то.

Трайни маркетовскую апиху: https://mineos.buttex.ru/MineOSAPI/2.04/publications.php
Если с браузера работает - то надо конфиги майна смотреть. Если нет - то впн поможет

**Comment by Maximkasup** [comment]
Да пробовал

**Comment by Maximkasup** [comment]
с vpn запускает сайт в браузере,
без пишет что такого сайта нету.

**Comment by IgorTimofeev** [comment]
Ну, тогда, впн или смена провайдера решит вопрос. Гулаг!1

**Comment by Bumer-32** [comment]
Бля, изначально же сказал  - юзай впн
