### ISSUE TITLE
Computer halted

### ISSUE THREAD

**Issue by portex7000** [IgorTimofeev/MineOS#605]
**Describe the bug**
When i run install command, it blue screens with error 'computer halted'. (and i need to replace EEPROM)

**To Reproduce**
1. pastebin run PDE3eVsL
2. Computer halted

**Expected behavior**
I expect it to work

**Screenshots**
![image](https://github.com/IgorTimofeev/MineOS/assets/150171265/c30c55d0-6766-4ecc-b853-4b5090ebf93b)

**Minecraft and OpenComputers version**
MC: 1.12.2 MOD: 1.8.5

**Additional context**

**Comment by DBTech77** [comment]
Im having this issue as well, been searching for 2 days now and cant find a fix

**Comment by CoolCat467** [comment]
@portex7000 What do you mean by "and i need to replace EEPROM"?

**Comment by sleep0312** [comment]
一样的问题，我也是一样的步骤

**Comment by portex7000** [comment]
@CoolCat467 when this happens i need to replace EEPROM to fix it

**Comment by portex7000** [comment]
(only to get back to OpenOS)

**Comment by mc-birdie** [comment]
Seeing the same issue :'(

**Comment by CoolCat467** [comment]
Does Minecraft's logs say anything from opencomputers when this happens?

**Comment by portex7000** [comment]
@CoolCat467 No, it doesn't. Last thing berfore logging out of the world was 'Not enough energy', which was from my other opencomputers pc

**Comment by portex7000** [comment]
I can still install MineOS by copying files from the zip i download to the disk

**Comment by azugbre** [comment]
@portex7000 Hi, I got the same error. How did you copy the files of mineos to the game?

**Comment by MrFredber** [comment]
> @portex7000 Hi, I got the same error. How did you copy the files of mineos to the game?

You can use this:
https://github.com/IgorTimofeev/MineOS/releases/tag/HDD

**Comment by mentosdll** [comment]
moin hat jemand ne lösung weil ich habe genau das gleich Problem

**Comment by RagedDev** [comment]
[MineOS](https://github.com/IgorTimofeev/MineOS/releases/tag/HDD) download this go to your saves and into your world the opencomputers folder and the one with the random name then paste the content of the zip into it now restart your world and reboot the computer use cd .. and then do rename init.lua old.lua and rename os.lua init.lua restart pc and finished!

**Comment by mentosdll** [comment]
ok und wann soll es wieder funktionieren also online

**Comment by mentosdll** [comment]
> [Laden Sie dies von MineOS](https://github.com/IgorTimofeev/MineOS/releases/tag/HDD) herunter. Gehen Sie zu Ihren Speichern und in den Ordner „opencomputers“ Ihrer Welt und den Ordner mit dem zufälligen Namen. Fügen Sie dann den Inhalt der ZIP-Datei hinein. Starten Sie nun Ihre Welt neu und starten Sie den Computer neu. Verwenden Sie dazu die CD .. und benennen Sie dann „init.lua old“ um .lua und benennen Sie os.lua init.lua um, starten Sie den PC neu und fertig!

Es tut mir leid aber könnten sie so nett sein und mir es besser beschreiben was sie meinen

**Comment by RagedDev** [comment]
> > [Laden Sie dies von MineOS](https://github.com/IgorTimofeev/MineOS/releases/tag/HDD) herunter. Gehen Sie zu Ihren Speichern und in den Ordner „opencomputers“ Ihrer Welt und den Ordner mit dem zufälligen Namen. Fügen Sie dann den Inhalt der ZIP-Datei hinein. Starten Sie nun Ihre Welt neu und starten Sie den Computer neu. Verwenden Sie dazu die CD .. und benennen Sie dann „init.lua old“ um .lua und benennen Sie os.lua init.lua um, starten Sie den PC neu und fertig!
> 
> Es tut mir leid aber könnten sie so nett sein und mir es besser beschreiben was sie meinen

du must in "%appdata%/.minecraft/saves" gehen und da in deine welt und  dann in den opencomputers ordner dann bei deiner festplatte ingame must du dir den anfang der id merken und in diesen ordner gehen dann die sachen von der zip da rein kopieren und die welt in minecraft laden
dann in die konsole gehen und "cd .." dannach "rename init.lua old.lua" und "rename os.lua init.lua" fertig computer in computer mc neustarten fertig

**Comment by RagedDev** [comment]
> ok und wann soll es wieder funktionieren also online

+ schreib in englisch

**Comment by mentosdll** [comment]
When will it work normally again?

**Comment by Smok1e** [comment]
I've just tested MineOS installation in Ocelot, minecraft 1.12.2 with OC versions 1.8.3 and 1.8.5 and it goes fine. So, as long as we could not reproduce the issue, everything i can assume is that the problem is related to network and not to MineOS or OpenComputers. Try using proxy or vpn.

**Comment by mentosdll** [comment]
Mit was für einer vpn 
Und möchte es auf dem Server nutzen

**Comment by RagedDev** [comment]
do open to lan cuz on server it works
