### ISSUE TITLE
Computer halted

### ISSUE THREAD

**Issue by NORTCHOT** [IgorTimofeev/MineOS#611]
Ставлю ось с пастебина. Когда установщик пытается запустится падает в синьку
![image](https://github.com/IgorTimofeev/MineOS/assets/153174477/62de7893-c89b-4e97-9adf-e945606ea45a)

**Comment by DluxGamesHD-INC** [comment]
Have you found a fix I'm having same issue

**Comment by 6lr6lr** [comment]
Here how you can fix it:
1. Download hdd dump from:https://github.com/IgorTimofeev/MineOS/releases/tag/HDD and get .zip content
2.  Go to.minecraft/version/<your mc name>/worlds/<your world name>/  and stay folder open
3. Check your disk id in minecraft
4. Add to .minecraft/version/<your mc name>/worlds/<your world name>/<your disk id>
5. Make sure that this disk is empty
6. Put hdd dump in the disk
7. Copy OS.lua file and rename copy to init.lua
8. Run computer/server
9. And it DONE🎉🎉🎉🎉🎉🎉

**Comment by NORTCHOT** [comment]
> Run computer/server
are there servers here? ok, I'll check the method now

**Comment by 6lr6lr** [comment]
> > Run computer/server
> 
> It turns out there are servers here? ok, I'll check the method now

No i mean opencomputers server
Cuz we have in opencomputers computer and "server"

**Comment by IgorTimofeev** [comment]
Update java

**Comment by NORTCHOT** [comment]
> Update java

сяб

**Comment by NORTCHOT** [comment]
кстати, @IgorTimofeev , есть способ эту ос оптимизировать, а то не сильно плавно идет
