### ISSUE TITLE
Cant install mine os

### ISSUE THREAD

**Issue by DluxGamesHD-INC** [IgorTimofeev/MineOS#612]
Im getting the issue unrecoverbale error computer haulted when trying to install mine os on opencomputers with openos my open computers version is 1.8.5 and my minecraft version is 1.12.2

**Comment by CoolCat467** [comment]
See https://github.com/IgorTimofeev/MineOS/issues/611, this is another duplicate issue.

**Comment by DluxGamesHD-INC** [comment]
i havent gotten this fixed yet I just created this issue the other fix didnt work

**Comment by DluxGamesHD-INC** [comment]
its really irritating that its not working and I cant figure out why

**Comment by DluxGamesHD-INC** [comment]
nevermind fixed it. It was my java version lol.
