### ISSUE TITLE
Plz update MineOS hdd dump

### ISSUE THREAD

**Issue by CACKE** [IgorTimofeev/MineOS#613]
Just update plz if you can

**Comment by CoolCat467** [comment]
As of https://github.com/IgorTimofeev/MineOS/commit/26dec6fa411ec7a91ec025ab8268c1b4a66457b0 issues might be fixed

**Comment by IgorTimofeev** [comment]
@CACKE https://github.com/IgorTimofeev/MineOS/releases/tag/06.06.2024
@CoolCat467 it won't. It's even not a fix - just a prevention for errors on outdated Java version
