### ISSUE TITLE
Mine OS inside Virtual Machine for App DEVS

### ISSUE THREAD

**Issue by wwfrel4pentester** [IgorTimofeev/MineOS#614]
I'm a Lua script dev. And I want to make it easier to develop apps on **Mine OS** **through VMs**. Any solutions?? Compile to ISO perhaps? **How to install Mine OS on VM through pastebin**??
Virtual Box and VMware

**Comment by CoolCat467** [comment]
If you are talking about the minecraft server manager https://wiki.codeemo.com/, this is not the correct repository for that.

As far as I am aware, it is not possible to "compile [MineOS] to ISO", but there are [several emulator projects](https://duckduckgo.com/?q=opencomputers+emulator) that might help you.

The built-in application MineCode IDE seems to be sort of the standard for programming with MineOS.

**Comment by Smok1e** [comment]
![Pedro_Paskal_smeyotsya_potom_plachet](https://github.com/IgorTimofeev/MineOS/assets/33802666/0f574674-e8fd-442e-bd58-58b902b0f0cc)
