### ISSUE TITLE
Не устанавливается MineOS

### ISSUE THREAD

**Issue by Teamarrow32895** [IgorTimofeev/MineOS#616]
Хочу установить mine os ,ввел сначала через 
wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/OpenOS.lua /tmp/installer.lua && /tmp/installer.lua
Ввело ошибку,показанную на скриншоте
,потом ввел через pastebin,ошибка также на скриншоте

**Screenshots**
![image](https://github.com/IgorTimofeev/MineOS/assets/173059816/3b5b7152-fc8e-47c5-a878-41c2a97ac73f)

**Minecraft and OpenComputers version**
OpenComputers-MC1.12.2-1.8.3-274990f.jar

**Additional context**

**Comment by IgorTimofeev** [comment]
Update Java

**Comment by Teamarrow32895** [comment]
> Обновление Java

не помогло 

Версия Java 411

**Comment by Smok1e** [comment]
![image](https://github.com/IgorTimofeev/MineOS/assets/33802666/8e1865f7-b99b-4532-8d2a-45c089a7cd3d)

Какую версию отображает майн в f3?

**Comment by Teamarrow32895** [comment]
> ![image](https://private-user-images.githubusercontent.com/33802666/340431941-8e1865f7-b99b-4532-8d2a-45c089a7cd3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NTQ5OTgsIm5iZiI6MTcxODY1NDY5OCwicGF0aCI6Ii8zMzgwMjY2Ni8zNDA0MzE5NDEtOGUxODY1ZjctYjk5Yi00NTMyLThkMmEtNDVjMDg5YTdjZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDIwMDQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNzk0MzA3MWY5NzM0OGI5OTFmYjZkNGVmNmY1ZTQyN2YyZTc3ZmJiYTFhZmVjYTQ5OTJmOGYyMmEzNzFmNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L4NoGwS3EImKMUotifDiPM1RNAiUIJoDNjqlm2ILp7M)
> 
> Какую версию отображает майн в f3?

По возможности завтра проверю

**Comment by Teamarrow32895** [comment]
> ![image](https://private-user-images.githubusercontent.com/33802666/340431941-8e1865f7-b99b-4532-8d2a-45c089a7cd3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTIzOTAsIm5iZiI6MTcxODY5MjA5MCwicGF0aCI6Ii8zMzgwMjY2Ni8zNDA0MzE5NDEtOGUxODY1ZjctYjk5Yi00NTMyLThkMmEtNDVjMDg5YTdjZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA2MjgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNjhmYWMzM2NkOGMxMTIxYTEzZTJjMmEzYmUyODVkYzA0MGRiYWY0MDY2NmE4MjFkOTBmMzAyZDdlZDYyM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nq2u6QntrQqEQ4dn8MVY3kINVIbytRG69AgdAav1IQs)
> 
> Какую версию отображает майн в f3?

![2024-06-18_06 34 38](https://github.com/IgorTimofeev/MineOS/assets/173059816/a607a768-4bf4-439f-901d-79dddf0ff8ce)

**Comment by Teamarrow32895** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/33802666/340431941-8e1865f7-b99b-4532-8d2a-45c089a7cd3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTM0NTEsIm5iZiI6MTcxODY5MzE1MSwicGF0aCI6Ii8zMzgwMjY2Ni8zNDA0MzE5NDEtOGUxODY1ZjctYjk5Yi00NTMyLThkMmEtNDVjMDg5YTdjZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA2NDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MGUyNWQ3MjAyY2JiOGYyNzg5OGMxMWQ1ZWUwYjBhNTAwZjFhYTE5M2MyMmQ3ZTVjOGNkMTQyMTcwZTcxYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oYxdSf4P9-ykuojmHbbTXAjVImEx14zbLTQG0M7eUo4)
> 
> Какую версию отображает майн в f3?

Сможешь кинуть акутальную джаву?

**Comment by Smok1e** [comment]
> > ![image](https://private-user-images.githubusercontent.com/33802666/340431941-8e1865f7-b99b-4532-8d2a-45c089a7cd3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTIzOTAsIm5iZiI6MTcxODY5MjA5MCwicGF0aCI6Ii8zMzgwMjY2Ni8zNDA0MzE5NDEtOGUxODY1ZjctYjk5Yi00NTMyLThkMmEtNDVjMDg5YTdjZDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA2MjgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNjhmYWMzM2NkOGMxMTIxYTEzZTJjMmEzYmUyODVkYzA0MGRiYWY0MDY2NmE4MjFkOTBmMzAyZDdlZDYyM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nq2u6QntrQqEQ4dn8MVY3kINVIbytRG69AgdAav1IQs)
> > Какую версию отображает майн в f3?
> 
> ![2024-06-18_06 34 38](https://private-user-images.githubusercontent.com/173059816/340566064-a607a768-4bf4-439f-901d-79dddf0ff8ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTUyNjIsIm5iZiI6MTcxODY5NDk2MiwicGF0aCI6Ii8xNzMwNTk4MTYvMzQwNTY2MDY0LWE2MDdhNzY4LTRiZjQtNDM5Zi05MDFkLTc5ZGRkZjBmZjhjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwNzE2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmM4ODE0NTAxN2U1M2NlNmRlZmNjNzZmYjMxZTQxYWFhMTNhYzBkODY3NTliOTcwNWNmOWM1Yzg3Y2I4ZjRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0wLvhupdsgN2m2misTIBAHh84uPZqRakR2MBOxoZoK4)

У тебя майн работает на жабе 15-года, не 411, а 51. Как тебе уже сказали, обнови её. В сторонние лаунчеры джава часто встроена, поэтому даже после обновления у тебя майн может запускаться на старой. В этом случае ищи в лаунчере способ прописать путь к нормальной джаве, а если такой возможности нет, используй нормальный лаунчер, например, MultiMC.
