### ISSUE TITLE
Не могу установить Mine OS #2 обращение

### ISSUE THREAD

**Issue by Teamarrow32895** [IgorTimofeev/MineOS#617]
Хочу установить mine os ,ввел сначала через
wget -f https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/OpenOS.lua /tmp/installer.lua && /tmp/installer.lua
Ввело ошибку,показанную на скриншоте
,потом ввел через pastebin,ошибка также на скриншоте

Screenshots
![image](https://github.com/IgorTimofeev/MineOS/assets/173059816/252e290d-e840-4ea1-bb8c-a9d77be01028)

Minecraft and OpenComputers version
OpenComputers-MC1.12.2-1.8.3-274990f.jar

Additional context
Мне ответили то нужно обновить java,я обновил ,версия java-411
Все равно те же самые ошибки

**Comment by Smok1e** [comment]
#611

**Comment by Teamarrow32895** [comment]
> #611

Ссылка для дампа жесткого диска не работает
