### ISSUE TITLE
Not able to download because of my configuration file

### ISSUE THREAD

**Issue by HighonrobloxGaming** [IgorTimofeev/MineOS#619]
Is there a configuration file I am supposed to manage or it's not allowing me because of internet. I just ran it on my computer(Opencomputers) and I am getting an error: Download Server is unavaliable. Check Github.com is not blocked by your internet provider or Opencomputers Configuration file

**Comment by HighonrobloxGaming** [comment]
Any help anyone?

**Comment by CoolCat467** [comment]
See configuration file details: https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/application.conf

**Comment by Smok1e** [comment]
If you are playing in single world, then please check if https://raw.githubusercontent.com/IgorTimofeev/MineOS/master/Installer/OpenOS.lua is loading in your web browser;

If you are getting this error on a server then it is server issue and you will not be able to fix it anyway

**Comment by HighonrobloxGaming** [comment]
Well I am playing on a single world and it loads on my web browser, Should I paste onto my Opencomputers?

**Comment by HighonrobloxGaming** [comment]
That is loading in my browser

**Comment by Smok1e** [comment]
Well then it is supposed to install properly, i have no idea what is going wrong. The message you see appears when finishConnect method of internet handle fails, which usually happens when github is blocked by your network. It could also be blocked by OC configuration, try delete .minecraft/config/opencomputers/settings.cnf to ensure it is not.

**Comment by HighonrobloxGaming** [comment]
It's probably something have to do with I am using. Currently, I use the Mod on CurseForge. Maybe that would be a problem from it.

**Comment by HighonrobloxGaming** [comment]
https://private-user-images.githubusercontent.com/99602498/344451449-86381d65-feb8-4846-a74e-95bddc55ea6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMzE1NDksIm5iZiI6MTcyMDAzMTI0OSwicGF0aCI6Ii85OTYwMjQ5OC8zNDQ0NTE0NDktODYzODFkNjUtZmViOC00ODQ2LWE3NGUtOTViZGRjNTVlYTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE4MjcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYmJmMWI5ZDNiN2U5MGI0OGQ0OWE0NmZiNDMwN2Y5Mjg4ZmY4ZGZkMzdiYmExYTQwOTExZjc2YjM0YTJkNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gq4NDhH-i5y8aWr-5ays3q8LO-BGhZhTlf73307U8ZU

Same thing I have problem with.

**Comment by HighonrobloxGaming** [comment]
Image got deleted, here.
![image_2024-07-03_154040072](https://github.com/IgorTimofeev/MineOS/assets/84866936/35b09b0e-894b-4664-b915-05f5a43ff8e0)

**Comment by Smok1e** [comment]
Your java is out of date. Download latest java 8 release and make sure your launcher runs on it (version is shown at top right corner in f3 view).
