### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by tester5454** [IgorTimofeev/MineOS#623]
**Describe the bug**
This is propably a problem related to mine. but pastebin method for installing says github.com maybe blocked by your internet providor or opencomputers config file

**To Reproduce**
replacating it is just run the commands and it just gives errors instead of bringing up the installer.
i have the image that you can download in releases. but don't know how to mount it
![Screenshot 2024-07-11 160004](https://github.com/IgorTimofeev/MineOS/assets/127688610/4e9ebe9a-484f-455b-ba05-340a99770ccf)
**Minecraft and OpenComputers version**
minecraft 1.12.2 and Opencomputer is 1.8.5
if anyone can tell a guide to how to fix this or how to mount the preinstalled hard drive OS into the game

**Comment by tester5454** [comment]
oh and sometimes this
![Screenshot 2024-07-11 160515](https://github.com/IgorTimofeev/MineOS/assets/127688610/abc5ba41-f48a-4456-aed1-d163d9868135)

**Comment by Smok1e** [comment]
https://github.com/IgorTimofeev/MineOS/wiki/SSL-issue
