### ISSUE TITLE
Не получается скачать и поставить MineOS

### ISSUE THREAD

**Issue by vadimsman** [IgorTimofeev/MineOS#626]
Делаю всё в точности по инструкции сначала OpenOS, перезагрузка и ввожу команды
При первой команде получаю это 
![image](https://github.com/user-attachments/assets/74e2ee94-b411-4a73-adb3-fc30b687a14b)
Пробую вторую и получаю это
![image](https://github.com/user-attachments/assets/17f14ab4-09b6-4318-a5e3-cc77035945b4)
Искал у других решение нашёл ещё вариант там вот это
![image](https://github.com/user-attachments/assets/d25a9a40-8f00-4e7a-9b18-76b563403c27)
Потом ломается БИОС
![image](https://github.com/user-attachments/assets/53141037-9b7e-432a-abdd-5bca21de82d2)
Помогите пожалуйста решить проблему

**Comment by CoolCat467** [comment]
See https://github.com/IgorTimofeev/MineOS/wiki/Troubleshooting-(Common-problems-resolved).

**Comment by Smok1e** [comment]
https://github.com/IgorTimofeev/MineOS/wiki/SSL-issue

**Comment by vadimsman** [comment]
![image](https://github.com/user-attachments/assets/39ca44f4-3f46-438c-a058-db735f93949e)
Эта версия не подходит?

**Comment by Smok1e** [comment]
> ![image](https://private-user-images.githubusercontent.com/159170164/353517244-39ca44f4-3f46-438c-a058-db735f93949e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNTM4ODQsIm5iZiI6MTcyMjM1MzU4NCwicGF0aCI6Ii8xNTkxNzAxNjQvMzUzNTE3MjQ0LTM5Y2E0NGY0LTNmNDYtNDM4Yy1hMDU4LWRiNzM1ZjkzOTQ5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxNTMzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGYxYzRiOTQwMjNlYzg5YmE1OGIyYmE4NTU0NTljZjhiZWEzZTZlOGM3YzJlMzliY2QyYjU2NWQwNWU4ZTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2gvVn_UhQ6V8f7yS1yAAgKdqaPFk5OJozhz1tMyG07A) Эта версия не подходит?

Если ошибка при установке осталась, очевидно, нет
