### ISSUE TITLE
Web request failed: Connection refused: connect

### ISSUE THREAD

**Issue by misha99fr** [IgorTimofeev/MineOS#627]
**Describe the bug**

**To Reproduce**
1. Go to 'App Market.'
2. See error

**Expected behavior**
idk

**Screenshots**
![image](https://github.com/user-attachments/assets/86bbd96b-de5f-47dd-8446-7ba12ae17d27)

**Minecraft and OpenComputers version**
1.8.3(OC) 1.16.5(MINECRAFT)

**Additional context**
no

**Comment by CoolCat467** [comment]
Looks like App Market server is down, statistics page isn't loading: https://mineos.buttex.ru/MineOSAPI/2.04/statistics.php

**Comment by misha99fr** [comment]
oh no

**Comment by CoolCat467** [comment]
Self promotion, I re-implemented the app market server by studying the responses it gives back. If you would like to try it out, available here: https://github.com/CoolCat467/MineOS-Market-Server

**Comment by misha99fr** [comment]
thx
