### ISSUE TITLE
I think i broke it

### ISSUE THREAD

**Issue by tester5454** [IgorTimofeev/MineOS#634]
**Describe the bug**
So i was randomly browsing the app store and seeing every app and uhhh when i clicked one of the app(i will put the screenshot) it threw up this error:
![Screenshot 2024-08-12 084851](https://github.com/user-attachments/assets/4f83270e-90c8-4f56-a530-0a5f235e6927)
![Screenshot 2024-08-12 085135](https://github.com/user-attachments/assets/8d11227c-cb96-47f0-89e3-d2fc55587995)

**To Reproduce**
1. Go to the app store
2. Click on 'the app mentioned in the second screenshot'
3. See error

**Expected behavior**
open the pictures, description of the app...
**Minecraft and OpenComputers version**
1.12.2 ForgeOptifine Minecraft
1.8.5 OpenComputers mod

**Additional context**
Everytime i open it it happens

https://github.com/user-attachments/assets/49e19b58-a929-4ac2-8467-5359dc4af7f5

Oh and this program too
![Screenshot 2024-08-12 085729](https://github.com/user-attachments/assets/3b93b65d-967a-4d29-b768-0e8103a90bff)
![Screenshot 2024-08-12 085840](https://github.com/user-attachments/assets/a0dbc02b-1731-4b7c-aa9e-f2e378dce80e)

**Comment by CoolCat467** [comment]
Looks like somehow a `null` value is being sent from the Market API server as something GUI library was trying to use as an image. First, I would suggest trying to update the App Market application itself. If the issue persists, it's probably an issue with those particular publications being improperly formatted.

**Comment by tester5454** [comment]
> Looks like somehow a `null` value is being sent from the Market API server as something GUI library was trying to use as an image. First, I would suggest trying to update the App Market application itself. If the issue persists, it's probably an issue with those particular publications being improperly formatted.
