### ISSUE TITLE
Ran out of ram

### ISSUE THREAD

**Issue by tester5454** [IgorTimofeev/MineOS#635]
**Describe the bug**
This isn't exactly a bug and i shouldn't post it here. but maybe it's possible to help
So i was downloading apps from app store and it threw me this error for some of the apps
![Screenshot 2024-08-12 221522](https://github.com/user-attachments/assets/4ada5e89-ddfd-417d-bd31-4a63ede17c48)

**To Reproduce**
1.Usually for downloading heavier apps it happenes because the system runs out of ram

**Expected behavior**
Download the app correctly

**Minecraft and OpenComputers version**
1.12.2 minecraft
1.8.9 OpenComputer

**Additional context**
Is there any way to at least optimize the ram usage for the system? if there is any apps for it i would like someone to tell me
Thanks
EDIT: It made the whole system crash so i have to restart :\
![Screenshot 2024-08-12 221913](https://github.com/user-attachments/assets/97663c6e-cf56-44b1-a767-ea5089666b4b)

**Comment by tester5454** [comment]
By the way i have 2 tier 3.5 ram sticks...

**Comment by MrFredber** [comment]
2 MB of RAM is not enough for MineOS. You should move your computer parts to a server and  add 2 additional 2.5 ram sticks.

**Comment by tester5454** [comment]
Thanks
