### ISSUE TITLE
Ошибка с магазином приложений

### ISSUE THREAD

**Issue by Bufka2011** [IgorTimofeev/MineOS#637]
Открываю магазин приложений и высвечивается ошибка.

![image](https://github.com/user-attachments/assets/d3ba131d-49c6-45a4-b972-9da3c2c89404)

**Comment by CoolCat467** [comment]
This is because at the moment, response from app market server is the following HTML, which is not able to be deserialized properly as it is not a valid lua table.

```html
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by CoolCat467** [comment]
Basically it means at the moment, official app market server is down.

I have made a re-implementation of the official server by reverse-engineering its responses. It's available here: https://github.com/CoolCat467/MineOS-Market-Server

**Comment by Bufka2011** [comment]
Thank you very much!

**Comment by Smok1e** [comment]
The server is under maintenance at the moment and will go available soon
