### ISSUE TITLE
Not installing.

### ISSUE THREAD

**Issue by Lulu598** [IgorTimofeev/MineOS#640]
**Describe the bug**
I cannot install MineOs

**To Reproduce**
1. Try To install MineOs
2. Get "Download server is unavailable. Check if github is not blocked by your OpenComputers configuration file"

**Expected behavior**
MineOs Installer showing up

**Minecraft and OpenComputers version**
Minecraft 1.12.2 OpenComputers : 1.8.5

**Comment by CoolCat467** [comment]
This is likely another instance of the SSL issue. Please see https://github.com/IgorTimofeev/MineOS/wiki/SSL-issue.
