### ISSUE TITLE
mineos app store works once and then stops working 

### ISSUE THREAD

**Issue by pikachuproge** [IgorTimofeev/MineOS#641]
so first when i download a fresh install of mineos, i go to app store, i update something or download it, and then i want to install another app so i go back to the store and it freezes on the loading icon. so then i restart the pc, and its on the loading icon forever and never loads
![Screenshot 2024-08-25 181909](https://github.com/user-attachments/assets/2466a8b2-1978-4316-b83a-30e87cb3ee73)

**Comment by Smok1e** [comment]
I am unable to reproduce your problem. Also, question marks instead of normal unicode symbols on your screenshot looks suspiciously.

**Comment by MrFredber** [comment]
Looks like you are using the outdaded version of OpenComputers. Update the mod, so you can see newly supported unicode symbols and maybe your issue will be solved.

**Comment by pikachuproge** [comment]
alright, thanks i'll try that, it's probably because i'm using the skyfactory 4 modpack which has the old version of the mod

**Comment by pikachuproge** [comment]
thanks guys, all fixed by updating the mod
