### ISSUE TITLE
Says that download servers are unavailable

### ISSUE THREAD

**Issue by WernCoreOfficial** [IgorTimofeev/MineOS#643]
uhhh idk what to _**`put`**_ here

**Comment by IgorTimofeev** [comment]
Maybe github.com is blacklisted on your server, or java version is outdated, so it still can't download anything from github

**Comment by CoolCat467** [comment]
More likely than not you are encountering the SSL issue several other people have been encountering. Please see https://github.com/IgorTimofeev/MineOS/wiki/SSL-issue.

If it is indeed the SSL issue, basically you need to re-install a new version of Java, and if so the version of java you are using has outdated SSL certificates that leads to a certificate security error. Installing a new version of java will have new versions of the SSL certificates, meaning the error should not happen any longer.
