### ISSUE TITLE
MineOS неработает и крашит игру

### ISSUE THREAD

**Issue by SingularityK-SST** [IgorTimofeev/MineOS#644]
Я уже очень долго играю с этим модом, однако около года назад перестал, и тут вернулся опять. MineOS это моя любимая ОС, однако, по неизвестным причинам она не устанавливается. После флеша биоса он просто не читается. Что я только не пробовал, уже даже мод переустанавливал - не помогает.

Ошибок очень много. Надеюсь кто-нибудь поможет

**Comment by Smok1e** [comment]
[жаба протухла, надо обновить.](https://github.com/IgorTimofeev/MineOS/wiki/SSL-issue)
