### ISSUE TITLE
Метод read()

### ISSUE THREAD

**Issue by at-elcapitan** [IgorTimofeev/MineOS#645]
При написании Отсутствует метод read (io.read(), io.stdin:read()) для получения ввода от пользователя из терминала. Если уж терминал, как способ взаимодействия с пользователем доступен, то получение ввода является вещью первой необходимости.

**Comment by IgorTimofeev** [comment]
Ты абсолютно прав, если бы терминал задумывался как средство взаимодействия. А на деле меня просто заебали вопли "А ХДЕ ТУТ PRINT ФУУУ ГАВНО", поэтому пришлось добавить окошечко. До сих пор жалею хд

А так ось чисто юайная, создавалась в противовес терминалу. Ну, знаешь, чтобы кнопочки тыкать, ползуночки дергать и т.п.

**Comment by at-elcapitan** [comment]
Первое. Операционная система вдохновлена macOS, которая, являясь основанной на BSD, (т.е. UNIX) имеет в себе консоль. 

Второе. В любой операционной системе, тем более такой, что заточена под взаимодействие с разными структурами игры (напомню, мод OpenComputers задумывался как способ автоматизации процессов по средсву программирования), консоль является вещью первой необходимости. Ведь как гласит филсофия юникс, "Избегайте графических интерфейсов там, где они могут ограничить возможности пользователя по взаимодействию с системой". 

То есть, что мы имеем. Операционная система по сути превращает компьютер из мощного инструмента автоматизации в беспомощную, но очень красочную безделушку.

**Comment by CoolCat467** [comment]
What I feel like you fail to understand is that active development for MineOS stopped quite some time ago. If you feel strongly that a proper terminal should be in MineOS, why not try your hand at making one yourself? Most of the groundwork is already there if you copy some code from the text editor and/or OpenOS.

**Comment by Smok1e** [comment]
> Первое. Операционная система вдохновлена macOS, которая, являясь основанной на BSD, (т.е. UNIX) имеет в себе консоль.
> 
> Второе. В любой операционной системе, тем более такой, что заточена под взаимодействие с разными структурами игры (напомню, мод OpenComputers задумывался как способ автоматизации процессов по средсву программирования), консоль является вещью первой необходимости. Ведь как гласит филсофия юникс, "Избегайте графических интерфейсов там, где они могут ограничить возможности пользователя по взаимодействию с системой".
> 
> То есть, что мы имеем. Операционная система по сути превращает компьютер из мощного инструмента автоматизации в беспомощную, но очень красочную безделушку.

Спасибо, что объяснил автору, чему должна следовать ось. Делай форк и ебись с ним как хочешь, удачи.

**Comment by IgorTimofeev** [comment]
> Ведь как гласит филсофия юникс

Моя философия гласит "пошёл на хуй"

**Comment by IgorTimofeev** [comment]
> Первое. Операционная система вдохновлена macOS, которая, являясь основанной на BSD, (т.е. UNIX) имеет в себе консоль.

Вдохновляться следует лучшим, избавляясь от худшего. Если наши прадеды хуярили мамонтов и резали руны на берестяной коре, то следует ли по твоей логике добавить в майнось Birch.app? Или это уже атавизм?

> (напомню, мод OpenComputers задумывался как способ автоматизации процессов по средсву программирования)

Это тебе лично Сангар признался за бутылочкой сакэ? Я с тем же успехом могу заявить, что мод пилился ради фана и личного скиллчека, чтобы параллельно поизучать Скалу и совместить приятное с полезным. Опенкомпы - это песочница, где каждый дрочит как хочет, а не загон для скота с жёсткими правилами. Тут вопрос лишь в твоей адаптивности к чужому видению

> консоль является вещью первой необходимости

Является для кого, для тебя? Ну-ка, спиздани, что же такого хитровыебанного можно реализовать в виде терминального скрипта, и чего нельзя через юай? Интересно будет почитать на досуге.  Лично я считаю терминалы мусором от неосиляторов UI/UX, способных лишь в примитивный скриптинг. Git gud, хули

> Избегайте графических интерфейсов там, где они могут ограничить возможности пользователя по взаимодействию с системой

Каким образом юай майноси ограничивает возможности пользователя по взаимодействию с ней? 

> То есть, что мы имеем. Операционная система по сути превращает компьютер из мощного инструмента автоматизации в беспомощную, но очень красочную безделушку.

Какие аспекты автоматизации перестают быть доступными из-за такого подхода? Почему внезапно компьютер становится беспомощной игрушкой?
