### ISSUE TITLE
software caused connection abort: recv failed

### ISSUE THREAD

**Issue by ToasterGithubUser** [IgorTimofeev/MineOS#648]
**To Reproduce**
trying to install mineOS from both links

**Expected behavior**
MineOS installer

**Screenshots**

![image](https://github.com/user-attachments/assets/ca2b3885-b62a-4721-9d54-c6a24a18b9d9)

**Minecraft and OpenComputers version**
MC 1.12.2 Opencomputers 1.8.6

**Comment by Bumer-32** [comment]
Not a MineOS issue
#647

**Comment by Bumer-32** [comment]
@Smok1e нихуя оперативность, прокоментировал и сию минуту уже закрыто
