### ISSUE TITLE
Workspace doesn't render when stopped and started again

### ISSUE THREAD

**Issue by mindbound** [IgorTimofeev/MineOS#649]
I used the Braille canvas example from the wiki, with the following added event handler function:

```
workspace.eventHandler = function(workspace, object, e1, e2, e3, e4, e5)
    if e1 == "key_down" then
        workspace:stop()
    end

    workspace:draw()
end
```

On a key press, the code terminates normally. When I run the script for the second time, nothing is rendered on the screen, even though the event handler itself seems to work normally and there are no errors. When I reboot the computer, the workspace is rendered correctly when I run the script for the first time (after which it fails to render again). This behaviour is not exclusive to the Braille canvas example and seems to affect any workspace regardless of its child contents.

I'm running the code on MC 1.7.10, OC 1.10.27-GTNH.

What could I be doing wrong? TIA!

**Comment by IgorTimofeev** [comment]
Hmm, what do you do after calling `workspace:stop()`? Do you drawing something directly to screen buffer? If so, yo should call `workspace:draw()` before calling `workspace:start()`. Otherwise give pls full code example, it's hard to determine problem

```lua
local GUI = require("GUI")
local event = require("Event")
local screen = require("Screen")

--------------------------------------------------------------------------------

local workspace = GUI.workspace()
workspace:addChild(GUI.panel(1, 1, workspace.width, workspace.height, 0x2D2D2D))

workspace:addChild(GUI.button(3, 2, 26, 3, 0xEEEEEE, 0x000000, 0xAAAAAA, 0x0, "Button"))

workspace.eventHandler = function(workspace, object, e1, e2, e3, e4)
	if e1 ~= "key_down" then
		return
	end

	-- Stopping workspace
	workspace:stop()

	-- Drawing something directly into screen buffer
	screen.drawRectangle(10, 10, 30, 4, 0xFF4940, 0x0, " ")
	screen.update()

	GUI.alert("Done")

	-- Restarting workspace
	workspace:draw()
	workspace:start()
end


--------------------------------------------------------------------------------

workspace:draw()
workspace:start()
```

**Comment by mindbound** [comment]
>  If so, yo should call `workspace:draw()` before calling `workspace:start()`

That seems to have helped, thanks!
