### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by redstonelogi** [IgorTimofeev/MineOS#651]
Hello, i cant install MineOS. Not with the pastebin link and not with the wget command. If i try to install aps, it comes up with an error and finally, the Recovery Script in boot menu doesn't work also.

**Comment by Smok1e** [comment]
https://github.com/IgorTimofeev/MineOS/wiki/SSL-issue

**Comment by redstonelogi** [comment]
okay now it works. thanks
